/*
 * Optocoupler
 */
INSERT INTO item( name, description, category, quantity, locationBox, status, locationImage, locationDatasheet, locationAttachment ) VALUES
(	'MOC3020 - Acoplador Óptico',
	'Acoplador Óptico que também é isolador. Driver Fototriac para saída 250V. Driver de saída projetado para 220V AC.',
	'Optocoupler',
	7,
	'',
	'NOT ORGANIZED',
	'MOC3020.jpg',
	'',
	''),
	
(	'6N138 - Acoplador Óptico',
	'Acoplador óptico de alta velocidade, 100kBd, corrente de entrada baixa e saída de fotodiodo acoplador com aplicações em interface de sistemas de microprocessamento, recepção de linha RS232, tradução de tensão TTL e CMOS, entre outras.',
	'Optocoupler',
	12,
	'',
	'NOT ORGANIZED',
	'6N138.jpg',
	'',
	''),
	
(	'TLP521 - Acoplador Óptico',
	'Acoplador óptico com um fototransistor dimensões 6.4+-0.25 x 4.58+-0.25 mm com 0.26g.',
	'Optocoupler',
	1,
	'',
	'NOT ORGANIZED',
	'TLP521 - Acoplador Optico.jpg',
	'',
	''),
	
(	'EL817 - Acoplador Óptico',
	'Acoplador óptico com VCE=5V e IF=5mA.',
	'Optocoupler',
	4,
	'',
	'NOT ORGANIZED',
	'EL817.jpg',
	'',
	''),
(	'4N25 - Acoplador Óptico',
	'Acoplador óptico com fototransistor de saída e com conexão de base.',
	'Optocoupler',
	9,
	'',
	'NOT ORGANIZED',
	'4N25.jpg',
	'',
	''),
	
(	'6N139 - Acoplador Óptico',
	'Acoplador óptico de alta velocidade, 100kBd, corrente de entrada baixa e saída de fotodiodo acoplador com aplicações em interface de sistemas de microprocessamento, recepção de linha RS232, tradução de tensão TTL e CMOS, entre outras.',
	'Optocoupler',
	8,
	'',
	'NOT ORGANIZED',
	'6N139.jpg',
	'6N138, 6N139.pdf',
	''),
	
(	'H11AA1 - Optoacoplador com entrada AC  e Fototransistor de saída com conexão de base',
	'Entrada AC ou entrada com duas polaridades; I/O compatível com circuitos integrados; Teste de tensão de isolação: 5300 VRMS',
	'Optocoupler',
	1,
	'',
	'NOT ORGANIZED',
	'H11AA1_1.jpg;H11AA1_2.jpg',
	'H11AA1 - Optocoupler, Phototransistor Output, AC Input, with Base Connection.pdf',
	'')
;