/*
 * Operational Amplifier
 */
INSERT INTO item( name, description, category, quantity, locationBox, status, locationImage, locationDatasheet, locationAttachment ) VALUES
(	'741 - Amplificador Operacional de Uso Geral',
	'Amplificador Operacional com proteção, ganho em torno de 200V/mV, resistência de entrada de 2 MOhms e resistência de saída de 75 Ohms.',
	'Operational Amplifier',
	6,
	'',
	'NOT ORGANIZED',
	'741-op-amp.png',
	'',
	''),
	
(	'INA118 - Amplificador de instrumentação',
	'Amplificador de instrumentação INA118, de baixa potência e alta precisão, com ganho de 1 até 10000. Alimentação de +-1.35~+-18V.',
	'Operational Amplifier',
	1,
	'',
	'NOT ORGANIZED',
	'INA118-INA118P-DIP8.jpg',
	'',
	''),
	
(	'OPA544 - Amplificador Operacional de média potência',
	'Wide Power Supply Range: ±10V ~ ± 35V; Output Current: 4A (Typ); GBW: 1.4MHz (Typ); Slew Rate: 8V/us (Typ); Vos (Offset Voltage@25C): 5mV (Max); Offset Drift: 10uV/C (Typ); Iq per channel: 12mA (Typ); Input Bias Current: 100pA (Max); CMRR: 106dB (Typ)',
	'Operational Amplifier',
	1,
	'',
	'NOT ORGANIZED',
	'OPA544.jpg',
	'OPA544 - High-Voltage, High-Current Operational Amplifier.pdf',
	''),
	
(	'LM358 - Dual amplificador operacional de baixa potência',
	'Dual amplificador operacional de baixa potência com grande ganho de tensão DC de 100dB, larga largura de banda (ganho unitário) de 1MHz com tensão de alimentação variando entre 3V~32V.',
	'Operational Amplifier',
	1,
	'',
	'NOT ORGANIZED',
	'LM358.jpg',
	'',
	''),
	
(	'LM324 - Quatro Amplificadores Operacional',
	'Quatro Amplificadores Operacional em um único chip, circuito de saída protegido, intervalo de alimentação de 3~32V, entre outras características.',
	'Operational Amplifier',
	1,
	'',
	'NOT ORGANIZED',
	'LM324.jpg',
	'',
	''),
	
(	'LF351 - Amplificador Operacional com estágio de entrada com JFET',
	'Internally adjustable input offset voltage; Low input bias and offset current; Output short-circuit protection; High input impedance JFET input stage; Internal frequency compensation; Latch up free operation; High slew rate 16 V/µs (typical)',
	'Operational Amplifier',
	1,
	'',
	'NOT ORGANIZED',
	'LF351N-LF351-OPAMP-JFET-4MHZ-8DIP_1.jpg;LF351N-LF351-OPAMP-JFET-4MHZ-8DIP_2.jpg',
	'LF351 - Wide bandwidth single JFET operational amplifiers.pdf',
	''),
	
(	'LM3900 - Amplificador Operacional',
	'VCC (single)/VCC+ (dual)/VCC– (dual): 4.5~32 V/2.2~16 V/–2.2~–16 V; AVD - Large-signal differential voltage amplification (VO=10 V, f=100 Hz, RL=10 kΩ) MIN/TYP: 1.2/2.8 V/mV; resistance ri - Input (inverting input)/ro - Output: 1 MΩ/8 kΩ',
	'Operational Amplifier',
	1,
	'',
	'NOT ORGANIZED',
	'LM3900.jpg',
	'LM3900 - Quadruple Norton Operational Amplifiers.pdf',
	''),
	
(	'TBA820M - Amplificador de Audio de 1.2W',
	'Supply voltage (Vs): 3~16 V; Output peak current (Io): 1.5 A; Power dissipation at Tamb=50°C (Ptot): 1 W; Input resistance [pin 3] f=1 kHz (Ri): 5 MΩ',
	'Operational Amplifier',
	1,
	'',
	'NOT ORGANIZED',
	'TBA820M.jpg',
	'TBA820M - 1.2W Audio Amplifier.pdf',
	''),
	
(	'TL072CP - Amplificador Operacional com entrada JFET e baixo ruído',
	'Baixo consumo de alimentação; Proteção de saída de curto-circuito; Baixa distorção total harmônica: 0.003% (Típico); Alta Impedância de entrada (estágio de entrada JFET); Alto taxa de Slew: 13 V/μs (Típico)',
	'Operational Amplifier',
	2,
	'',
	'NOT ORGANIZED',
	'TL072.jpg',
	'TL07xx Low-Noise JFET-Input Operational Amplifiers.pdf',
	''),
	
(	'TL071CP - Amplificador Operacional com entrada JFET e baixo ruído',
	'Baixo consumo de alimentação; Proteção de saída de curto-circuito; Baixa distorção total harmônica: 0.003% (Típico); Alta Impedância de entrada (estágio de entrada JFET); Alto taxa de Slew: 13 V/μs (Típico); Pinos de offset',
	'Operational Amplifier',
	2,
	'',
	'NOT ORGANIZED',
	'TL071.jpg',
	'TL07xx Low-Noise JFET-Input Operational Amplifiers.pdf',
	''),
	
(	'LM311 - Comparador diferencial',
	'Tempo de resposta rápida: 165 ns; Corrente máxma de bias de entrada: 300 nA; Corrente máxida de offset de entrada: 70 nA; Pode ser operado com simples fonte 5 V',
	'Operational Amplifier',
	2,
	'',
	'NOT ORGANIZED',
	'LM311.jpg',
	'LM111, LM211, LM311 Differential Comparators.pdf',
	''),
	
(	'LM339 - 4 Comparadores diferencial',
	'Wide Supply Ranges; Single Supply: 2 V to 36 V; Dual Supplies: ±1 V to ±18 V; Low Supply-Current Drain Independent of Supply Voltage: 0.8 mA (Typ); Low Input Bias Current: 25 nA (Typ); Low Input Offset Voltage: 2 mV (Typ)',
	'Operational Amplifier',
	1,
	'',
	'NOT ORGANIZED',
	'LM339.jpg',
	'LM339, LM239, LM139, LM2901 Quad Differential Comparators.pdf',
	''),
	
(	'OP07 - Ultralow Offset Voltage Operational Amplifier',
	'Low VOS: 75 μV maximum; Low VOS drift: 1.3 μV/°C maximum; Ultrastable vs. time: 1.5 μV per month maximum; Low noise: 0.6 μV p-p maximum; Wide input voltage range: ±14 V typical; Wide supply voltage range: ±3 V to ±18 V; 125°C temperature-tested dice',
	'Operational Amplifier',
	4,
	'',
	'NOT ORGANIZED',
	'OP07;Figure1.jpg',
	'OP07;OP07.pdf',
	'')
;