INSERT INTO components( name, description, category, quantity, locationBox, status, locationImage, locationDatasheet, locationAttachment ) VALUES
(
	'Módulo Serial I2C para Display LCD',
	'Módulo Serial I2C para Display LCD para conexão de display ao Arduino usando o chip PCF8574',
	'DIY',
	1,
	'Box 000',
	'ORGANIZED',
	'Serial LCD I2C Module with chip PCF8574;Figure 1.jpg;Figure 2.jpg;Figure 3.jpg;Figure 4.jpg',
	'Serial LCD I2C Module with chip PCF8574;Schemas.pdf',
	'Serial LCD I2C Module with chip PCF8574;New LiquidCrystal _ wiki _ Home — Bitbucket.pdf;NewLiquidCrystal_1.5.1.zip'
),
(
	'Módulo LCD Nokia 5110',
	'Módulo LCD Nokia 5110 de 1.6\" com chip PCD8544 de 48x48 pixels com tensão de 2.7V ~ 3.3V, interface SPI, corrente de operação <5mA, com iluminação <20mA.',
	'DIY',
	1,
	'Box 000',
	'ORGANIZED',
	'Module LCD Nokia 5110;Figure 1.jpg',
	'Module LCD Nokia 5110;Nokia5110.pdf',
	'Module LCD Nokia 5110;Adafruit-PCD8544-Nokia-5110-LCD-library-1.1.1.zip;Adafruit-GFX-Library-1.7.4.zip;BitmapEncoder-master.zip;LCDAssistant.zip;LCDAssistantCMD.zip;TheDotFactory-0.1.4.7z'
),
(
	'AGM-1604A-801 - Display de Cristal Liquido',
	'Display de Cristal Liquido modelo AGM-1604A-801, no formato 16*4 caracteres, com luz branca de fundo e cor de fundo azul.',
	'DIY',
	1,
	'Box 000',
	'ORGANIZED',
	'16x4 LCD Display White-Blue LED Backlight;Figure 1.jpg',
	'16x4 LCD Display White-Blue LED Backlight;AGM-1604A-801.pdf',
	'16x2 LCD Display White-Blue LED Backlight;Arduino - HelloWorld.pdf;In-Depth Tutorial to Interface 16x2 Character LCD Module with Arduino.pdf;HelloWord.ino'
),
(
	'Módulo Touch Screen TFT 3.2in',
	'Módulo Touch Screen TFT 3.2in, modelo TFT01-3.2, com 65k core, resolução 320x240 pixels e tensão de trabalho de 3.3V.',
	'DIY',
	1,
	'Box 000',
	'ORGANIZED',
	'3.2 inch TFT LCD Screen Module;Figure 1.jpg;Figure 2.jpg',
	'3.2 inch TFT LCD Screen Module;SSD1289-spec.pdf',
	'3.2 in TFT LCD Screen Module;UTFT.zip;3.2 inch TFT Touch LCD.zip;LCD 3.2 TFT LCD Screen Module.zip;The instruction for mega2560 board and 3.2 inch touch screen and shield.zip'
),
(
	'1602A - Módulo LCD com 16 caracteres por 2 linhas e fundo azul',
	'Modelo 6514 com 16 caracteres x 2 linhas, luz de fundo azul, caracteres branco e tensão de alimentação de 5VDC',
	'DIY',
	1,
	'Box 000',
	'ORGANIZED',
	'16x2 LCD Display White-Blue LED Backlight;Figure 1.jpg;Figure 2.jpg;Figure 3.jpg',
	'16x2 LCD Display White-Blue LED Backlight;eone-1602a1.pdf',
	'16x2 LCD Display White-Blue LED Backlight;Arduino - HelloWorld.pdf;In-Depth Tutorial to Interface 16x2 Character LCD Module with Arduino.pdf;HelloWord.ino'
),
(
	'GTM2088ARGB-28 - Matriz de LEDs RGB 8x8 com super brilho',
	'Matriz de LEDs RGB 8x8 com super brilho, tensão 2.3V (Red)/3.4V (Green)/3.4V (Blue) e corrente de 50mA.',
	'LED',
	1,
	'Box 000',
	'ORGANIZED',
	'LED Matrix 8x8 - Triple Color RGB common Anode Display - 5mm;Figure 1.jpg;Figure 2.jpg;Figure 3.jpg;Figure 4.jpg;Figure 5.jpg;Figure 6.jpg',
	'LED Matrix 8x8 - Triple Color RGB common Anode Display - 5mm;GTM2088ARGB-28.pdf',
	'LED Matrix 8x8 - Triple Color RGB common Anode Display - 5mm;Product Description.txt;8×32 Scrolling LED Message Display.zip'
),
(
	'Módulo matriz de LEDs vermelho com MAX7219',
	'Módulo matriz de LEDs (8x8) vermelho com catodo comum usando o chip MAX7219, alimentado em 5VDC, comunicação SPI e dimensões de 5cm de comprimento, 3.2cm de largura e 1.5cm de altura.',
	'LED',
	1,
	'Box 000',
	'ORGANIZED',
	'MAX7219 Dot Matrix Display Module;Figure 1.jpg',
	'MAX7219 Serially Interfaced, 8-Digit LED Display Drivers;MAX7219-MAX7221 Serially Interfaced, 8-Digit LED Display Drivers.pdf',
	'MAX7219 Dot Matrix Display Module;LedControl-master.zip;8x8 LED Matrix MAX7219 Tutorial with Scrolling Text and Android Control via Bluetooth.zip;Aprenda a usar o Módulo Matriz de LEDs com MAX7219 - Embarcados.pdf'
),
(
	'Módulo LED RGB para Arduino',
	'Módulo 5050 (JY-MCU) LED RGB SMD de três cores para Arduino, podendo obter cores diferentes usando PWM.',
	'LED',
	1,
	'Box 000',
	'ORGANIZED',
	'SMD 5050 RGB LED Module;Figure 1.png',
	'SMD 5050 RGB LED Module;5050LED.pdf',
	'SMD 5050 RGB LED Module;3 Color RGB LED Module - Summerfuel Robotics.pdf'
),
(
	'Módulo OLED Display 0.96 polegadas Azul/Amarelo 128X64 SPI',
	'Módulo OLED Display de 0.96 polegadas nas cores Azul e Amarelo com resolução de 128X64 pixels e comunicação SPI.',
	'LED',
	1,
	'Box 000',
	'ORGANIZED',
	'0.96 inch SPI Serial 128X64 Yellow Blue OLED Display Module;Figure 1.jpg;Figure 2.jpg;Figure 3.jpg;Figure 4.jpg',
	'0.96 inch SPI Serial 128X64 Yellow Blue OLED Display Module;SSD1306.pdf',
	'0.96 inch SPI Serial 128X64 Yellow Blue OLED Display Module;Adafruit_SSD1306-2.0.4.zip;Adafruit-GFX-Library-1.7.4.zip'
),
(
	'Módulo OLED Display 1.3 polegadas Branco 128X64 SPI',
	'Módulo OLED Display de 1.3 polegadas na cor Branca com resolução de 128X64 pixels e comunicação SPI.',
	'LED',
	1,
	'Box 000',
	'ORGANIZED',
	'1.3 inch SPI Serial 128X64 Yellow Blue OLED Display Module;Figure 1.jpg;Figure 2.jpg;Figure 3.jpg;Figure 4.jpg',
	'1.3 inch SPI Serial 128X64 Yellow Blue OLED Display Module;sh1106_datasheet.pdf',
	'1.3 inch SPI Serial 128X64 Yellow Blue OLED Display Module;Getting started with µOLED displays.zip'
),
(
	'Fonte Ajustável para Protoboard',
	'Fonte Ajustável para Protoboard (YwRobot Breadboard Power Supply) com saídas de 3.3V e 5V.',
	'DIY',
	3,
	'Paper Box 05',
	'ORGANIZED',
	'Fonte Ajustável para Protoboard.jpg',
	'',
	''
),
(
	'Módulo Buck-boost para FPV com LM2587 para entrada de 3 ~ 35V para 1,2 ~ 30V 2A DC',
	'Módulo Buck-boost para FPV com LM2587 para entrada de 3 ~ 35V para 1,2 ~ 30V 2A DC.',
	'DIY',
	1,
	'Paper Box 05',
	'ORGANIZED',
	'Módulo Buck-boost para FPV.png',
	'',
	''
)
(
	'Placa Amplificadora Stereo com TDA2030A',
	'Placa Amplificadora Stereo com TDA2030A com duplo canal para acesso OCL 18Wx2 ou mono BTL 36Wx1. Resistores de 1% de metal de filmes, Chemi-Con e Panasonic capacitores, 2x3300uF/25V como filtro. Tensão de entrada AC 9V-12V.',
	'DIY',
	1,
	'Paper Box 05',
	'ORGANIZED',
	'Placa Amplificadora Stereo TDA2030A 2.1.jpg',
	'',
	''
),
(
	'RD084DY002 - Módulo de Recarga de Bateria de Lítio 1A',
	'Módulo de Recarga de Bateria de Lítio 1A, com LED indicador de carga. Modelo RD084DY002',
	'DIY',
	1,
	'Paper Box 05',
	'ORGANIZED',
	'Módulo de Recarga de Bateria de Lítio 1A.jpg',
	'',
	''
),
(
	'Placa de Expansão GSM/GPRS FreeArduino',
	'Placa de Expansão GSM/GPRS FreeArduino usada para fazer/receber ligações, enviar/receber mensagens como também transferências de dados.',
	'DIY',
	1,
	'Paper Box 05',
	'ORGANIZED',
	'Placa de Expansão GSM-GPRS FreeArduino.jpg',
	'',
	''
),
(
	'Sensor de nível de água',
	'Sensor de nível de água para ser usado no Arduino.',
	'DIY',
	1,
	'Paper Box 05',
	'ORGANIZED',
	'Sensor de nível de água.jpg',
	'',
	''
),
(
	'Válvula Elétrica Solenoide para água e ar',
	'Válvula Elétrica Solenoide para água e ar NO e NC com tensão de alimentação de 12V com 0.5in normalmente fechada.',
	'DIY',
	1,
	'Paper Box 05',
	'ORGANIZED',
	'Válvula Elétrica Solenoide para água e ar.jpg',
	'',
	''
),
(
	'Ethernet Shield com Wiznet W5100',
	'Ethernet Shield com Wiznet W5100 para conexão a cabo para Arduino.',
	'DIY',
	1,
	'Paper Box 05',
	'ORGANIZED',
	'Ethernet Shield com Wiznet W5100.jpg',
	'',
	''
),
(
	'Módulo Encoder Rotação de 360°',
	'Módulo Encoder Rotação de 360° com resolução de 20 pulsos por revolução e corrente máxima de 10mA.',
	'DIY',
	1,
	'Paper Box 05',
	'ORGANIZED',
	'Módulo Encoder Rotação de 360.jpg',
	'',
	''
),
(
	'Módulo reconhecimento de impressão digital',
	'Módulo reconhecimento de impressão digital com frequência de trabalho de 433MHz,868MHz ou 915MHz. Sensibilidade de -100dBm, tensão de alimentação de 3.6~6V, tamanho dos caracteres de 256 bytes, tempo de pesquisa < 1 segundo.',
	'DIY',
	1,
	'Paper Box 05',
	'ORGANIZED',
	'Modulo reconhecimento de impressão digital.jpg',
	'ZFM-20_Series_Fingerprint_Identification_Module-User_Manual.pdf;DY001fingerprint.pdf;adafruit-optical-fingerprint-sensor.pdf',
	'SFGDemoV2.0.rar;Adafruit-Fingerprint-Sensor-Library-master.zip'
),
(
	'ZHO-0420S-05A4.5 - Mini Solenóide 5V',
	'Mini Solenóide 5V com curso do eixo de aproximadamente 4,5mm, diâmetro do eixo de 1,6mm (3mm na extrimidade), corrente de alimentação de 1.1A. Modelo ZHO-0420S-05A4.5',
	'DIY',
	1,
	'Paper Box 05',
	'ORGANIZED',
	'Mini Solenóide 5V.jpg',
	'',
	''
),
(
	'PCF8574 - Placa de Expansão',
	'Placa de Expansão PCF8574 no qual pode ser conectado por I2C provendo até 64 portas I/O. A placa é uma interface 8-bit paralela.',
	'DIY',
	1,
	'Paper Box 05',
	'ORGANIZED',
	'Placa de Expansão PCF8574.jpg',
	'',
	''
),
(
	'DS1307 - Módulo de Real Time Clock',
	'Módulo de Real Time Clock (RTC) com memória 24C32 de 32K com comunicação I2C e chip DS1307.',
	'DIY',
	1,
	'Paper Box 05',
	'ORGANIZED',
	'Módulo de Real Time Clock RTC DS1307 DS-1307 AT24C32.jpg',
	'',
	''
),
(
	'Protoshield',
	'Protoshield desenvolvido para criar shields de acordo com a necessidade do usuário com dois botões, dois leds, entradas para NOKIA 5110, LCM 1602, entre outros.',
	'DIY',
	1,
	'Paper Box 05',
	'ORGANIZED',
	'protoshield-prototype-para-arduino-protoboard-170-pontos1.jpg;protoshield-prototype-para-arduino-protoboard-170-pontos2.jpg',
	'',
	''
),
(
	'Shield de Sensor 5.0',
	'Shield de Sensor no qual podem ser conectados módulo bluetooth, sdcard, display, sensores, entre outros. As dimensões são de 5.7 x 5.7 x 2 cm.',
	'DIY',
	1,
	'Paper Box 05',
	'ORGANIZED',
	'Shield de Sensor 5.0.jpg',
	'',
	''
),
(
	'W908 - Ibeacon',
	'Ibeacon W908 com chip CC2541, a prova de água, uso de bateria CR2477, range efetivo de 30m e máximo de 100m e corrente de 100uA (standby).',
	'DIY',
	1,
	'Paper Box 05',
	'ORGANIZED',
	'ibeacon w908.jpg;Ibeacon w908 -Bluetooth-TICC2541.jpg',
	'',
	''
),
(
	'PCW2138WC - Carregador sem fio',
	'Carregador sem fio (PCW2138WC) com entrada/saída de 5~12VDC/(5VDC/600mA), indutância da bobina de transmissão de 30uH, distância de transmissão de 1~20mm, diâmetro da bobina de 38mm e altura da bobina de 2mm.',
	'DIY',
	1,
	'Paper Box 05',
	'ORGANIZED',
	'Carregador sem fio.jpg',
	'',
	''
),
(
	'HLK-RM04 - Módulo Adaptador Wi-Fi',
	'Módulo Adaptador Wi-Fi HLK-RM04 com antena onboard e externa, modo client/AP/server, com todas as funcionalidades de rede com e sem fio.',
	'DIY',
	1,
	'Paper Box 05',
	'ORGANIZED',
	'Módulo Adaptador Wi-Fi HLK-RM04.jpg',
	'',
	''
),
(
	'PCF8591 - Módulo Conversor de 8-Bit A/D e D/A',
	'Módulo Conversor PCF8591 de 8-Bit A/D e D/A, tensão de 2.5~6V, 3 pinos de entrada (A0, A1 e A2) e 4 pinos de entrada analógicos programados como saída simples ou entrada diferencial.',
	'DIY',
	1,
	'Paper Box 05',
	'ORGANIZED',
	'Módulo Conversor PCF8591 - 1.jpg;Módulo Conversor PCF8591 - 2.jpg;Módulo Conversor PCF8591 - 3.jpg;Módulo Conversor PCF8591 - 4.jpg',
	'',
	''
),
(
	'Módulo Transmissor/Receptor RF de 433MHz',
	'Corrente transm. máx<=40mA (12V), mín<=9mA (3V), modo ressonante/modulação SAW/(ASK/OOK), freq. trab. 315~433.92MHz, pot. trans. 25mW (315MHz,12V), erro freq. 150kHz (máx), vel. <=10kbps,  intervalo de trans. 20~200m.',
	'DIY',
	1,
	'Paper Box 05',
	'ORGANIZED',
	'Modulo Transmissor-Receptor RF de 433MHz.jpg',
	'',
	''
),
(
	'Módulo Player MP3 Music com controle Serial UART',
	'Suporte a formato MP3 e WAV, controle por UART, frequência de amostragem de 8kHz~48kHz, tensão de alimentação de 3.2~5.2VDC, suporte para Micro SD (SDHC) Card <=2G (<16G).',
	'DIY',
	1,
	'Paper Box 05',
	'ORGANIZED',
	'Modulo Player MP3 Music com controle Serial UART1.jpg;Modulo Player MP3 Music com controle Serial UART2.jpg',
	'',
	''
),
(
	'KY-023 - Módulo Joystick',
	'Módulo joystick PS2, no qual tem um cross rocker que é um resistor bidirecional 10K, com balancim em direções diferentes, a resistência muda com direção, fonte de alimentação 5V, estado original x, tensão de leitura Y é de cerca de 2,5V.',
	'DIY',
	1,
	'Paper Box 05',
	'ORGANIZED',
	'Módulo Joystick KY-023.jpg',
	'',
	''
),
(
	'TEA5767 - Módulo Receptor FM',
	'Módulo receptor FM com suporte de frequência entre 76~108MHz usando o chip Philips TEA5767.',
	'DIY',
	1,
	'Paper Box 05',
	'ORGANIZED',
	'Módulo Receptor FM TEA57671.jpg;Módulo Receptor FM TEA5767_pinout.jpg;Módulo Receptor FM TEA5767_schematictea.jpg',
	'',
	''
),
(
	'OV7670 - Módulo Camera VGA 300KP',
	'Array fotosensível 640x480, tensão IO 2.5~3.0V, formato saída YUV/YCbCr4:2:2 RGB565/555/444 GRB4:2:2 Raw RGB Data (8 digit), tamanho lente 1/6\"; ângulo visão 25 graus; taxa frame máx. 30fps VGA, sensibilidade 1.3V/(Lux-sec), sinal taxa ruído 46 dB',
	'DIY',
	1,
	'Paper Box 05',
	'ORGANIZED',
	'Módulo Camera VGA 300KP OV7670.jpg',
	'',
	''
),
(
	'Joystick Escudo v1.2',
	'Um Joystick para adicição do Nokia 5110 LCD e interface de nRF24L01. Pode-se desenvolver facilmente jogos com Joystick, e até a comunicação entre si com nRF24L01 wireless. ',
	'DIY',
	1,
	'Paper Box 05',
	'ORGANIZED',
	'Joystick Escudo v1.2.jpg',
	'',
	''
),
(
	'Cabo conversor IPX para RP-SMA macho',
	'Cabo conversor adaptador IPX para RP-SMA macho com comprimento de 19cm.',
	'DIY',
	1,
	'Paper Box 05',
	'ORGANIZED',
	'Cabo conversor IPX para RP-SMA macho.jpg',
	'',
	''
),
(
	'Conversor Lógico Bidirecional 5V/3V',
	'Conversor nível lógico de 4 canais para Arduino, em uso de I2C.',
	'DIY',
	6,
	'Paper Box 05',
	'ORGANIZED',
	'Conversor Lógico Bidirecional 5V-3V.jpg',
	'',
	''
),
(
	'A7 - Placa de Desenvolvimento GPS GPRS GSM SMS e Módulo de Voz',
	'Placa de Desenvolvimento A7 GPS GPRS GSM SMS e Módulo de Voz com tensão de alimentação de 3.3~4.2V, suporte as frequ&ecirc;ncias 850/900/1800/1900 MHz com duas antenas.',
	'DIY',
	1,
	'Paper Box 05',
	'ORGANIZED',
	'Placa de Desenvolvimento A7 GPS GPRS GSM SMS e Módulo de Voz.jpg',
	'',
	''
),
(
	'ATK-NEO-6M-V12 - Módulo GPS  com antena Ulbox',
	'Taxa 4.8k/9.6k/38.4k(padrão)/57.6k; 3.3/5V sistema SCM; GPS L1 (1575.42MHZ) código C/A; SBAS:WAAS/EGNOS/MSAS; Precisão:2.5 MCEP (SBAS2.0mCEP); Inicio a frio/quente:27s (mais rápido)/1s; Sensibilidade:161dBm; Protocolo:NMEA(padrão)/UBX Binary',
	'DIY',
	1,
	'Paper Box 05',
	'ORGANIZED',
	'Módulo GPS  com antena Ulbox ATK-NEO-6M-V121.jpg;Módulo GPS  com antena Ulbox ATK-NEO-6M-V122.jpg;Módulo GPS  com antena Ulbox ATK-NEO-6M-V123.jpg',
	'',
	''
),
(
	'CD74HC4067 - Placa com Multiplexador/Demultiplexador Analógico de 16 canais',
	'Multiplexador/Demultiplexador analógico com tensão de trabalho de 2~6V. Modelo CD74HC4067 de 16 canais.',
	'DIY',
	1,
	'Paper Box 05',
	'ORGANIZED',
	'Placa com Multiplexador-Demultiplexador Analógico CD74HC4067 de 16 canais.jpg',
	'',
	''
),
(
	'CNC Shield V3 para impressora 3D com 4 Drivers A4988',
	'CNC Shield com tensão de 12~36VDC, botão reset, 4 eixos (X, Y, Z e A), entrada para conectores de fim de curso para cada eixo. Compatível com Arduino UNO e GRBL.',
	'DIY',
	1,
	'Paper Box 05',
	'ORGANIZED',
	'CNC Shield V3 para impressora 3D com 4 Drivers A4988_1.jpg;CNC Shield V3 para impressora 3D com 4 Drivers A4988_2.jpg',
	'',
	''
),
(
	'Controle para uso em MP3',
	'Controle para uso em MP3. Uso de duas pilhas de relógio. Há 21 teclas incluindo turn on/off, mode, play e pause, mute, entre outros.',
	'Equipamento',
	1,
	'Paper Box 05',
	'ORGANIZED',
	'Controle para uso em MP3.jpg',
	'',
	''
),
(
	'Módulo DRF1278F LoRa 433MHz SX1278',
	'Frequency Range: 433MHz Modulation: FSK/GFSK/MSK/LoRa SPI Data Interface Sensitivity: -136dBm Output Power: +20dBm Data Rate: <300 kbps 127dB dynamic Range RSSI Packet engine up to 256 bytes with CRC Standby current: 1uA Supply voltage: 1.8~3.6V',
	'DIY',
	2,
	'Paper Box 05',
	'ORGANIZED',
	'LoRa_SX1278_433MHz_Module_DRF1278F_1.jpg;LoRa_SX1278_433MHz_Module_DRF1278F_2.jpg;LoRa_SX1278_433MHz_Module_DRF1278F_3.jpg;LoRa_SX1278_433MHz_Module_DRF1278F_4.jpg',
	'DRF1278F - 20dBm LoRa Long Range RF Front-end Module.pdf',
	''
),
(
	'Célula de Carga para balança de até 50kg',
	'Capacity:40~50 kg Error:0.05 mv/v Output Sensitivity:1.0±0.1 mv/v Nonlinearity:0.03 %FS Repeatability:0.03 %FS Hysteresis:0.03 %FS Zero Output:±0.1 mV/V Input Resistance:1000±20 Ω Insulation Resistance:≥5000 MΩ Overload Capacity:150 %FS',
	'DIY',
	1,
	'Paper Box 05',
	'ORGANIZED',
	'Load Sensor - 50kg_1.jpg;Load Sensor - 50kg_2.jpg',
	'Load Sensor - 50kg.pdf',
	''
),
(
	'Módulo TTL para RS485 para Arduino',
	'Chipset MAX485; 2 pinos para comunicação e fiação fácil RS-485 Tensão de trabalho de 5V',
	'DIY',
	2,
	'Paper Box 05',
	'ORGANIZED',
	'Módulo TTL para RS485 para Arduino_1.jpg;Módulo TTL para RS485 para Arduino_2.jpg;Módulo TTL para RS485 para Arduino_3.jpg',
	'',
	''
),
(
	'Módulo sem fio NRF24L01 + PA + LNA (com antena)',
	'Controlador: NRF24L01+ Frequência: 2.4GHz Tensão de operação: 1.9 à 3.6V Taxa de transferência: 2 Mbit/s Corrente em power down: 400nA Corrente em standby: 32uA Dimensões: 29 x 15mm Regulador de tensão embutido Conector para antena SMA',
	'DIY',
	2,
	'Paper Box 05',
	'ORGANIZED',
	'NRF24L01 + PA + LNA (com antena)_1.jpg;NRF24L01 + PA + LNA (com antena)_2.jpg',
	'nRF24L01P_Product_Specification_1_0.pdf;nWP_011_v1.1.pdf;RF_Test_Instructions_nRF24L01P_v1_0.pdf;Tuning_the_nFR24xx_matching_network.pdf',
	'nAN24-12.zip;nRF24L01P-EK.zip'
),
(
	'Módulo SD Card',
	'LED indicador Suporte para SD Card Pinos: GND, 3.3V, 5V, CS, MOSI, SCK, MISO e GND',
	'DIY',
	1,
	'Paper Box 05',
	'ORGANIZED',
	'SD_Card_Module_1.jpg;SD_Card_Module_2.jpg;SD_Card_Module_Pin_Outs.png',
	'SDCard Module_schematic.pdf;Micro SD Data Sheet.pdf;SDCard Datasheet  SDCard V 1.2.pdf',
	''
),
(
	'Conversor Digital para Analógico de 12Bits com memória EEPROM',
	'O módulo CJMCU-MCP4725 é um conversor DAC (Digital-to-Analog Converter) controlado por I2C. Caracteristicas: resolução de 12bits Interface I2C (suportados os modos Standard, Fast, e High-Speed) Alimentção de 2.7~5.5V',
	'DIY',
	1,
	'Paper Box 05',
	'ORGANIZED',
	'MCP4725_1.png;MCP4725_2.jpg;MCP4725_3.jpg',
	'MCP4725.pdf',
	''
),
(
	'X9C103S - Potenciômetro 10kΩ controlado digitalmente',
	'Potenciômetro controlado digitalmente com resistência de 10k Ohms, com 99 posições e com tensão de alimentação entre 3V à 5V. Corrente máx. ativa de 3mA. Corrente máx. standby de 750µA. Duração de 100000 trocas de dados por bit.',
	'DIY',
	3,
	'Paper Box 05',
	'ORGANIZED',
	'x9c103s_digital_potentiometer_module_2.jpg;x9c103s_digital_potentiometer_module_1.jpg;Potenciômetro Digital X9C103S_1.jpg;Potenciômetro Digital X9C103S_2.jpg;Potenciômetro Digital X9C103S_3.jpg;Potenciômetro Digital X9C103S_4.jpg',
	'X9C102, X9C103, X9C104, X9C503 - Digitally Controlled Potentiometer.pdf',
	''
),
(
	'Conversor RS232 para TTL',
	'Transceiver : 2 (1 TTL -> RS232 + 1 TTL <- RS232) Operating Voltage:3 V ~ 5.5 V Maximum Datarate: 120 kbps Operation: Full Duplex Protocol: RS232 Receiver Hysteresis: 300mV Temperature range: -40°C ~ 85°C Size: 10mm x 15mm'
	'DIY',
	3,
	'Paper Box 05',
	'ORGANIZED',
	'Mini_RS232_to_TTL_Converter_1.jpg;Mini_RS232_to_TTL_Converter_2.jpg',
	'MAX3222, MAX3232, MAX3237, MAX3241 - 3.0V to 5.5V, Low-Power, up to 1Mbps, True RS-232 Transceivers Using Four 0.1µF External Capacitors.pdf',
	''
)
(
	'DS18B20 - Sensor de temperatura TO92',
	'Sensor temperatura com resolução programável por 1 fio de 9~12 bits, tensão alimentação 3.0~5.5V, temperatura medida entre -55&deg;C até +125&deg;C, conversão 12 bits em 750ms (max), acuracia +-0.5&deg;C de temperaturas entre -10&deg; até +85&deg;C',
	'Integrated Circuit',
	10,
	'Paper Box 04',
	'ORGANIZED',
	'DS18B20.png;DS18B20_pins.png',
	'',
	''),
(
	'LM35DZ - Sensor de temperatura',
	'Sensor de temperatura para medidas entre -55&deg;C até 150&deg;C, com tensão de operação entre 4~30V, consumo de corrente menor que 60uA, fator linear 10mV/&deg;C.',
	'Integrated Circuit',
	1,
	'Paper Box 04',
	'ORGANIZED',
	'LM35DZ.jpg',
	'',
	''
),
(
	'Módulo de Sensor de Som',
	'Módulo de Sensor de Som com sensibilidade ajustada, com tensão de operação de 3.3V~5V, com saída digital on-off e saída analógica regulada por potenciômetro.',
	'DIY',
	1,
	'Paper Box 04',
	'ORGANIZED',
	'Modulo de Sensor de Som.jpg',
	'',
	''
),
(
	'Sensor de chuva',
	'Sensor de chuva com saída analógica e digital.',
	'DIY',
	1,
	'Paper Box 04',
	'ORGANIZED',
	'Sensor de chuva.jpg',
	'',
	''
),
(
	'RFID-RC522 - Módulo Sensor de Cartão RFID',
	'Módulo Sensor de Cartão RFID-RC522 com corrente de trabalho de 13~26mA/3.3V. Suporta cartões Mifare1 S50, Mifare1 S70, Mifare Ultralight, Mifare Pro e Mifare Desfare.',
	'DIY',
	1,
	'Paper Box 04',
	'ORGANIZED',
	'Módulo Sensor de Cartão RFID.jpg',
	'',
	''
),
(
	'GY-521 (MPU6050) Módulo de 3 eixos de aceleração e giroscópio',
	'Módulo GY-521 de 3 eixos de aceleração/giroscópio 6DOF com chip MPU6050, alimentação 3~5V, comunicação I2C, conversor A/D de 16 bits, range do giroscópio de +- 250, 500, 1000 e 2000 degree/sec, range do acelerômetro de +- 2g, +-4g, +-8g e +-16g.',
	'DIY',
	1,
	'Paper Box 04',
	'ORGANIZED',
	'Módulo de 3 eixos de aceleração e giroscópio DOF MPU-6050.jpg',
	'',
	''
),
(
	'HC-SR04 - Módulo de sensor de ultrassônico',
	'Módulo de sensor de ultrassônico para medição de distância HC-SR04 com tensão de alimentação de 5V DC, corrente de operação de 2mA, alcance de 2cm~4m e precisão de 3mm.',
	'DIY',
	1,
	'Paper Box 04',
	'ORGANIZED',
	'Módulo de sensor de ultrassônico HC-SR04.jpg',
	'',
	''
),
(
	'XD-58C - Módulo de frequência cardíaca',
	'Módulo de frequência cardíaca XD-58C com tensão de trabalho de 3~5V de material FR4 da marca KEYES.',
	'DIY',
	1,
	'Paper Box 04',
	'ORGANIZED',
	'Módulo de frequência cardíaca XD-58C.jpg',
	'',
	''
),
(
	'ACS712-20A - Módulo de Sensor de Corrente até 20A',
	'Módulo ACS712 20A de Sensor Corrente de 20A com tempo resposta de 5us, largura banda de 80kHz, margem erro de 1.5% a 25°C, resistência interna de 0.0012Ohms, tensão isolação de 2.1kVrms, tensão alimentação de 4.5~5.5V e sensibilidade de 100mV/A.',
	'DIY',
	1,
	'Paper Box 04',
	'ORGANIZED',
	'Módulo de Sensor de Corrente até 20A ACS712 20A.jpg',
	'',
	''
),
(
	'MQ-3 - Sensor Álcool Etanol',
	'Sensor Álcool Etanol MQ-3 com tensão de alimentação de 5V e saídas analógica e digital.',
	'DIY',
	1,
	'Paper Box 04',
	'ORGANIZED',
	'Sensor Álcool Etanol MQ-3.jpg',
	'',
	''
),
(
	'HC-SR501 - Sensor Infravermelho de movimento',
	'Sensor HC-SR501 de Infravermelho de movimento ROBOX RTHW com consumo em standby de 50uA, distancia máxima de detecção de 7m, ângulo  de máximo de detecção de 110° e tensão de alimentação de 4.5~20V.',
	'DIY',
	1,
	'Paper Box 04',
	'ORGANIZED',
	'Sensor Infravermelho de movimento ROBOX IR HC-SR501.jpg',
	'',
	''
),
(
	'MQ-2 - Sensor de gás liquefeito de petróleo e natural',
	'Sensor MQ-2 com saída digital e analógica, sensível a gás liquefeito de petróleo, natural, de cidade e de poluição.',
	'DIY',
	1,
	'Paper Box 04',
	'ORGANIZED',
	'Sensor MQ-2 de gás liquefeito de petróleo e natural.png',
	'',
	''
),
(
	'BH1750FVI - Sensor Digital de Intensidade de Luz',
	'Chip BH1750FVI original da ROHM, tensão de alimentação de 3~5V, intevalo de iluminância de 0~65535 lux e conversor AD de 16 bits.',
	'DIY',
	1,
	'Paper Box 04',
	'ORGANIZED',
	'Sensor Digital de Intensidade de Luz BH1750FVI.jpg',
	'BH1750FVI - Digital 16 bit Serial Output Type Ambient Light Sensor IC.pdf',
	'TEST_BH1750.zip;BH1750-master.zip'
),
(
	'Módulo Bluetooth V2.0',
	'Tensão/corrente de trabalho de 3.3V/20~3mA, conectado 8mA, configuração default de 9600, N, 8, 1 e senha 1234.',
	'DIY',
	1,
	'Paper Box 04',
	'ORGANIZED',
	'Módulo Bluetooth V2.0 hc-05-HC-05-RF-Wireless1.jpg;Módulo Bluetooth V2.0 hc-05-HC-05-RF-Wireless2.jpg',
	'',
	''
),
(
	'MQ-7 - Sensor de Monóxido de Carbono',
	'Sensor MQ-7 com material SnO2 com a capacidade de detectar CO, trabalhando com tensão de 5V e saída digital e analógica.',
	'DIY',
	1,
	'Paper Box 04',
	'ORGANIZED',
	'Sensor MQ-7 de Monóxido de Carbono1.jpg;Sensor MQ-7 de Monóxido de Carbono2.jpg',
	'',
	''
),
(
	'Módulo Sensor Magnético de Efeito Hall',
	'Módulo Sensor Magnético de Efeito Hall para aplicações em trabalhos com campos magnéticos, velocidade e \"gap\" de indução. Tensão de alimentação de 5V.',
	'DIY',
	1,
	'Paper Box 04',
	'ORGANIZED',
	'Módulo Sensor Magnético de Efeito Hall (a3144eul).jpg',
	'',
	''
),
(
	'SW-520D - Módulo de Sensor de Ângulo',
	'Módulo de Sensor de Ângulo com SW-520D, tensão de alimentação de 3.3~12VDC, saída 0 (LED verde ligado) e 1 (LED verde desligado).',
	'DIY',
	1,
	'Paper Box 04',
	'ORGANIZED',
	'Modulo de Sensor de Angulo (SW520).jpg',
	'',
	''
),

/* name, description, category, quantity, locationBox, status, locationImage, locationDatasheet, locationAttachment */
/* status, locationAttachment, locationDatasheet, locationBox, locationImage, quantity, types, description, name */

(
	'Módulo Bússola GY-273 (HMC5883L).jpg',
	1,
	'DIY',
	'Módulo Bússola GY-273 com chip HMC5883L, tensão de alimentação de 3~5V, comunicação I2C, faixa de medição +-1.3~8 Gaus.',
	'GY-273 (HMC5883L) - Módulo Bússola',
),
(
	'Modulo Sensor Gestos e RGB.jpg',
	1,
	'DIY',
	'Sensor de Gestos e Luz Ambiente de alimentação de 3.3V.',
	'Módulo Sensor Gestos e RGB',
),
(
	'Modulo Digital Sensor Aceleracao ADXL345.jpg',
	1,
	'DIY',
	'Módulo Digital Sensor Aceleração ADXL345 de 3-eixos de +-2g, +-4g, +-8g, +-16g, com resolução fixada de 10 bits. Tensão de alimentação de 5V/3.3V',
	'ADXL345 - Módulo Digital Sensor Aceleração',
),
(
	'Modulo Sensor Touch TTP223B (Touch Sensor Capacitive).jpg',
	1,
	'DIY',
	'Módulo Sensor Touch TTP223B com tensão de operação de 2~5.5V, saída de estado alto/baixo de 0.8V/0.3V, tempo de resposta de 220ms (estado baixo) e 60ms (estado alto)',
	'TTP223B - Módulo Sensor Touch',
),
(
	'Adafruit_Python_BMP-master.zip;Adafruit-BMP085-Library-master.zip;Adafruit_Python_GPIO-master.zip;BMP280_driver-master.zip',
	'BMP085 - Digital pressure sensor.pdf',
	'Módulo Digital Sensor de Pressão Barométrica e Temperatura do Ar BOSCH BMP085.jpg',
	1,
	'DIY',
	'Intervalo pressão barométrica 300~1100hPa (elevação 9000~500m), tensão alimentação 1.8~3.6V (VDDA), 1.62~3.6V (VDDD), consumo modo padrão 5uA, acurácia alta c/ resolução 0.06hPa (0.5m), no modo linear, resolução é 0.03hPa (0.25m).',
	'BMP085 - Módulo Digital Sensor de Pressão Barométrica e Temperatura do Ar BOSCH',
),
(
	'Módulo de Sensor de toque de corpo humano.jpg',
	1,
	'DIY',
	'Tensão de alimentação de 5VDC e uso do circuito LM393, saída analógica e digital.',
	'Módulo de Sensor de toque de corpo humano',
),
(
	'Módulo Bluetooth AT-09.jpg',
	1,
	'DIY',
	'Módulo Bluetooth 4.0 para Arduino com serial BLE CC2540 CC2541 iBeacon.',
	'AT-09 - Módulo Bluetooth',
),
(
	'Sensor UVM-30A de Detecção de Raios Ultravioleta.jpg',
	1,
	'DIY',
	'Sensor com 28mm/12mm/10mm, detecção raios ultravioletas, alimentação 3~5V, tensão saída 0~1VDC, precisão teste de +-1 UV INDEX, corrente funcionamento 0.06mA (typ) e 0.1mA (max), comprimento onda de resposta 200nm~370nm, estabilidade de -20º~85º',
	'UVM-30A - Sensor de Detecção de Raios Ultravioleta',
),
(
	'Sensor de detecção de radar HB100.jpg',
	1,
	'DIY',
	'Sensor microondas de efeito doppler com frequência de 10.525 GHz, alimentação de 5V +-0.25V, corrente de 40mA, dimensões 37mm (c), 45mm (l) e 8mm (a).',
	'HB100 - Sensor de detecção de radar',
),
(
	'Radar doppler RCWL-0516.jpg',
	1,
	'DIY',
	'Radar doppler RCWL-0516 para sensor de movimento para detecção de longa distância e com capacidade de penetração. Tensão de alimentação 4~28VDC e saída de 3.3V',
	'RCWL-0516 - Radar doppler',
),
(
	'MPU9250-master.zip',
	'PS-MPU-9250A-01.pdf;RM-MPU-9250A-00.pdf',
	'GY-9250(MPU-9250)-9-axis_1.jpg;GY-9250(MPU-9250)-9-axis_2.jpg;GY-9250(MPU-9250)-9-axis_3.jpg;GY-9250(MPU-9250)-9-axis_4.jpg;GY-9250(MPU-9250)-9-axis_5.jpg',
	1,
	'DIY',
	'O módulo MPU-9250 tem 9-eixos: 3 do giroscópio (escalas de ±250, ±500, ±1000, e ±2000°/sec), 3 do acelerômetro (escalas de ±2g, ±4g, ±8g e ±16g) e 3 do magnetômetro (resolução de saída de 14 bit (0.6µT/LSB) e escala completa de±4800µT)',
	'GY-9250 (MPU-9250) Módulo de 9 eixos de aceleração, giroscópio e magnetômetro',
),
(
	'Sensor Capacitivo.jpg',
	1,
	'DIY',
	'Sensor Capacitivo com distância de detecção de 0-15mm com saídas NPN/NO+NC e tensão de alimentação 6~36VDC.',
	'CM30-3015-NC - Sensor Capacitivo',
),
(
	'Sensor Indutivo de Proximidade PR12-2DP1.jpg;Sensor Indutivo de Proximidade PR12-2DP2.png',
	1,
	'DIY',
	'Sensor Indutivo de Proximidade PR12-2DP com distância de detecção de 0-2mm, frequência de resposta de 1.5kHz e tensão de alimentação de 12-24VDC.',
	'PR12-2DP - Sensor Indutivo de Proximidade',
),
(
	'Contador de Fluxo de água - YF-S201.jpg',
	1,
	'DIY',
	'YF-S201 - Contador de Fluxo de Água usando sensor de efeito Hall. Pressão < 1.75MPa, tensão de 5~24V, acurácia = 1~60L/Min +-3%, caracteristica do pulso do fluxo = 4.8xQ, onde Q é L/Min.',
	'YF-S201 - Contador de Fluxo de água',
),
(
	'Modulo ISD1820, para gravação de voz.jpg',
	1,
	'DIY',
	'Modulo ISD1820, para gravação de voz com microfone onboard e gravação de 10s de voz. É composto de três botões (REC,PLAYE e PLAYL), microfone e alto falante.',
	'ISD1820 - Módulo para gravação de voz',
),
(
	'Sensor de Temperatura e Umidade DHT21-AM2301_1.jpg;Sensor de Temperatura e Umidade DHT21-AM2301_2.jpg;Sensor de Temperatura e Umidade DHT21-AM2301_3.jpg',
	1,
	'DIY',
	'Sensor de Temperatura e Umidade DHT21/AM2301 com tensão de alimentação de 3~5V, umidade de 0~100%, temperatura de -40~80°C, precisão de +-3%RH/+-0.5°C com saída digital \"monobus\".',
	'DHT21/AM2301 - Sensor de Temperatura e Umidade',
),
(
	'Motor DC com caixa de redução e eixo duplo-1.jpg;Motor DC com caixa de redução e eixo duplo-2.jpg;Motor DC com caixa de redução e eixo duplo-3.jpg',
	1,
	'DIY',
	'Motor DC de 3~6V com caixa de redução (1:48) e eixo duplo. Peso de 30g, corrente sem carga <= 200mA (6V) e <= 150mA (3V) e velocidade sem carga de 200RPM (6V) e 90RPM (3V).',
	'Motor DC com caixa de redução e eixo duplo',
),
(
	'Sensor de Corrente não Invasivo 100A SCT013-000.jpg',
	1,
	'DIY',
	'Medição corrente 0~100A, corrente saída 0~50mA, acurácia ±1%, linearidade ±3%, razão espiras 1:1800, deslocamento fase ≤180º, material núcleo ferrite e frequência trabalho 50~1000Hz.',
	'SCT013-000 - Sensor de Corrente não Invasivo 100A',
),
(
	'ELM327 OBD2 - Interface de diagnóstico.jpg',
	1,
	'Equipamento',
	'Interface de diagnóstico ELM327 OBD2 versão 2.1 de conexão bluetooth.',
	'ELM327 OBD2 - Interface de diagnóstico',
),
(
	'E18-D80NK Long range adjustable IR sensor.pdf;Wiring the E18-D80NK Infrared Distance Ranging Sensor.pdf',
	'E18-D80NK - Sensor de Proximidade_1.jpg;E18-D80NK - Sensor de Proximidade_2.jpg;E18-D80NK - Sensor de Proximidade_3.jpg;E18-D80NK - Sensor de Proximidade_4.jpg;E18-D80NK - Sensor de Proximidade_5.jpg;E18-D80NK - Sensor de Proximidade_6.jpg',
	1,
	'DIY',
	'Sensor normalmente aberto com faixa de detecção de 3~80 cm, alimentação de 5VDC, corrente de consumo < 25mA, diâmetro de 17 mm, comprimento do sensor de 45 mm, comprimento do cabo de 45 cm, tempo de resposta < 2 ms, ângulo maior que 15°.',
	'E18-D80NK - Sensor de Proximidade Fotoelétrico Infravermelho com faixa de detecção de 3~80 cm',
),
(
	'5KG resistance strain type pressure sensor.doc',
	'CX. PAPEL 04-B',
	'Load_Cell_Weight_Sensor_5kg_1.jpg;Load_Cell_Weight_Sensor_5kg_2.jpg',
	2,
	'DIY',
	'Potência nominal: 1,0±0.15mV/V; Impedância entrada/saída: 1115±10%/1000±10%Ω; Resistência isolamento: 1000MΩ; Sobrecarga seguro/extrema: 150%FS/200%FS; Alimentação:3~12VDC; IP65',
	'Célula de Carga de 5kg',
),
(
	'Sensor LSON Ultrason.jpeg',
	4,
	'DIY',
	'16mm ultrasonic; Water resistant; 40KHz sensor; Diameter: 16mm; Working mode: transceiver split; Transmitting sound pressure at 10V: >=110dB; Sensitivity: >=-75dB; Capacitance at 1KHz: 1800+/-30%',
	'Sensor LSON Ultrassônico 40KHz',
)