INSERT INTO components( name, description, category, quantity, locationBox, status, locationImage, locationDatasheet, locationAttachment ) VALUES
(
	'Capacitor Eletrolítico SNAP-IN 100uF/400V',
	'Capacitor Eletrolítico SNAP-IN 100uF por 400V com 22mm de diametro e 30mm de altura.',
	'Capacitor',
	1,
	'',
	'NOT ORGANIZED',
	'Capacitor eletrolitico snap-in.jpg',
	'',
	''
),
(
	'Capacitor Eletrolítico Snap-in 47uF/400V',
	'Capacitor G-LUXON Eletrolítico Snap-in 47UF por 400V e TW85&deg;. Di&acirc;metro de 22mm e altura de 20mm.',
	'Capacitor',
	1,
	'',
	'NOT ORGANIZED',
	'Capacitor eletrolitico snap-in.jpg',
	'',
	''
),
(
	'Capacitor Huang Eletrolítico 33uF/400V',
	'Capacitor Huang Eletrolítico 33UF por 400V.Di&acirc;metro de 16mm e altura de 22mm. Temperatura de -40&deg;C até 105&deg;C.',
	'Capacitor',
	1,
	'',
	'NOT ORGANIZED',
	'Capacitor Eletrolítico 33UF-400V - 105.jpg',
	'',
	''
),
(
	'Capacitor trimmer 20pF',
	'Capacitor trimmer 20pF na cor vermelha e com 2 terminais.',
	'Capacitor',
	3,
	'',
	'NOT ORGANIZED',
	'Capacitor trimmer 20pF vermelho 2 terminais.jpg;Capacitor trimmer 2 terminais.png',
	'',
	''
),
(
	'Capacitor trimmer 5pF',
	'Capacitor trimmer 5pF na cor azul e com 2 terminais.',
	'Capacitor',
	1,
	'',
	'NOT ORGANIZED',
	'Capacitor trimmer 5pF azul 2 terminais.jpg;Capacitor trimmer 2 terminais.png',
	'',
	''
),
(
	'Capacitor trimmer 30pF',
	'Capacitor trimmer 30pF na cor verde e com 2 terminais.',
	'Integrated Circuit',
	1,
	'',
	'NOT ORGANIZED',
	'Capacitor trimmer 30pF verde 2 terminais.jpg;Capacitor trimmer 2 terminais.png',
	'',
	''
),
(
	'MOC3020 - Acoplador Óptico',
	'Acoplador Óptico que também é isolador. Driver Fototriac para saída 250V. Driver de saída projetado para 220V AC.',
	'Circuito',
	7,
	'',
	'NOT ORGANIZED',
	'MOC3020.jpg',
	'',
	''
),
(
	'PIC18F4550 - Microcontrolador',
	'Microcontrolador com USB 2.0, 13 canais A/D de 10 bits, 24k bytes de Flash, SRAM de 2048 bytes, 256 bytes de EEPROM, 35 I/O, SPP, SPI, I2C, EUSART, timers de 8 (1) e 16 (3) bits.',
	'Integrated Circuit',
	1,
	'',
	'NOT ORGANIZED',
	'PIC18F4550.jpg',
	'',
	''
),
(
	'AT28C256 - Memória EEPROM',
	'Memória EEPROM AT28C256 de 256K bits (32k x 8).',
	'Integrated Circuit',
	1,
	'',
	'NOT ORGANIZED',
	'AT28C256-20PC.jpg',
	'',
	''
),
(
	'AT28C64 - Memória EEPROM',
	'Memória EEPROM AT28C64 de 64K bits (8k x 8).',
	'Integrated Circuit',
	2,
	'',
	'NOT ORGANIZED',
	'AT28C64.jpg',
	''
	''
),
(
	'PIC16F84A - Microcontrolador',
	'Microcontrolador de 8 bit, com apenas 35 instruções, 1024 palavras de memória de programa, 68 bytes RAM, 64 bytes EEPROM.',
	'Integrated Circuit',
	5,
	'',
	'NOT ORGANIZED',
	'PIC16F84A.jpg',
	'',
	''
),
(
	'dsPIC4013 - Microcontrolador',
	'Microcontrolador alta performance de 16 bits para controle de sinal digital, 48k+16k bytes de memória de programa, 2048 bytes SRAM, 1024 bytes EEPROM, 5 timers 16 bits, 4 PWM, interface codec AC 97 e I2S, 13 canais A/D 12 bits, 2 UART, 1 SPI/I2C/CAN',
	'Integrated Circuit',
	1,
	'',
	'NOT ORGANIZED',
	'dsPIC30F4013.png',
	'',
	''
),
(
	'PIC16F628A - Microcontrolador',
	'Microcontrolador de 8 bit, com apenas 35 instruções, 2048 palavras de memória de programa, 224 bytes RAM, 128 bytes EEPROM, 2 comparadores, timer de 8/16 bits, PWM de 10 bits e USART.',
	'Integrated Circuit',
	3,
	'',
	'NOT ORGANIZED',
	'PIC16F628A.jpg',
	'',
	''
),
(
	'80C51 - Microcontrolador',
	'Microcontrolador 80C51 de chip CHMOS de 8 bit, com 128 x 8 bit de RAM, 32 linhas de programação I/O, 2 timers/contadores, processador boleano, ...',
	'Integrated Circuit',
	1,
	'',
	'NOT ORGANIZED',
	'80C51.jpg',
	'',
	''
),
(
	'PIC12F675 - Microcontrolador',
	'Microcontrolador 8 pinos em 8 bits com 6 pinos I/O, 1 comparador analógico, 1024 palavras de memória de programa, 64 bytes SRAM, 128 bytes EEPROM, 6 I/O, 4 canais I/O de 10 bits e um timer de 8 bits e outro de 16 bits.',
	'Integrated Circuit',
	1,
	'',
	'NOT ORGANIZED',
	'PIC12F675.jpg',
	'',
	''
),
(
	'AT24C04 - Memória EEPROM',
	'Memória EEPROM com interface serial I2C. Outro nome pode ser ATMLU018. Memória de tamanho de 16K (512 x 8) bytes.',
	'Integrated Circuit',
	1,
	'',
	'NOT ORGANIZED',
	'AT24C04-DIP-8-Serial EEPROM (ATMLU018).jpg',
	'',
	''
),
(
	'6N138 - Acoplador Óptico',
	'Acoplador óptico de alta velocidade, 100kBd, corrente de entrada baixa e saída de fotodiodo acoplador com aplicações em interface de sistemas de microprocessamento, recepção de linha RS232, tradução de tensão TTL e CMOS, entre outras.',
	'Integrated Circuit',
	12,
	'',
	'NOT ORGANIZED',
	'6N138.jpg',
	'',
	''
),
(
	'TLP521 - Acoplador Óptico',
	'Acoplador óptico com um fototransistor dimensões 6.4+-0.25 x 4.58+-0.25 mm com 0.26g.',
	'Integrated Circuit',
	1,
	'',
	'NOT ORGANIZED',
	'TLP521 - Acoplador Optico.jpg',
	'',
	''
),
(
	'EL817 - Acoplador Óptico',
	'Acoplador óptico com VCE=5V e IF=5mA.',
	'Integrated Circuit',
	4,
	'',
	'NOT ORGANIZED',
	'EL817.jpg',
	'',
	''
),
(
	'4N25 - Acoplador Óptico',
	'Acoplador óptico com fototransistor de saída e com conexão de base.',
	'Integrated Circuit',
	9,
	'',
	'NOT ORGANIZED',
	'4N25.jpg',
	'',
	''
),
(
	'NE555 - Timer',
	'Timer com baixo tempo de turn-off, máxima frequência de operação maior que 500kHz, tempo de microsegundos à horas, saída de até 200mA, entre outros.',
	'Integrated Circuit',
	4,
	'',
	'NOT ORGANIZED',
	'NE555.jpg',
	'',
	''
),
(
	'741 - Amplificador Operacional de Uso Geral',
	'Amplificador Operacional com proteção, ganho em torno de 200V/mV, resistência de entrada de 2 MOhms e resistência de saída de 75 Ohms.',
	'Integrated Circuit',
	6,
	'',
	'NOT ORGANIZED',
	'741-op-amp.png',
	'',
	''
),
(
	'LM358 - Dual amplificador operacional de baixa potência',
	'Dual amplificador operacional de baixa potência com grande ganho de tensão DC de 100dB, larga largura de banda (ganho unitário) de 1MHz com tensão de alimentação variando entre 3V~32V.',
	'Integrated Circuit',
	1,
	'',
	'NOT ORGANIZED',
	'LM358.jpg',
	'',
	''
),
(
	'MT8870DE - Receptor integrado de DTMF',
	'Receptor integrado de DTMF com modo de baixa potência, inibidor, aplicações em sistemas de cartão de crédito, controle remoto, entre outros.',
	'Integrated Circuit',
	1,
	'',
	'NOT ORGANIZED',
	'MT8870.jpg',
	'',
	''
),
(
	'MAX232N/ST232BN - Driver e Receiver EIA-232',
	'Driver e Receiver EIA-232, com operação acima até 120kbits/s, com dois drivers e dois receptores e tensão de alimentação +-30V.',
	'Integrated Circuit',
	3,
	'',
	'NOT ORGANIZED',
	'MAX232N.jpg;ST232.jpg',
	'',
	''
),
(
	'LM324 - Quatro Amplificadores Operacional',
	'Quatro Amplificadores Operacional em um único chip, circuito de saída protegido, intervalo de alimentação de 3~32V, entre outras características.',
	'Integrated Circuit',
	1,
	'',
	'NOT ORGANIZED',
	'LM324.jpg',
	'',
	''
),
(
	'ADC0804LCN - Conversor A/D de 8Bit',
	'Conversor A/D de resolução de 8 bits com tempo de conversão de 100us. Tensão de alimentação de 5V com intervalo de tensão de entrada de 0~5V.',
	'Integrated Circuit',
	1,
	'',
	'NOT ORGANIZED',
	'ADC0804LCN.jpg',
	'',
	''
),
(
	'L293B - Drivers de quatro canais',
	'Drivers com quatro canais com corrente de saída de 1A por canal e 2A de pico, alta imunidade a ruídos e proteção contra sobre temperatura.',
	'Integrated Circuit',
	1,
	'',
	'NOT ORGANIZED',
	'L293D.jpg',
	'',
	''
),
(
	'ULN2003APG - Arranjo de 7 Darlington',
	'Arranjo de 7 Darlington de alta corrente, sinais 5V TTL e CMOS e 500mA por saída.',
	'Integrated Circuit',
	1,
	'',
	'NOT ORGANIZED',
	'ULN2803.jpg;ULN2003APG.jpg',
	'',
	''
),
(
	'74HC595 - conversor de serial para paralelo',
	'Conversor com registrador de deslocamento de 8 bits com registradores de saída com 3 estados, alimentação de 2~6V, e aplicações em switches de rede, dislpay de LEDs e servidores.',
	'Integrated Circuit',
	8,
	'',
	'NOT ORGANIZED',
	'SN74HC595.jpg',
	'',
	''
),
(
	'4019 - Seletor de Porta AND/OR CMOS',
	'Seletor de Porta AND/OR CMOS com 4 destas, com aplicações em seleção de porta AND*OR, deslocamento para direita/esquerda de registradores, entre outros.',
	'Integrated Circuit',
	2,
	'',
	'NOT ORGANIZED',
	'CD4019.jpg',
	'',
	''
),
(
	'74HC238 - Decoder/Demultiplexador inverso e não-inverso',
	'Decoder/Demultiplexador inverso e não-inverso de alta velocidade com 8 bits, tensão de 2~6V e tensão nominal de 3.3V e 5V.',
	'Integrated Circuit',
	3,
	'',
	'NOT ORGANIZED',
	'74HC238.jpg;CD74HC238.jpg',
	'',
	''
),
(
	'4511 - Driver decodificador BCD para display de 7 segmentos',
	'Driver decodificador BCD para display de 7 segmentos com aplicações em display de LED de catodo comum, catodo comum multiplexado, incandescente ou de fluorescente de baixa tensão.',
	'Integrated Circuit',
	4,
	'',
	'NOT ORGANIZED',
	'CD4511.jpg',
	'',
	''
),
(
	'74LS245 - Transceptor de Barramento Octal com 3 estados de saída',
	'Transceptor de Barramento Octal com 3 estados de saída, com aplicações em construção de automação, controle e automação de fabricas e testes e medidas.',
	'Integrated Circuit',
	4,
	'',
	'NOT ORGANIZED',
	'SN74LS245.jpg',
	'',
	''
),
(
	'4011 - Quatro portas NAND',
	'Quatro portas NAND com duas entradas por porta.',
	'Integrated Circuit',
	2,
	'',
	'NOT ORGANIZED',
	'CD4011.jpg',
	'',
	''
),
(
	'4001 - Quatro portas NOR',
	'Quatro portas NOR com duas entradas por porta.',
	'Integrated Circuit',
	2,
	'',
	'NOT ORGANIZED',
	'CD4001.jpg',
	'',
	''
),
(
	'74HC32 - Quatro portas OR',
	'Quatro portas OR com duas entradas por porta.',
	'Integrated Circuit',
	2,
	'',
	'NOT ORGANIZED',
	'SN74HC32.jpg',
	'',
	''
),
(
	'74HC00 - Quatro portas NAND',
	'Quatro portas NAND com duas entradas por porta.',
	'Integrated Circuit',
	2,
	'',
	'NOT ORGANIZED',
	'SN74HC00N.jpg',
	'',
	''
),
(
	'74HC08 - Quatro portas AND',
	'Quatro portas AND com duas entradas por porta.',
	'Integrated Circuit',
	2,
	'',
	'NOT ORGANIZED',
	'SN74HC08N.jpg',
	'',
	''
),
(
	'74HC04 - Seis portas inversoras',
	'Seis portas inversoras, isto é, seis portas NOT.',
	'Integrated Circuit',
	2,
	'',
	'NOT ORGANIZED',
	'SN74HC04N.jpg',
	'',
	''
),
(
	'4071 - Quatro portas OR',
	'Quatro portas OR com duas entradas por porta.',
	'Integrated Circuit',
	2,
	'',
	'NOT ORGANIZED',
	'HEF4071.jpg',
	'',
	''
),
(
	'ATMEGA328P-PU - Microcontrolador',
	'Microcontrolador CMOS 8-bit de 131 instruções, RISC, 32 registradores trabalho uso geral 8-bit, 32KBytes memória flash, 1KBytes EEPROM, 2KBytes SRAM, 2 timer/contador 8-bit, 1 timer/contador 16-bit, 6 canais PWM, 8 canais A/D 10-bit, entre outros.',
	'Integrated Circuit',
	10,
	'',
	'NOT ORGANIZED',
	'ATMEGA328P-PU.jpg',
	'',
	''
),
(
	'LM567CN - Decodificador de Tom',
	'Decodificador de tom de frequência central ajustável de 0.01Hz até 500kHz, com saída lógica de até 100mA, com aplicações em decodificação de toque de tom, oscilador de precisão, controle ultrassônico, entre outros.',
	'Integrated Circuit',
	2,
	'',
	'NOT ORGANIZED',
	'LM567-NE567-tone-decoder.jpg',
	'',
	''
),
(
	'INA118 - Amplificador de instrumentação',
	'Amplificador de instrumentação INA118, de baixa potência e alta precisão, com ganho de 1 até 10000. Alimentação de +-1.35~+-18V.',
	'Integrated Circuit',
	1,
	'',
	'NOT ORGANIZED',
	'INA118-INA118P-DIP8.jpg',
	'',
	''
),
(
	'Alicate Compressão TALON TL-H518A',
	'Cripador TALON TL-H518A para cabos coaxial RG59 e RG6 com conector F.',
	'Tool',
	1,
	'',
	'NOT ORGANIZED',
	'Alicate Compressão TALON TL-H518A.jpg',
	'',
	''
),
(
	'Alicate Decapador de Cabo Coaxial',
	'Descascador de fios e cabo coaxial de 4, 6, 8 e 12mm, podendo descascar fios RG58 e RG59.',
	'Tool',
	1,
	'',
	'NOT ORGANIZED',
	'Alicate Decapador de Cabo Coaxial.jpg',
	'',
	''
),
(
	'Display Matriz de LED Vermelho',
	'Display Matriz HS-757-BS Anodo Comum Vermelho, 13x18mm.',
	'LED',
	1,
	'',
	'NOT ORGANIZED',
	'Display Matriz HS-757-BS Anodo Comum Vermelho.png;LED Dot Matrix Display 5x7 1.9mm Red Common Anode-Common Cathode  757AS-757BS.jpg',
	'',
	''
),
(
	'Mini Quadricoptero JINXINGDA JD-385',
	'Marca: JINXINGDA; Modelo: JD-385; Material: ABS + liga de alumínio; Canal: 4 Canais; Especificação Canal: back/forward/backward/upward/downward/left/right/3D; Giroscópio: Sim; Frequência Controle Remoto: 2.4GHz; Faixa de controle remoto: 60~80 metros; Capacidade da bateria: 240 mAh; Tipo de Bateria: Polímero íon de lítio; Tempo de carregamento: 30 minutos; Tempo de Trabalho: 8~10 minutos',
	'Other',
	1,
	'',
	'NOT ORGANIZED',
	'JINXINGDA JD-385_1.jpg;JINXINGDA JD-385_2.jpg;JINXINGDA JD-385_3.jpg;JINXINGDA JD-385_4.jpg;JINXINGDA JD-385_5.jpg;JINXINGDA JD-385_6.jpg;JINXINGDA JD-385_7.jpg',
	'',
	''
),
(
	'Tv Portátil LCD Midi Japan Md-7550',
	'Tv Portátil TFT-LCD Midi MD-7550, 7 polegadas, colorida, analógica e resolução de 640 x 480 pixel.',
	'Other',
	1,
	'',
	'NOT ORGANIZED',
	'TV MIDI MD-7550.png',
	'',
	''
),
(
	'Scanner 1D Scanworld-918',
	'Material: Case Plástico; Interface: USB; Tipo: Pistola scanner de código de barras; Uso: Identifificar código de barra 1D; Marca: Barcode Scanner ; Modelo: Scanworld-918',
	'Other',
	1,
	'',
	'NOT ORGANIZED',
	'Scanner 1D Scanworld-918.png',
	'',
	''
),
(
	'Conversor Analógico para Digital (ADC) de 24-Bit HX711 para balanças',
	'Módule Amplificador HX711 para leitura de massa em células de carga. Conexões: fio vermelho para E+, fio preto para E-, fio verde para A+ e fio branco para A-. Alimentação: 2.6~5.5V; Consumo de corrente: operação normal < 1.5mA, desligado < 1uA.',
	'DIY',
	1,
	'',
	'NOT ORGANIZED',	'Load_Cell_Amplifier_HX711_1.jpg;Load_Cell_Amplifier_HX711_2.jpg;Load_Cell_Amplifier_HX711_3.jpg;Load_Cell_Amplifier_HX711_4.jpg;Load_Cell_Weight_Sensor_1kg_3.jpg',
	'HX711 - 24-Bit Analog-to-Digital Converter (ADC) for Weigh Scales.pdf',
	''
),
(
	'PIC16F688 - Microcontrolador',
	'Microcontrolador de 8 bit, com 35 instruções, 4096 palavras de mem. de programa, 256 bytes SRAM, 256 bytes EEPROM, 12 pinos I/O, módulo comparador analógico, conversor A/D resolução 10 bits e 8 canais, módulo USART (RS-485/RS-232/LIN) 1.2 e ICSP.',
	'Integrated Circuit',
	1,
	'',
	'NOT ORGANIZED',
	'microcontrolador_PIC16F688.jpg',
	'PIC16F688.pdf',
	''
),
(
	'MCP2551 - CAN Transceiver',
	'Transceiver para comunicação entre TTL e CAN e permitindo comunicações até 112 nós.',
	'Integrated Circuit',
	2,
	'',
	'NOT ORGANIZED',
	'MCP2551.jpg',
	'AN228 - A CAN Physical Layer Discussion.pdf;AN713 - An introduction to the CAN protocol that discusses the basics and key features.pdf;MCP2551- High-Speed CAN Transceiver.pdf;TB3101 - MCP2551 to MCP2561 Migration.pdf',
	''
),
(
	'6N139 - Acoplador Óptico',
	'Acoplador óptico de alta velocidade, 100kBd, corrente de entrada baixa e saída de fotodiodo acoplador com aplicações em interface de sistemas de microprocessamento, recepção de linha RS232, tradução de tensão TTL e CMOS, entre outras.',
	'Integrated Circuit',
	8,
	'',
	'NOT ORGANIZED',
	'6N139.jpg',
	'6N138, 6N139.pdf',
	''
),
(
	'IR2104 - Driver Meia-Ponte',
	'VOFFSET: 600V max.; IO+/-: 130 mA / 270 mA; ton/off (typ.): 680 & 150 ns; Deadtime (typ.): 520 ns; Gate drive supply (VOUT) range from 10 to 20V; 3.3V, 5V and 15V input logic compatible',
	'Integrated Circuit',
	1,
	'',
	'NOT ORGANIZED',
	'IR2104_1.jpg;IR2104_2.jpg',
	'IR2104 - Half-Bridge Driver.pdf',
	''
),
(
	'LF351 - Amplificador Operacional com estágio de entrada com JFET',
	'Internally adjustable input offset voltage; Low input bias and offset current; Output short-circuit protection; High input impedance JFET input stage; Internal frequency compensation; Latch up free operation; High slew rate 16 V/µs (typical)',
	'Integrated Circuit',
	1,
	'',
	'NOT ORGANIZED',
	'LF351N-LF351-OPAMP-JFET-4MHZ-8DIP_1.jpg;LF351N-LF351-OPAMP-JFET-4MHZ-8DIP_2.jpg',
	'LF351 - Wide bandwidth single JFET operational amplifiers.pdf',
	''
),
(
	'LM3900 - Amplificador Operacional',
	'VCC (single)/VCC+ (dual)/VCC– (dual): 4.5~32 V/2.2~16 V/–2.2~–16 V; AVD - Large-signal differential voltage amplification (VO=10 V, f=100 Hz, RL=10 kΩ) MIN/TYP: 1.2/2.8 V/mV; resistance ri - Input (inverting input)/ro - Output: 1 MΩ/8 kΩ',
	'Integrated Circuit',
	1,
	'',
	'NOT ORGANIZED',
	'LM3900.jpg',
	'LM3900 - Quadruple Norton Operational Amplifiers.pdf',
	''
),
(
	'ADC0832 - Conversor Serial A/D de 8Bit Multiplexado',
	'No Zero or Full-Scale Adjust Required; 2-Channel Multiplexer Options with Address Logic; 0V to 5V Input Range with Single 5V Power Supply; Resolution: 8 Bits; Total Unadjusted Error: ±1/2 LSB and ±1 LSB; Low Power: 15 mW; Conversion Time: 32 μs',
	'Integrated Circuit',
	1,
	'',
	'NOT ORGANIZED',
	'ADC0832_1.jpg;ADC0832_2.jpg',
	'ADC0831-N, ADC0832-N, ADC0834-N, ADC0838-N - 8-Bit Serial I-O A-D Converters with Multiplexer Options.pdf',
	''
),
(
	'TBA820M - Amplificador de Audio de 1.2W',
	'Supply voltage (Vs): 3~16 V; Output peak current (Io): 1.5 A; Power dissipation at Tamb=50°C (Ptot): 1 W; Input resistance [pin 3] f=1 kHz (Ri): 5 MΩ',
	'Integrated Circuit',
	1,
	'',
	'NOT ORGANIZED',
	'TBA820M.jpg',
	'TBA820M - 1.2W Audio Amplifier.pdf',
	''
),
(
	'ULN2803A - Array de Transistores Darlington',
	'500 mA - Rated Collector Current (Single Output); High-Voltage Outputs: 50 V; Output Clamp Diodes; Inputs Compatible With Various Types of Logic',
	'Integrated Circuit',
	1,
	'',
	'NOT ORGANIZED',
	'ULN2803_1.jpg;ULN2803_2.jpg',
	'ULN2803A - Darlington Transistor Arrays.pdf',
	''
),
(
	'4070 - Quatro portas OR Exclusivo (XOR)',
	'Quatro portas OR Exclusivo com duas entradas por porta.',
	'Integrated Circuit',
	3,
	'',
	'NOT ORGANIZED',
	'HCF4070BE.png',
	'HCF4070.pdf;HCF4070B.pdf',
	''
),
(
	'TL072CP - Amplificador Operacional com entrada JFET e baixo ruído',
	'Baixo consumo de alimentação; Proteção de saída de curto-circuito; Baixa distorção total harmônica: 0.003% (Típico); Alta Impedância de entrada (estágio de entrada JFET); Alto taxa de Slew: 13 V/μs (Típico)',
	'Integrated Circuit',
	2,
	'',
	'NOT ORGANIZED',
	'TL072.jpg',
	'TL07xx Low-Noise JFET-Input Operational Amplifiers.pdf',
	''
),
(
	'TL071CP - Amplificador Operacional com entrada JFET e baixo ruído',
	'Baixo consumo de alimentação; Proteção de saída de curto-circuito; Baixa distorção total harmônica: 0.003% (Típico); Alta Impedância de entrada (estágio de entrada JFET); Alto taxa de Slew: 13 V/μs (Típico); Pinos de offset',
	'Integrated Circuit',
	2,
	'',
	'NOT ORGANIZED',
	'TL071.jpg',
	'TL07xx Low-Noise JFET-Input Operational Amplifiers.pdf',
	'',
	''
),
(
	'H11AA1 - Optoacoplador com entrada AC  e Fototransistor de saída com conexão de base',
	'Entrada AC ou entrada com duas polaridades; I/O compatível com circuitos integrados; Teste de tensão de isolação: 5300 VRMS',
	'Integrated Circuit',
	1,
	'',
	'NOT ORGANIZED',
	'H11AA1_1.jpg;H11AA1_2.jpg',
	'H11AA1 - Optocoupler, Phototransistor Output, AC Input, with Base Connection.pdf',
	''
),
(
	'OPA544 - Amplificador Operacional de média potência',
	'Wide Power Supply Range: ±10V ~ ± 35V; Output Current: 4A (Typ); GBW: 1.4MHz (Typ); Slew Rate: 8V/us (Typ); Vos (Offset Voltage@25C): 5mV (Max); Offset Drift: 10uV/C (Typ); Iq per channel: 12mA (Typ); Input Bias Current: 100pA (Max); CMRR: 106dB (Typ)',
	'Integrated Circuit',
	1,
	'',
	'NOT ORGANIZED',
	'OPA544.jpg',
	'OPA544 - High-Voltage, High-Current Operational Amplifier.pdf',
	''
),
(
	'Nextion HMI NX3224T024',
	'NX3224T024 tem 65K (65536) cores (16 bit - 5R6G5B), resolução de 320×240 pixels (também pode configurar 240×320 pixels), sensor resistivo, luz de fundo, suporte a cartão SD, e comunicação serial.',
	'DIY',
	1,
	'',
	'NOT ORGANIZED',	'NX3224T024_1.jpg;NX3224T024_2.jpg;NX3224T024_3.jpg;NX3224T024_4.jpg;NX3224T024_5.jpg;NX3224T024_6.jpg;NX3224T024_7.jpg;NX3224T024_8.jpg;NX3224T024_9.jpg;NX3224T024_10.jpg;NX3224T024_11.jpg;NX3224T024_12.jpg',
	'NX3224T024 - ITEAD Wiki.pdf',
	''
),
(
	'TDA7439 - Processador de áudio controlado digitalmente',
	'Processador de áudio controlado digitalmente de três bandas, entrada multiplexada, entre outras.',
	'Integrated Circuit',
	1,
	'',
	'NOT ORGANIZED',
	'TDA7439_1.jpg;TDA7439_2.jpg',
	'TDA7439 - Three-band digitally-controlled audio processor.pdf',
	''
),
(
	'LM311 - Comparador diferencial',
	'Tempo de resposta rápida: 165 ns; Corrente máxma de bias de entrada: 300 nA; Corrente máxida de offset de entrada: 70 nA; Pode ser operado com simples fonte 5 V',
	'Integrated Circuit',
	2,
	'',
	'NOT ORGANIZED',
	'LM311.jpg',
	'LM111, LM211, LM311 Differential Comparators.pdf',
	''
),
(
	'LM339 - 4 Comparadores diferencial',
	'Wide Supply Ranges; Single Supply: 2 V to 36 V; Dual Supplies: ±1 V to ±18 V; Low Supply-Current Drain Independent of Supply Voltage: 0.8 mA (Typ); Low Input Bias Current: 25 nA (Typ); Low Input Offset Voltage: 2 mV (Typ)',
	'Integrated Circuit',
	1,
	'',
	'NOT ORGANIZED',
	'LM339.jpg',
	'LM339, LM239, LM139, LM2901 Quad Differential Comparators.pdf',
	''
),
(
	'Módulo Serial I2C para Display LCD',
	'Módulo Serial I2C para Display LCD para conexão de display ao Arduino usando o chip PCF8574',
	'DIY',
	1,
	'Box 000',
	'NOT ORGANIZED',
	'Serial LCD I2C Module with chip PCF8574;Figure 1.jpg;Figure 2.jpg;Figure 3.jpg;Figure 4.jpg',
	'Serial LCD I2C Module with chip PCF8574;Schemas.pdf',
	'Serial LCD I2C Module with chip PCF8574;New LiquidCrystal _ wiki _ Home — Bitbucket.pdf;NewLiquidCrystal_1.5.1.zip'
),
(
	'Módulo LCD Nokia 5110',
	'Módulo LCD Nokia 5110 de 1.6\" com chip PCD8544 de 48x48 pixels com tensão de 2.7V ~ 3.3V, interface SPI, corrente de operação <5mA, com iluminação <20mA.',
	'DIY',
	1,
	'Box 000',
	'NOT ORGANIZED',
	'Module LCD Nokia 5110;Figure 1.jpg',
	'Module LCD Nokia 5110;Nokia5110.pdf',
	'Module LCD Nokia 5110;Adafruit-PCD8544-Nokia-5110-LCD-library-1.1.1.zip;Adafruit-GFX-Library-1.7.4.zip;BitmapEncoder-master.zip;LCDAssistant.zip;LCDAssistantCMD.zip;TheDotFactory-0.1.4.7z'
),
(
	'AGM-1604A-801 - Display de Cristal Liquido',
	'Display de Cristal Liquido modelo AGM-1604A-801, no formato 16*4 caracteres, com luz branca de fundo e cor de fundo azul.',
	'DIY',
	1,
	'Box 000',
	'NOT ORGANIZED',
	'16x4 LCD Display White-Blue LED Backlight;Figure 1.jpg',
	'16x4 LCD Display White-Blue LED Backlight;AGM-1604A-801.pdf',
	'16x2 LCD Display White-Blue LED Backlight;Arduino - HelloWorld.pdf;In-Depth Tutorial to Interface 16x2 Character LCD Module with Arduino.pdf;HelloWord.ino'
),
(
	'Módulo Touch Screen TFT 3.2in',
	'Módulo Touch Screen TFT 3.2in, modelo TFT01-3.2, com 65k core, resolução 320x240 pixels e tensão de trabalho de 3.3V.',
	'DIY',
	1,
	'Box 000',
	'NOT ORGANIZED',
	'3.2 inch TFT LCD Screen Module;Figure 1.jpg;Figure 2.jpg',
	'3.2 inch TFT LCD Screen Module;SSD1289-spec.pdf',
	'3.2 in TFT LCD Screen Module;UTFT.zip;3.2 inch TFT Touch LCD.zip;LCD 3.2 TFT LCD Screen Module.zip;The instruction for mega2560 board and 3.2 inch touch screen and shield.zip'
),
(
	'1602A - Módulo LCD com 16 caracteres por 2 linhas e fundo azul',
	'Modelo 6514 com 16 caracteres x 2 linhas, luz de fundo azul, caracteres branco e tensão de alimentação de 5VDC',
	'DIY',
	1,
	'Box 000',
	'NOT ORGANIZED',
	'16x2 LCD Display White-Blue LED Backlight;Figure 1.jpg;Figure 2.jpg;Figure 3.jpg',
	'16x2 LCD Display White-Blue LED Backlight;eone-1602a1.pdf',
	'16x2 LCD Display White-Blue LED Backlight;Arduino - HelloWorld.pdf;In-Depth Tutorial to Interface 16x2 Character LCD Module with Arduino.pdf;HelloWord.ino'
),
(
	'GTM2088ARGB-28 - Matriz de LEDs RGB 8x8 com super brilho',
	'Matriz de LEDs RGB 8x8 com super brilho, tensão 2.3V (Red)/3.4V (Green)/3.4V (Blue) e corrente de 50mA.',
	'LED',
	1,
	'Box 000',
	'NOT ORGANIZED',
	'LED Matrix 8x8 - Triple Color RGB common Anode Display - 5mm;Figure 1.jpg;Figure 2.jpg;Figure 3.jpg;Figure 4.jpg;Figure 5.jpg;Figure 6.jpg',
	'LED Matrix 8x8 - Triple Color RGB common Anode Display - 5mm;GTM2088ARGB-28.pdf',
	'LED Matrix 8x8 - Triple Color RGB common Anode Display - 5mm;Product Description.txt;8×32 Scrolling LED Message Display.zip'
),
(
	'Módulo matriz de LEDs vermelho com MAX7219',
	'Módulo matriz de LEDs (8x8) vermelho com catodo comum usando o chip MAX7219, alimentado em 5VDC, comunicação SPI e dimensões de 5cm de comprimento, 3.2cm de largura e 1.5cm de altura.',
	'LED',
	1,
	'Box 000',
	'NOT ORGANIZED',
	'MAX7219 Dot Matrix Display Module;Figure 1.jpg',
	'MAX7219 Serially Interfaced, 8-Digit LED Display Drivers;MAX7219-MAX7221 Serially Interfaced, 8-Digit LED Display Drivers.pdf',
	'MAX7219 Dot Matrix Display Module;LedControl-master.zip;8x8 LED Matrix MAX7219 Tutorial with Scrolling Text and Android Control via Bluetooth.zip;Aprenda a usar o Módulo Matriz de LEDs com MAX7219 - Embarcados.pdf'
),
(
	'Módulo LED RGB para Arduino',
	'Módulo 5050 (JY-MCU) LED RGB SMD de três cores para Arduino, podendo obter cores diferentes usando PWM.',
	'LED',
	1,
	'Box 000',
	'NOT ORGANIZED',
	'SMD 5050 RGB LED Module;Figure 1.png',
	'SMD 5050 RGB LED Module;5050LED.pdf',
	'SMD 5050 RGB LED Module;3 Color RGB LED Module - Summerfuel Robotics.pdf'
),
(
	'Módulo OLED Display 0.96 polegadas Azul/Amarelo 128X64 SPI',
	'Módulo OLED Display de 0.96 polegadas nas cores Azul e Amarelo com resolução de 128X64 pixels e comunicação SPI.',
	'LED',
	1,
	'Box 000',
	'NOT ORGANIZED',
	'0.96 inch SPI Serial 128X64 Yellow Blue OLED Display Module;Figure 1.jpg;Figure 2.jpg;Figure 3.jpg;Figure 4.jpg',
	'0.96 inch SPI Serial 128X64 Yellow Blue OLED Display Module;SSD1306.pdf',
	'0.96 inch SPI Serial 128X64 Yellow Blue OLED Display Module;Adafruit_SSD1306-2.0.4.zip;Adafruit-GFX-Library-1.7.4.zip'
),
(
	'Módulo OLED Display 1.3 polegadas Branco 128X64 SPI',
	'Módulo OLED Display de 1.3 polegadas na cor Branca com resolução de 128X64 pixels e comunicação SPI.',
	'LED',
	1,
	'Box 000',
	'NOT ORGANIZED',
	'1.3 inch SPI Serial 128X64 Yellow Blue OLED Display Module;Figure 1.jpg;Figure 2.jpg;Figure 3.jpg;Figure 4.jpg',
	'1.3 inch SPI Serial 128X64 Yellow Blue OLED Display Module;sh1106_datasheet.pdf',
	'1.3 inch SPI Serial 128X64 Yellow Blue OLED Display Module;Getting started with µOLED displays.zip'
),
(
	'Alicate Decapador H5 21K547',
	'Alicate Decapador H5, com regulagem ajustável de 5 a 12mm, corte de cabos e fios de até 2mm, decapador de 0.2mm^2 até 6.0mm^2 (24 AWG até 10AWG) fabricado na Alemanha.',
	'Tool',
	1,
	'Paper Box 01',
	'NOT ORGANIZED',
	'Alicate Decapador H5 21K547.jpg',
	'',
	''
),
(
	'Assistente de Soldagem Hikari HK-151',
	'Assistente de Soldagem Hikari com alavanca, gancho, escova, garfo, agulha, suporte, faca, raspador e broca.',
	'Tool',
	1
	'Paper Box 01',
	'NOT ORGANIZED',
	'Assistente de Soldagem Hikari HK-151.jpg',
	'',
	''
),
(
	'Extrator de CI PLCC Pinça WJ-368',
	'Extrator de CI PLCC Pinça, indicado para extração de CIs PLCC, PGA e DIP (soquete), com corpo em plástico e hastes em aço inoxidável, design ergonômico para retirar o CI verticalmente, adaptável à diversos tamanhos de CI e proteção anti-estática.',
	'Tool',
	1,
	'Paper Box 01',
	'NOT ORGANIZED',
	'Extrator de CI PLCC Pinça WJ-368.jpg',
	'',
	''
),
(
	'Pulseira anti-estática LEKO',
	'Pulseira anti-estática de cabo de aterramento de 1.6 metros.',
	'Tool',
	1,
	'Paper Box 01',
	'NOT ORGANIZED',
	'Pulseira anti-estática LEKO.jpg',
	'',
	''
),
(
	'Pinça angular de precisão anti-magnética TS-15',
	'Pinça angular de precisão anti-magnética de aço inoxidável.',
	'Tool',
	1,
	'Paper Box 01',
	'NOT ORGANIZED',
	'Pinça angular de precisão anti-magnética TS-15.jpg',
	'',
	''
),
(
	'Alicate Pinça Bico Pato Reto (Polofer)',
	'Alicate Pinça Bico Pato Reto (Polofer) para multiuso, de precisão, com trava no cabo (push).',
	'Tool',
	1,
	'Paper Box 01',
	'NOT ORGANIZED',
	'Alicate Pinça Bico Pato Reto (Polofer).jpg',
	'',
	''
),
(
	'Pinça CT01 Aço Inox 125mm - ponta reta lisa',
	'Pinça CT01 Aço Inox 125mm com ponta reta lisa de 25 gramas.',
	'Tool',
	1,
	'Paper Box 01',
	'NOT ORGANIZED',
	'Alicate Pinça CT01 Aço Inox 125mm - ponta reta lisa.jpg',
	'',
	''
),
(
	'Broca de aço inoxidável para circuito impresso PCB',
	'Broca de aço inoxidável para circuito impresso PCB de 3.175mm (diâmetro de haste) x 0.4mm (diâmetro de corte) x 7mm (comprimento de corte).',
	'Tool',
	9,
	'Paper Box 01',
	'NOT ORGANIZED',
	'Broca de aço inoxidável para circuito impresso PCB.jpg',
	'',
	''
),
(
	'Cabo teste para analisador lógico',
	'Cabo teste para analisador lógico com 10 garras, sendo 5 vermelhas e 5 amarelas.',
	'Tool',
	1,
	'Paper Box 01',
	'NOT ORGANIZED',
	'Cabo teste para analisador lógico.jpg',
	'',
	''
),
(
	'Jogo de Chave Torx T5 A T10',
	'Jogo de Chave Torx Com 6 Peças T5 A T10 para notebook e celular.',
	'Tool',
	1,
	'Paper Box 01',
	'NOT ORGANIZED',
	'Jogo de Chave Torx T5 A T10.png',
	'',
	''
),
(
	'Lupa de Aumento 75mm',
	'Lupa de Aumento de 75mm de diâmetro.',
	'Tool',
	1,
	'Paper Box 01',
	'NOT ORGANIZED',
	'Lupa de Aumento 75mm.jpg'
	'',
	''
),
(
	'Alicate de Corte Diagonal',
	'Alicate de corte diagonal para corte rente para acabamento.',
	'Tool',
	1,
	'Paper Box 01',
	'NOT ORGANIZED',
	'Alicate de Corte Diagonal.jpg',
	'',
	''
),
(
	'Alicate Aço Especial Corte Zero ACI-12',
	'Alicate Aço Especial Corte Zero ACI-12 para corte de contatos e fios.',
	'Tool',
	1,
	'Paper Box 01',
	'NOT ORGANIZED',
	'Alicate Aço Especial Corte Zero ACI-12.jpg',
	'',
	''
),
(
	'Sugador de Solda Suetoku Profissional',
	'Sugador de Solda Suetoku Profissional para uso para retirar solda de Estanho.',
	'Tool',
	1,
	'Paper Box 01',
	'NOT ORGANIZED',
	'Sugador de Solda Suetoku Profissional.jpg',
	'',
	''
),
(
	'Kit de Chaves de Precisão com 31 Peças',
	'Kit de Chaves de Precisão com 31 Peças, onde há 1 cabo e 30 Bits Chaves Allen, Torx, Philips, e Fenda Para Manutenção de Celulares e Eletrônicos.',
	'Tool',
	1,
	'Paper Box 01',
	'NOT ORGANIZED',
	'Kit de Chaves de Precisão com 31 Peças.jpg',
	'',
	''
),
(
	'Luva ESD Anti-estática Fingerfit Ponta dos Dedos',
	'Lupa dissipativa emborrachada em PU na ponta dos dedos, composta de poliamida, poliéster e filamentos condutores. Possui resistividade de 1 x 10^8 ohms.',
	'Tool',
	1,
	'Paper Box 01',
	'NOT ORGANIZED',
	'Luva ESD Anti-estática Fingerfit Ponta dos Dedos.png',
	'',
	''
),
(
	'Kit acessórios com 137 peças para mini esmeril EDA-9QR',
	'Itens inclusos: 4 Pinças: 0.8, 1.6, 2.4 e 3.2mm; 5 Discos de corte reforçados de fibra de vidro 32mm; 65 Discos de corte 26mm; 1 Tubos com pasta de polir; 1 Escova de cerdas; 6 Pontas montadas; 3 Suportes para discos de corte; 2 Suportes para tubo de lixa; 1 Suporte para discos de feltro; 5 Pontas diamantadas; 2 Fresas; 4 Tubos de lixa 1/2"; 5 Tubos de lixa 1/4"; 1 Pedra para afiar; 4 Rolos de esmeril; 2 Pedras de polimento; 5 Feltros diversos tamanhos; 20 discos de lixa, Maleta.',
	'Tool',
	1,
	'Paper Box 01',
	'NOT ORGANIZED',
	'Kit acessorios com 137 pecas para mini esmeril EDA-9QR_1.jpg;Kit Acessorios com 137 Pecas para Mini Esmeril EDA-9QR-2.jpg;Kit Acessorios com 137 Pecas para Mini Esmeril EDA-9QR-3.jpg',
	'',
	''
),
(
	'Kit chaves para celular Lelong 36 peças modelo LE-960',
	'Itens inclusos: Chave Torx: T2, T3, T4, T5, T6, T7, T8, T9, T10, T15; Chave Philips: 1.2, 1.5, 2.0; Chave de Fenda: 1.5, 2.0; Chave Hexagonal: 2.5, 3, 3.5, 4, 4.5, 5, 5.5; Chave Estrela (5 Pontas): 0.8, 1.2; Chave Y: 2.0; Chave PH2; Chave Triangulo: 2.3; Chave U1: 2.6; 02 - chaves plásticas; 01 - Ventosa; 01 - Pinça.',
	'Tool',
	1,
	'Paper Box 01',
	'NOT ORGANIZED',
	'Kit chaves para celular lelong 36 pecas_le-960_1.png;Kit chaves para celular lelong 36 pecas_le-960_2.png',
	'',
	''
),
(
	'Pontas para Retífica Black Bull',
	'Pontas para retífica com 20 pontas e 1/8\" (3mm) cada, composto de ferro cobertas com carboneto de silicone.',
	'Tool',
	1,
	'Paper Box 01',
	'NOT ORGANIZED',
	'Pontas para Retífica Black Bull_1.jpg;Pontas para Retífica Black Bull_2.jpg',
	'',
	''
),
(
	'Conjunto de Agulha Aço Inoxidável de Circuito Eletrônico de 80mm x 0.7-1.3mm',
	'Conjunto de 10 Agulhas de Circuito Eletrônico PCB para reparo de soldagem com comprimento de 80mm e diâmetro de 0.7 até 1.3mm',
	'Tool',
	1,
	'Paper Box 01',
	'NOT ORGANIZED',
	'Agulha Circuito Eletrônico_1.jpg;Agulha Circuito Eletrônico_2.jpg;Agulha Circuito Eletrônico_3.jpg;Agulha Circuito Eletrônico_4.jpg;Agulha Circuito Eletrônico_5.jpg;Agulha Circuito Eletrônico_6.jpg',
	'',
	''
),
(
	'Ponta de Prova com Gancho',
	'Ganhos na cores preto, vermelho, verde, amarelo e azul, em material latão e plástico, gancho bronze de 4mm x 2mm, com conexão dos clipes com o multimetro ou fonte.',
	'Tool',
	1,
	'Paper Box 01',
	'NOT ORGANIZED',
	'Ponta de Prova Gancho_1.jpg;Ponta de Prova Gancho_2.jpg;Ponta de Prova Gancho_3.jpg;Ponta de Prova Gancho_4.jpg;Ponta de Prova Gancho_5.jpg;Ponta de Prova Gancho_6.jpg',
	'',
	''
),
(
	'Chave Ajuste Vishay Spectrol TO-008',
	'Chave Ajuste Vishay Spectrol TO-008 para trimmer e trimpot multivoltas.',
	'Tool',
	1,
	'Paper Box 01',
	'NOT ORGANIZED',
	'Chave Ajuste Spectrol TO-008 para trimmer-trimpot.jpg',
	'',
	''
),
(
	'Escova ESD Hikari HK-219',
	'Escova anti-estática para limpar placas de eletrônica sem descarregar cargas eletrosestáticas. Cabo ergonômico de 125mm com cerdas de 52mm x 3mm x 25mm.',
	'Tool',
	1,
	'Paper Box 01',
	'NOT ORGANIZED',
	'escova_esd_hk-219_frente.jpg;escova_esd_hk-219_lateral.jpg',
	'',
	''
),
(
	'Detector e Medidor de Tensão Hyx Vd4',
	'Medição de tensão diretamente de 12~220V. Detecção de tensão sobre linhas inderetamente de 12~220V. Não necessita de pilhas.',
	'Tool',
	1,
	'Paper Box 01',
	'NOT ORGANIZED',
	'Detector e Medidor de Tensão Hyx Vd4.jpg',
	'',
	''
),
(
	'Wi-Pi módulo Wi-Fi para Raspberry Pi',
	'Wi-Pi módulo Wi-Fi para Raspberry Pi compativel com IEEE 802.11,802.11g e 802.11b. Intervalo de frequência de 2.4GHz até .4835GHz. Suporte nativo para o Linux Raspbian Weezy. Interface USB 2.0 e potência máxima de transmissão de 20dBm.',
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',
	'Wi-Pi módulo Wi-Fi para Raspberry Pi.jpg',
	'',
	''
),
(
	'Adaptador USB para Ethernet Apple',
	'Adaptador USB 2.0 para Ethernet Apple que oferece um conector RJ-45 compatível com Ethernet 10/100BASE-T.',
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',
	'Adaptador USB para Ethernet Apple.jpg',
	'',
	''
),
(
	'Gravador AVR USBasp',
	'Gravador para controladores Atmel AVR com uma conexão USB. Permite a leitura ou escrita na EEPROM, firmware, fuse bits e lock bits. Velocidade de programação maior que 5kBytes/seg. Opção de modo lento SCK para alvos com baixo clock (<1.5MHz).',
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',
	'Gravador AVR USBasp_1.jpg;Gravador AVR USBasp_2.jpg;Gravador AVR USBasp_3.jpg;Gravador AVR USBasp_4.jpg',
	'',
	''
),
(
	'Adaptador 10 pinos para 6 pinos AVRISP USBasp',
	'Adaptador 10 pinos para 6 pinos AVRISP USBasp para uso no gravador AVR USBasp, AVRISP, USBASP e STK500.',
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',
	'Adaptador 10 pinos para 6 pinos AVRISP USBasp_1.jpg;Adaptador 10 pinos para 6 pinos AVRISP USBasp_2.jpg;Adaptador 10 pinos para 6 pinos AVRISP USBasp_3.jpg;Adaptador 10 pinos para 6 pinos AVRISP USBasp_4.jpg',
	'',
	''
),
(
	'Conversor USB para RS232 TTL PL2303HX',
	'Simples comunicação UART e saída de 3.3V ou 5V.',
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',
	'Conversor USB para RS232 TTL PL2303HX.jpg',
	'',
	''
),
(
	'Placa Adaptadora de Som USB Virtual com canal 5.1',
	'Placa de som surround virtual 5.1 com USB 2.0, perfeito para fone de ouvido ou alto falantes e um microfone.',
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',
	'Placa Adaptadora de Som USB Virtual com canal 5.1_1.jpg;Placa Adaptadora de Som USB Virtual com canal 5.1_2.jpg',
	'',
	''
),
(
	'Multímetro Digital MD-6130 True RMS',
	'Multímetro Digital MD-6130 para leituras de tensão/corrente elétrica contínua/alternada (True RMS), de temperatura, de teste de transistores, diodos e continuidade, de resistência, de capacitância, indutância e frequência.',
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',
	'Multímetro Digital MD-6130 True RMS.jpg',
	'',
	''
),
(
	'Multímetro Analógico HM202A+',
	'Multímetro Analógico HM202A+ com medição de tensão elétrica contínua/alternada, corrente elétrica contínua, resistência, decibel, teste de transistores/ICEO e continuidade.',
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',
	'Multímetro Analógico HM202A+.jpg',
	'',
	''
),
(
	'Satelite Finder SF-95',
	'Satelite Finder SF-95 é um localizado de Satélite FINDER 950~2150MHz, com entrada máxima de -10dBm e tensão de alimentação 13~18V DC.',
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',
	'Satelite Finder SF-95.jpg;Satelite Finder SF-95_1.jpg;Satelite Finder SF-95_2.jpg;Satelite Finder SF-95_3.jpg',
	'',
	''
),
(
	'PICkit 3 PIC Programmer',
	'Com conexão USB, execução real-time, compatível MPLAB IDE, monitor curto-circuito/sobre-tensão, suporte baixa tensão até 2V (2~6V), LEDs diagnóstico (alimentação, ocupado e erro), leitura/escrita memória de programa e dados microcontrolador.',
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',
	'PICkit 3 PIC Programmer.jpg',
	'',
	''
),
(
	'Gravador de PIC K150 (USB 40ZIF)',
	'Gravador de microcontroladores PIC de alguns das séries 12C, 12F, 16C, 16F e 18. Gravador com soquete ZIF de 40 pinos. Compatível somente com Windows 98/2000/NT/XP e 7.',
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',
	'Gravador de PIC K150 (USB 40ZIF)_1.jpg;Gravador de PIC K150 (USB 40ZIF)_2.jpg',
	'',
	''
),
(
	'Mini Teclado Wireless 2.4Hz USB',
	'Mini Teclado Wireless 2.4Hz USB com suporte para HTPC, computadores com sistemas operacional Windows/Linux/Mac, PlayStation3, XBOX 360 e Android. Tensão de alimentação de 3V (2x AAA) com corrente menor que 50mA em operação e 1mA em descanso.',
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',
	'Mini Teclado Wireless 2.4Hz USB.jpg',
	'',
	''
),
(
	'Analisador Lógico Open Bench',
	'Analisador lógico open source (Open Bench Logic Sniffer) com interface USB, captura formas de onda de até 50MHz sobre 32 canais, 16 canais de 5V com buffer.',
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',
	'Analisador Lógico Open Bench_1.jpg;Analisador Lógico Open Bench_2.jpg;Analisador Lógico Open Bench_3.jpg',
	'',
	''
),
(
	'Balança Digital Portátil',
	'Balança digital com capacidade de 1000g, e mínimo de 0.1g, com unidades em g, ct, oz e gn. Divisões de 0.1g, temperatura de operação de 10~30ºC e uso de 2 pilhas AAA.',
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',
	'Balança Digital Portátil.jpg',
	'',
	''
),
(
	'RF Explorer 3G Combo - Analisador de Espectro',
	'Analisador de Espectro portátil com tela LCD 128x64 pixels, leitura em 240~960MHz/15~2700MHz, com alcance de 112kHz~100MHz, uma antena Sub-GHz Nagoya NA-773 e outra 2.4GHz helicoidal, amplitude de resolução de 0.5dBm.',
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',
	'RF Explorer 3G Combo - Analisador de Espectro.png',
	'',
	''
),
(
	'Microscopio 1000X USB',
	'Microscópio USB com ampliação de 1000X, com captura de imagem e vídeo.',
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',
	'Microscopio 1000X USB.jpg',
	'',
	''
),
(
	'Nano Adaptador USB Wireless N150Mbps TL-WN725N',
	'Adaptador USB Wireless com velocidade de transmissão Wireless de até 150Mbps e segurança avançada com suporte a WEP de 64/128, WPA, PA2/WPA-PSK/WPA2-PSK (TKIP / AES).',
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',
	'Nano Adaptador USB Wireless N150Mbps TL-WN725N_1.jpg;Nano Adaptador USB Wireless N150Mbps TL-WN725N_2.jpg',
	'',
	''
),
(
	'Multímetro Digital Minipa ET-2041',
	'Leitura tensão contínua (alternada) 200mV~1000V (2V~750V), corrente contínua (alternada) 2mA~20A (20mA~20A), capacitância 2nF~20uF, temperatura, frequência, teste transistores bipolares, teste diodos/continuidade e resistência 200Ohms~200MOhms.'
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',
	'Multímetro Digital Minipa ET-2041.jpg',
	'',
	''
),
(
	'Cabo conversor USB para RS232',
	'Especificação USB 1.1 e 2.0; Suporte RS232 com interface DB9 e DB25; Taxa de transferência acima de 1Mbps',
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',
	'Adaptador USB-RS232 - 1.jpg;Adaptador USB-RS232 - 2.jpg;Adaptador USB-RS232 - 3.jpg;Adaptador USB-RS232 - 4.jpg',
	'',
	''
),
(
	'Peso de Calibração de 5 gramas',
	'Peso de Calibração de 5 gramas.',
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',
	'peso de Calibracao 5 gramas_1.jpg;peso de Calibracao 5 gramas_2.jpg;peso de Calibracao 5 gramas_3.jpg',
	'',
	''
),
(
	'Tomada USB 2.0 com 7 portas',
	'Tomada USB 2.0 com 7 portas compatível com USB 1.1, taxa de transferência de dados de 1.5 Mbps até 480 Mbps e proteção de 500mA.',
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',
	'Tomada USB 2.0 com 7 portas_1.jpg;Tomada USB 2.0 com 7 portas_2.jpg;Tomada USB 2.0 com 7 portas_3.jpg;Tomada USB 2.0 com 7 portas_4.jpg;Tomada USB 2.0 com 7 portas_5.jpg;Tomada USB 2.0 com 7 portas_6.jpg;',
	'',
	''
),
(
	'Cabo extensor com conector OBD2 macho para fêmea de 16 pinos para ELM327 da Elbow',
	'Cabo extensor com conector OBD2 macho para fêmea de 16 pinos para ELM327 da Elbow com comprimento de 60cm',
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',	'Extension_Cable_Flat_OBD2_16Pin_Male_to_Female_ELM327_1.jpg;Extension_Cable_Flat_OBD2_16Pin_Male_to_Female_ELM327_2.jpg;Extension_Cable_Flat_OBD2_16Pin_Male_to_Female_ELM327_3.jpg;Extension_Cable_Flat_OBD2_16Pin_Male_to_Female_ELM327_4.jpg',
	'',
	''
),
(
	'Conversor USB para RS485',
	'Módulo conversor USB para RS485; Cor: Preta; Driver USB: CH340; Velocidade: 75~115200bps; Máxima distância de comunicação RS485: 1200m; Dimensões: 60mmx18mmx14mm.';
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',
	'USB to RS485_1.jpg;USB to RS485_2.jpg;USB to RS485_3.jpg;USB to RS485_4.jpg',
	'',
	'CH341SER.zip;CH341SER (2).zip'
),
(
	'Conversor USB para RS232 TTL FT232RL',
	'Módulo Conversor FTDI FT232RL USB para RS232 Serial TTL com operação em 3.3 ou 5V. Chip: FT232RL; LEDs indicadores RX e TX; Tensão TTL selecionável para 5V ou 3.3V; Pinos: DTR, RXD, TX, VCC, CTS, GND; Interface: Mini USB; Dimensões: 36 x 18mm',
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',
	'USB to RS232 TTL FT232RL_1.png;USB to RS232 TTL FT232RL_2.jpg',
	'FT232R USB UART I.C._v104.pdf',
	''
),
(
	'CC2530 - Módulo ZigBee',
	'Composto por 2 Módulos ZigBee CC2530, 2 Placas Base, 2 Antenas 2.4G 3dB, 1 Módulo Smart RF04EE, 2 Cabos USB. Módulo com 16 canais de transmissão, taxa de transmissão de até 250kbps, transmissão confiável de até 250 metros.',
	'DIY',
	1,
	'Paper Box 03',
	'NOT ORGANIZED',
	'Module ZigBee CC2530, 2 base board and module Smart RF04EE;Figure 1.jpg;Figure 2.jpg',
	'Module ZigBee CC2530, 2 base board and module Smart RF04EE;cc2530.pdf',
	'Module ZigBee CC2530, 2 base board and module Smart RF04EE;ZigBee.7z'
),
(
	'Arduino LilyPad',
	'Projeto Arduino LilyPad com microcontrolador ATmega328 com tensão de operação de 2.7~5.5V, 14 pinos I/O, 6 pinos PWM e 6 pinos de entrada analogica, 40mA de corrente I/O, 16kB de flash, 1kB de SRAM, 512 bytes e velocidade de clock de 8MHz.',
	'Embedded',
	1,
	'Paper Box 03',
	'NOT ORGANIZED',
	'Arduino LilyPad.jpg',
	'',
	''
),
(
	'Arduino Nano',
	'Placa de desenvolvimento do projeto Arduino, em um tamanho menor comparado ao Arduino UNO, mas com caracteristicas semelhantes (ATmega328).',
	'Embedded',
	2,
	'Paper Box 03',
	'NOT ORGANIZED',
	'Arduino Nano V3-0_1.jpg;Arduino Nano V3-0_2.jpg',
	'',
	'CH341SER.zip;CH341SER (2).zip',
),
(
	'Onion Omega 2+',
	'Microcontrolador com 580MHz de processamento, 128MB de memria, 32MB de armazenamento flash, ÚSB 2.0, slot microSD , 15 pinos de GPIO, 2 PWM, 2 UART, 1 I2C, 1 SPI e 1 I2S.',
	'Embedded',
	1,
	'Paper Box 03',
	'NOT ORGANIZED',
	'Onion Omega 2 - front-back.png;Onion Omega 2 - Pinout-Diagram.png',
	'',
	''
),
(
	'Arduino Mega 2560 R3',
	'Placa com microcontrolador ATmega2560 com tensão de operação/entrada 5V/(7-12V), 54 portas digitais (15 PWM), 16 portas analógicas, corrente pinos I/O 40mA, corrente pinos 3.3V de 50mA, memória flash 256kB, SRAM 8kB, EEPROM 4kB, clock 16MHz.',
	'Embedded',
	1,
	'Paper Box 03',
	'NOT ORGANIZED',
	'Arduino-Mega-2560-Pinout.jpg',
	'',
	''
),
(
	'Arduino Uno R3',
	'Arduino Uno R3, com microcontrolador ATmega328, tensão operação/entrada 5V/(7-12V), 14 pinos I/O digitais (6 PWM) de 5V/40mA, 6 pinos analógicos, corrente pino 3.3V de 50mA, memória flash 32kB, SRAM 2kB, EEPROM 1kB e clock de 16MHz.',
	'Embedded',
	1,
	'Paper Box 03',
	'NOT ORGANIZED',
	'Arduino Uno R3.jpg;Arduino Uno R3 - perspective.png',
	'',
	''
),
(
	'BeagleBone Black',
	'BeagleBone Black AM3358 1GHz ARM Cortex-A8, 512MB DDR3 RAM, 4GB 8bit eMMC, acelerador gráfico 3D e ponto flutuante NEON, 2 microcontroladores PRU 32-bit, porta mini USB comunição/alimentação, USB, ethernet, saída HDMI, 92 pinos I/0 e alimentação.',
	'Embedded',
	1,
	'Paper Box 03',
	'NOT ORGANIZED',
	'Beaglebone Black - perspective.jpg;Beaglebone Black.jpg;BeagleBone Black - top.jpg',
	'',
	''
),
(
	'C.H.I.P.',
	'C.H.I.P. com processador de 1GHz, 4GB de armezanemento de alta velocidade, WiFi B/G/N, 512MB de RAM, bluetooth 4.0, conector para saída de VGA/audio, porta mini USB e USB.',
	'Embedded',
	1,
	'Paper Box 03',
	'NOT ORGANIZED',
	'CHIP.png'
	'',
	''
),
(
	'Raspberry Pi modelo Board B Rev2.0 512 ARM',
	'Raspberry Pi processador BCM2835 (CPU, GPU, DSP, e SDRAM), cpu 700 MHz ARM1176JZF-S core (ARM11 family), gpu Broadcom VideoCore IV, OpenGL ES 2.0, 1080p30 h.264/MPEG-4 AVC high-profile decoder, 512MB SDRAM, saida RCA/HDMI/P2, slot SD/MMC/SDIO e Ethernet',
	'Embedded',
	1,
	'Paper Box 03',
	'NOT ORGANIZED',
	'Raspberry Pi modelo Board B Rev2.0 512 ARM.png',
	'',
	''
),
(
	'Raspberry Pi 3 model B',
	'Processador quad-core 1.2 GHz 64-bit ARMv8, Wirelles 802.11n, Bluetooth 4.1 (BLE), 1GB RAM, 4 USB, 40 GPIO, HDMI, Ethernet, saída áudio/vídeo composto, interface Câmera e Display, slot Micro SD e gráfico VideoCore IV 3D.',
	'Embedded',
	1,
	'Paper Box 03',
	'NOT ORGANIZED',
	'Raspberry Pi 3 model B.jpg',
	'',
	''
),
(
	'Adaptador TF para SD Card',
	'Adaptador TF para SD Card para uso no Raspberry Pi modelo B.',
	'Equipment',
	1,
	'Paper Box 03',
	'NOT ORGANIZED',
	'Adaptador TF para SD Card.jpg',
	'',
	''
),
(
	'Adaptador GPIO para Raspberry PI',
	'Adaptador GPIO com revisão 2.0 com 26 pinos compatível com Raspberry Pi 2 e modelo B e B+.',
	'Tool',
	1,
	'Paper Box 03',
	'NOT ORGANIZED',
	'Adaptador GPIO para Raspberry PI_1.jpg;Adaptador GPIO para Raspberry PI_2.jpg;Adaptador GPIO para Raspberry PI_3.jpg;Adaptador GPIO para Raspberry PI_4.jpg',
	'',
	''
),
(
	'NodeMcu ESP8266 (ESP-12E)',
	'Modelo Amica, driver CP2012, antena embutida, wireless padrão 802.11 b/g/n, 11 GPIO de funções de PWM, I2C, SPI, etc, tensão operação 4,5~9V, taxa transferência: 110~460800bps, modo operação STA/AP/STA+AP, suporta 5 conexões TCP/IP.',
	'Embedded',
	2,
	'Paper Box 03',
	'NOT ORGANIZED',
	'nodemcu_amica_esp12_1.jpg;nodemcu_amica_esp12_2.jpg',
	'',
	''
),
(
	'ESP8266 ESP-12F',
	'Wi-Fi 802.11 B/G/N; Wi-Fi Direct (P2P), soft-AP; Stack TCP/IP integrada; CPU 32 bits de baixo consumo integrada; SDIO 1.1/2.0, SPI, UART; Segurança: WPA, WPA2; ADC 10 bits; Memória Flash: 4Mbyte; Tensão (alimentação / IO): 3.3v.',
	'Embedded',
	4,
	'Paper Box 03',
	'NOT ORGANIZED',
	'ESP-12F_1.jpg;ESP-12F_2.jpg;ESP-12F_3.jpg;ESP-12F_4.jpg',
	'ESP-12F.pdf',
	''
),
(
	'ESP32',
	'Microprocessador 32-bit/2 núcleos, Wi-Fi 802.11 b/g/n/e/i, bluetooth v4.2 BR/EDR e BLE, ROM 448KiB, SRAM 520KiB, 10 GPIOs, ADCs 12/8bits, 2 I2C, 2 UART, CAN 2.0, 4 SPI, 2 I2S, 16 PWM. Aceleração Criptografia AES, SHA-2, RSA, ECC e RNG.',
	'Embedded',
	1,
	'Paper Box 03',
	'NOT ORGANIZED',
	'ESP-32_1.jpg;ESP-32_2.jpg;ESP-32_3.png;ESP-32_4.png',
	'ESP32 Datasheet.pdf;ESP-WROOM-32 Datasheet.pdf'
	'',
	''
),
(
	'DS18B20 - Sensor de temperatura TO92',
	'Sensor temperatura com resolução programável por 1 fio de 9~12 bits, tensão alimentação 3.0~5.5V, temperatura medida entre -55&deg;C até +125&deg;C, conversão 12 bits em 750ms (max), acuracia +-0.5&deg;C de temperaturas entre -10&deg; até +85&deg;C',
	'Integrated Circuit',
	10,
	'Paper Box 04',
	'NOT ORGANIZED',
	'DS18B20.png;DS18B20_pins.png',
	'',
	''
),
(
	'LM35DZ - Sensor de temperatura',
	'Sensor de temperatura para medidas entre -55&deg;C até 150&deg;C, com tensão de operação entre 4~30V, consumo de corrente menor que 60uA, fator linear 10mV/&deg;C.',
	'Integrated Circuit',
	1,
	'Paper Box 04',
	'NOT ORGANIZED',
	'LM35DZ.jpg',
	'',
	''
),
(
	'Módulo de Sensor de Som',
	'Módulo de Sensor de Som com sensibilidade ajustada, com tensão de operação de 3.3V~5V, com saída digital on-off e saída analógica regulada por potenciômetro.',
	'DIY',
	1,
	'Paper Box 04',
	'NOT ORGANIZED',
	'Modulo de Sensor de Som.jpg',
	'',
	''
),
(
	'Sensor de chuva',
	'Sensor de chuva com saída analógica e digital.',
	'DIY',
	1,
	'Paper Box 04',
	'NOT ORGANIZED',
	'Sensor de chuva.jpg',
	'',
	''
),
(
	'RFID-RC522 - Módulo Sensor de Cartão RFID',
	'Módulo Sensor de Cartão RFID-RC522 com corrente de trabalho de 13~26mA/3.3V. Suporta cartões Mifare1 S50, Mifare1 S70, Mifare Ultralight, Mifare Pro e Mifare Desfare.',
	'DIY',
	1,
	'Paper Box 04',
	'NOT ORGANIZED',
	'Módulo Sensor de Cartão RFID.jpg',
	'',
	''
),
(
	'GY-521 (MPU6050) Módulo de 3 eixos de aceleração e giroscópio',
	'Módulo GY-521 de 3 eixos de aceleração/giroscópio 6DOF com chip MPU6050, alimentação 3~5V, comunicação I2C, conversor A/D de 16 bits, range do giroscópio de +- 250, 500, 1000 e 2000 degree/sec, range do acelerômetro de +- 2g, +-4g, +-8g e +-16g.',
	'DIY',
	1,
	'Paper Box 04',
	'NOT ORGANIZED',
	'Módulo de 3 eixos de aceleração e giroscópio DOF MPU-6050.jpg',
	'',
	''
),
(
	'HC-SR04 - Módulo de sensor de ultrassônico',
	'Módulo de sensor de ultrassônico para medição de distância HC-SR04 com tensão de alimentação de 5V DC, corrente de operação de 2mA, alcance de 2cm~4m e precisão de 3mm.',
	'DIY',
	1,
	'Paper Box 04',
	'NOT ORGANIZED',
	'Módulo de sensor de ultrassônico HC-SR04.jpg',
	'',
	''
),
(
	'XD-58C - Módulo de frequência cardíaca',
	'Módulo de frequência cardíaca XD-58C com tensão de trabalho de 3~5V de material FR4 da marca KEYES.',
	'DIY',
	1,
	'Paper Box 04',
	'NOT ORGANIZED',
	'Módulo de frequência cardíaca XD-58C.jpg',
	'',
	''
),
(
	'ACS712-20A - Módulo de Sensor de Corrente até 20A',
	'Módulo ACS712 20A de Sensor Corrente de 20A com tempo resposta de 5us, largura banda de 80kHz, margem erro de 1.5% a 25°C, resistência interna de 0.0012Ohms, tensão isolação de 2.1kVrms, tensão alimentação de 4.5~5.5V e sensibilidade de 100mV/A.',
	'DIY',
	1,
	'Paper Box 04',
	'NOT ORGANIZED',
	'Módulo de Sensor de Corrente até 20A ACS712 20A.jpg',
	'',
	''
),
(
	'MQ-3 - Sensor Álcool Etanol',
	'Sensor Álcool Etanol MQ-3 com tensão de alimentação de 5V e saídas analógica e digital.',
	'DIY',
	1,
	'Paper Box 04',
	'NOT ORGANIZED',
	'Sensor Álcool Etanol MQ-3.jpg',
	'',
	''
),
(
	'HC-SR501 - Sensor Infravermelho de movimento',
	'Sensor HC-SR501 de Infravermelho de movimento ROBOX RTHW com consumo em standby de 50uA, distancia máxima de detecção de 7m, ângulo  de máximo de detecção de 110° e tensão de alimentação de 4.5~20V.',
	'DIY',
	1,
	'Paper Box 04',
	'NOT ORGANIZED',
	'Sensor Infravermelho de movimento ROBOX IR HC-SR501.jpg',
	'',
	''
),
(
	'MQ-2 - Sensor de gás liquefeito de petróleo e natural',
	'Sensor MQ-2 com saída digital e analógica, sensível a gás liquefeito de petróleo, natural, de cidade e de poluição.',
	'DIY',
	1,
	'Paper Box 04',
	'NOT ORGANIZED',
	'Sensor MQ-2 de gás liquefeito de petróleo e natural.png',
	'',
	''
),
(
	'BH1750FVI - Sensor Digital de Intensidade de Luz',
	'Chip BH1750FVI original da ROHM, tensão de alimentação de 3~5V, intevalo de iluminância de 0~65535 lux e conversor AD de 16 bits.',
	'DIY',
	1,
	'Paper Box 04',
	'NOT ORGANIZED',
	'Sensor Digital de Intensidade de Luz BH1750FVI.jpg',
	'BH1750FVI - Digital 16 bit Serial Output Type Ambient Light Sensor IC.pdf',
	'TEST_BH1750.zip;BH1750-master.zip'
),
(
	'Módulo Bluetooth V2.0',
	'Tensão/corrente de trabalho de 3.3V/20~3mA, conectado 8mA, configuração default de 9600, N, 8, 1 e senha 1234.',
	'DIY',
	1,
	'Paper Box 04',
	'NOT ORGANIZED',
	'Módulo Bluetooth V2.0 hc-05-HC-05-RF-Wireless1.jpg;Módulo Bluetooth V2.0 hc-05-HC-05-RF-Wireless2.jpg',
	'',
	''
),
(
	'MQ-7 - Sensor de Monóxido de Carbono',
	'Sensor MQ-7 com material SnO2 com a capacidade de detectar CO, trabalhando com tensão de 5V e saída digital e analógica.',
	'DIY',
	1,
	'Paper Box 04',
	'NOT ORGANIZED',
	'Sensor MQ-7 de Monóxido de Carbono1.jpg;Sensor MQ-7 de Monóxido de Carbono2.jpg',
	'',
	''
),
(
	'Módulo Sensor Magnético de Efeito Hall',
	'Módulo Sensor Magnético de Efeito Hall para aplicações em trabalhos com campos magnéticos, velocidade e \"gap\" de indução. Tensão de alimentação de 5V.',
	'DIY',
	1,
	'Paper Box 04',
	'NOT ORGANIZED',
	'Módulo Sensor Magnético de Efeito Hall (a3144eul).jpg',
	'',
	''
),
(
	'SW-520D - Módulo de Sensor de Ângulo',
	'Módulo de Sensor de Ângulo com SW-520D, tensão de alimentação de 3.3~12VDC, saída 0 (LED verde ligado) e 1 (LED verde desligado).',
	'DIY',
	1,
	'Paper Box 04',
	'NOT ORGANIZED',
	'Modulo de Sensor de Angulo (SW520).jpg',
	'',
	''
),
(
	'GY-273 (HMC5883L) - Módulo Bússola',
	'Módulo Bússola GY-273 com chip HMC5883L, tensão de alimentação de 3~5V, comunicação I2C, faixa de medição +-1.3~8 Gaus.',
	'DIY',
	1,
	'Paper Box 04',
	'NOT ORGANIZED',
	'Módulo Bússola GY-273 (HMC5883L).jpg',
	'',
	''
),
(
	'Módulo Sensor Gestos e RGB',
	'Sensor de Gestos e Luz Ambiente de alimentação de 3.3V.',
	'DIY',
	1,
	'Paper Box 04',
	'NOT ORGANIZED',
	'Modulo Sensor Gestos e RGB.jpg',
	'',
	''
),
(
	'ADXL345 - Módulo Digital Sensor Aceleração',
	'Módulo Digital Sensor Aceleração ADXL345 de 3-eixos de +-2g, +-4g, +-8g, +-16g, com resolução fixada de 10 bits. Tensão de alimentação de 5V/3.3V',
	'DIY',
	1,
	'Paper Box 04',
	'NOT ORGANIZED',
	'Modulo Digital Sensor Aceleracao ADXL345.jpg',
	'',
	''
),
(
	'TTP223B - Módulo Sensor Touch',
	'Módulo Sensor Touch TTP223B com tensão de operação de 2~5.5V, saída de estado alto/baixo de 0.8V/0.3V, tempo de resposta de 220ms (estado baixo) e 60ms (estado alto)',
	'DIY',
	1,
	'Paper Box 04',
	'NOT ORGANIZED',
	'Modulo Sensor Touch TTP223B (Touch Sensor Capacitive).jpg',
	'',
	''
),
(
	'BMP085 - Módulo Digital Sensor de Pressão Barométrica e Temperatura do Ar BOSCH',
	'Intervalo pressão barométrica 300~1100hPa (elevação 9000~500m), tensão alimentação 1.8~3.6V (VDDA), 1.62~3.6V (VDDD), consumo modo padrão 5uA, acurácia alta c/ resolução 0.06hPa (0.5m), no modo linear, resolução é 0.03hPa (0.25m).',
	'DIY',
	1,
	'Paper Box 04',
	'NOT ORGANIZED',
	'Módulo Digital Sensor de Pressão Barométrica e Temperatura do Ar BOSCH BMP085.jpg',
	'BMP085 - Digital pressure sensor.pdf',
	'Adafruit_Python_BMP-master.zip;Adafruit-BMP085-Library-master.zip;Adafruit_Python_GPIO-master.zip;BMP280_driver-master.zip',
),
(
	'Módulo de Sensor de toque de corpo humano',
	'Tensão de alimentação de 5VDC e uso do circuito LM393, saída analógica e digital.',
	'DIY',
	1,
	'Paper Box 04',
	'NOT ORGANIZED',
	'Módulo de Sensor de toque de corpo humano.jpg',
	'',
	''
),
(
	'AT-09 - Módulo Bluetooth',
	'Módulo Bluetooth 4.0 para Arduino com serial BLE CC2540 CC2541 iBeacon.',
	'DIY',
	1,
	'Paper Box 04',
	'NOT ORGANIZED',
	'Módulo Bluetooth AT-09.jpg',
	'',
	''
),
(
	'UVM-30A - Sensor de Detecção de Raios Ultravioleta',
	'Sensor com 28mm/12mm/10mm, detecção raios ultravioletas, alimentação 3~5V, tensão saída 0~1VDC, precisão teste de +-1 UV INDEX, corrente funcionamento 0.06mA (typ) e 0.1mA (max), comprimento onda de resposta 200nm~370nm, estabilidade de -20º~85º',
	'DIY',
	1,
	'Paper Box 04',
	'NOT ORGANIZED',
	'Sensor UVM-30A de Detecção de Raios Ultravioleta.jpg',
	'',
	''
),
(
	'HB100 - Sensor de detecção de radar',
	'Sensor microondas de efeito doppler com frequência de 10.525 GHz, alimentação de 5V +-0.25V, corrente de 40mA, dimensões 37mm (c), 45mm (l) e 8mm (a).',
	'DIY',
	1,
	'Paper Box 04',
	'NOT ORGANIZED',
	'Sensor de detecção de radar HB100.jpg',
	'',
	''
),
(
	'RCWL-0516 - Radar doppler',
	'Radar doppler RCWL-0516 para sensor de movimento para detecção de longa distância e com capacidade de penetração. Tensão de alimentação 4~28VDC e saída de 3.3V',
	'DIY',
	1,
	'Paper Box 04',
	'NOT ORGANIZED',
	'Radar doppler RCWL-0516.jpg',
	'',
	''
),
(
	'GY-9250 (MPU-9250) Módulo de 9 eixos de aceleração, giroscópio e magnetômetro',
	'O módulo MPU-9250 tem 9-eixos: 3 do giroscópio (escalas de ±250, ±500, ±1000, e ±2000°/sec), 3 do acelerômetro (escalas de ±2g, ±4g, ±8g e ±16g) e 3 do magnetômetro (resolução de saída de 14 bit (0.6µT/LSB) e escala completa de±4800µT)',
	'DIY',
	1,
	'Paper Box 04',
	'NOT ORGANIZED',
	'GY-9250(MPU-9250)-9-axis_1.jpg;GY-9250(MPU-9250)-9-axis_2.jpg;GY-9250(MPU-9250)-9-axis_3.jpg;GY-9250(MPU-9250)-9-axis_4.jpg;GY-9250(MPU-9250)-9-axis_5.jpg',
	'PS-MPU-9250A-01.pdf;RM-MPU-9250A-00.pdf',
	'MPU9250-master.zip',
),
(
	'CM30-3015-NC - Sensor Capacitivo',
	'Sensor Capacitivo com distância de detecção de 0-15mm com saídas NPN/NO+NC e tensão de alimentação 6~36VDC.',
	'DIY',
	1,
	'Paper Box 04',
	'NOT ORGANIZED',
	'Sensor Capacitivo.jpg',
	'',
	''
),
(
	'PR12-2DP - Sensor Indutivo de Proximidade',
	'Sensor Indutivo de Proximidade PR12-2DP com distância de detecção de 0-2mm, frequência de resposta de 1.5kHz e tensão de alimentação de 12-24VDC.',
	'DIY',
	1,
	'Paper Box 04',
	'NOT ORGANIZED',
	'Sensor Indutivo de Proximidade PR12-2DP1.jpg;Sensor Indutivo de Proximidade PR12-2DP2.png',
	'',
	''
),
(
	'YF-S201 - Contador de Fluxo de água',
	'YF-S201 - Contador de Fluxo de Água usando sensor de efeito Hall. Pressão < 1.75MPa, tensão de 5~24V, acurácia = 1~60L/Min +-3%, caracteristica do pulso do fluxo = 4.8xQ, onde Q é L/Min.',
	'DIY',
	1,
	'Paper Box 04',
	'NOT ORGANIZED',
	'Contador de Fluxo de água - YF-S201.jpg',
	'',
	''
),
(
	'ISD1820 - Módulo para gravação de voz',
	'Modulo ISD1820, para gravação de voz com microfone onboard e gravação de 10s de voz. É composto de três botões (REC,PLAYE e PLAYL), microfone e alto falante.',
	'DIY',
	1,
	'Paper Box 04',
	'NOT ORGANIZED',
	'Modulo ISD1820, para gravação de voz.jpg',
	'',
	''
),
(
	'DHT21/AM2301 - Sensor de Temperatura e Umidade',
	'Sensor de Temperatura e Umidade DHT21/AM2301 com tensão de alimentação de 3~5V, umidade de 0~100%, temperatura de -40~80°C, precisão de +-3%RH/+-0.5°C com saída digital \"monobus\".',
	'DIY',
	1,
	'Paper Box 04',
	'NOT ORGANIZED',
	'Sensor de Temperatura e Umidade DHT21-AM2301_1.jpg;Sensor de Temperatura e Umidade DHT21-AM2301_2.jpg;Sensor de Temperatura e Umidade DHT21-AM2301_3.jpg',
	'',
	''
),
(
	'Motor DC com caixa de redução e eixo duplo',
	'Motor DC de 3~6V com caixa de redução (1:48) e eixo duplo. Peso de 30g, corrente sem carga <= 200mA (6V) e <= 150mA (3V) e velocidade sem carga de 200RPM (6V) e 90RPM (3V).',
	'DIY',
	1,
	'Paper Box 04',
	'NOT ORGANIZED',
	'Motor DC com caixa de redução e eixo duplo-1.jpg;Motor DC com caixa de redução e eixo duplo-2.jpg;Motor DC com caixa de redução e eixo duplo-3.jpg',
	'',
	''
),
(
	'SCT013-000 - Sensor de Corrente não Invasivo 100A',
	'Medição corrente 0~100A, corrente saída 0~50mA, acurácia ±1%, linearidade ±3%, razão espiras 1:1800, deslocamento fase ≤180º, material núcleo ferrite e frequência trabalho 50~1000Hz.',
	'DIY',
	1,
	'Paper Box 04',
	'NOT ORGANIZED',
	'Sensor de Corrente não Invasivo 100A SCT013-000.jpg',
	'',
	''
),
(
	'ELM327 OBD2 - Interface de diagnóstico',
	'Interface de diagnóstico ELM327 OBD2 versão 2.1 de conexão bluetooth.',
	'Equipment',
	1,
	'Paper Box 04',
	'NOT ORGANIZED',
	'ELM327 OBD2 - Interface de diagnóstico.jpg',
	'',
	''
),
(
	'E18-D80NK - Sensor de Proximidade Fotoelétrico Infravermelho com faixa de detecção de 3~80 cm',
	'Sensor normalmente aberto com faixa de detecção de 3~80 cm, alimentação de 5VDC, corrente de consumo < 25mA, diâmetro de 17 mm, comprimento do sensor de 45 mm, comprimento do cabo de 45 cm, tempo de resposta < 2 ms, ângulo maior que 15°.',
	'DIY',
	1,
	'Paper Box 04',
	'NOT ORGANIZED',
	'E18-D80NK - Sensor de Proximidade_1.jpg;E18-D80NK - Sensor de Proximidade_2.jpg;E18-D80NK - Sensor de Proximidade_3.jpg;E18-D80NK - Sensor de Proximidade_4.jpg;E18-D80NK - Sensor de Proximidade_5.jpg;E18-D80NK - Sensor de Proximidade_6.jpg',
	'E18-D80NK Long range adjustable IR sensor.pdf;Wiring the E18-D80NK Infrared Distance Ranging Sensor.pdf',
	''
),
(
	'Célula de Carga de 5kg',
	'Potência nominal: 1,0±0.15mV/V; Impedância entrada/saída: 1115±10%/1000±10%Ω; Resistência isolamento: 1000MΩ; Sobrecarga seguro/extrema: 150%FS/200%FS; Alimentação:3~12VDC; IP65',
	'DIY',
	2,
	'Paper Box 04',
	'NOT ORGANIZED',
	'Load_Cell_Weight_Sensor_5kg_1.jpg;Load_Cell_Weight_Sensor_5kg_2.jpg',
	'5KG resistance strain type pressure sensor.doc',
	''
),
(
	'Sensor LSON Ultrassônico 40KHz',
	'16mm ultrasonic; Water resistant; 40KHz sensor; Diameter: 16mm; Working mode: transceiver split; Transmitting sound pressure at 10V: >=110dB; Sensitivity: >=-75dB; Capacitance at 1KHz: 1800+/-30%',
	'DIY',
	4,
	'Paper Box 04',
	'NOT ORGANIZED',
	'Sensor LSON Ultrason.jpeg',
	'',
	''
),
(
	'Fonte Ajustável para Protoboard',
	'Fonte Ajustável para Protoboard (YwRobot Breadboard Power Supply) com saídas de 3.3V e 5V.',
	'DIY',
	3,
	'Paper Box 05',
	'NOT ORGANIZED',
	'Fonte Ajustável para Protoboard.jpg',
	'',
	''
),
(
	'Módulo Buck-boost para FPV com LM2587 para entrada de 3 ~ 35V para 1,2 ~ 30V 2A DC',
	'Módulo Buck-boost para FPV com LM2587 para entrada de 3 ~ 35V para 1,2 ~ 30V 2A DC.',
	'DIY',
	1,
	'Paper Box 05',
	'NOT ORGANIZED',
	'Módulo Buck-boost para FPV.png',
	'',
	''
)
(
	'Placa Amplificadora Stereo com TDA2030A',
	'Placa Amplificadora Stereo com TDA2030A com duplo canal para acesso OCL 18Wx2 ou mono BTL 36Wx1. Resistores de 1% de metal de filmes, Chemi-Con e Panasonic capacitores, 2x3300uF/25V como filtro. Tensão de entrada AC 9V-12V.',
	'DIY',
	1,
	'Paper Box 05',
	'NOT ORGANIZED',
	'Placa Amplificadora Stereo TDA2030A 2.1.jpg',
	'',
	''
),
(
	'RD084DY002 - Módulo de Recarga de Bateria de Lítio 1A',
	'Módulo de Recarga de Bateria de Lítio 1A, com LED indicador de carga. Modelo RD084DY002',
	'DIY',
	1,
	'Paper Box 05',
	'NOT ORGANIZED',
	'Módulo de Recarga de Bateria de Lítio 1A.jpg',
	'',
	''
),
(
	'Placa de Expansão GSM/GPRS FreeArduino',
	'Placa de Expansão GSM/GPRS FreeArduino usada para fazer/receber ligações, enviar/receber mensagens como também transferências de dados.',
	'DIY',
	1,
	'Paper Box 05',
	'NOT ORGANIZED',
	'Placa de Expansão GSM-GPRS FreeArduino.jpg',
	'',
	''
),
(
	'Sensor de nível de água',
	'Sensor de nível de água para ser usado no Arduino.',
	'DIY',
	1,
	'Paper Box 05',
	'NOT ORGANIZED',
	'Sensor de nível de água.jpg',
	'',
	''
),
(
	'Válvula Elétrica Solenoide para água e ar',
	'Válvula Elétrica Solenoide para água e ar NO e NC com tensão de alimentação de 12V com 0.5in normalmente fechada.',
	'DIY',
	1,
	'Paper Box 05',
	'NOT ORGANIZED',
	'Válvula Elétrica Solenoide para água e ar.jpg',
	'',
	''
),
(
	'Ethernet Shield com Wiznet W5100',
	'Ethernet Shield com Wiznet W5100 para conexão a cabo para Arduino.',
	'DIY',
	1,
	'Paper Box 05',
	'NOT ORGANIZED',
	'Ethernet Shield com Wiznet W5100.jpg',
	'',
	''
),
(
	'Módulo Encoder Rotação de 360°',
	'Módulo Encoder Rotação de 360° com resolução de 20 pulsos por revolução e corrente máxima de 10mA.',
	'DIY',
	1,
	'Paper Box 05',
	'NOT ORGANIZED',
	'Módulo Encoder Rotação de 360.jpg',
	'',
	''
),
(
	'Módulo reconhecimento de impressão digital',
	'Módulo reconhecimento de impressão digital com frequência de trabalho de 433MHz,868MHz ou 915MHz. Sensibilidade de -100dBm, tensão de alimentação de 3.6~6V, tamanho dos caracteres de 256 bytes, tempo de pesquisa < 1 segundo.',
	'DIY',
	1,
	'Paper Box 05',
	'NOT ORGANIZED',
	'Modulo reconhecimento de impressão digital.jpg',
	'ZFM-20_Series_Fingerprint_Identification_Module-User_Manual.pdf;DY001fingerprint.pdf;adafruit-optical-fingerprint-sensor.pdf',
	'SFGDemoV2.0.rar;Adafruit-Fingerprint-Sensor-Library-master.zip'
),
(
	'ZHO-0420S-05A4.5 - Mini Solenóide 5V',
	'Mini Solenóide 5V com curso do eixo de aproximadamente 4,5mm, diâmetro do eixo de 1,6mm (3mm na extrimidade), corrente de alimentação de 1.1A. Modelo ZHO-0420S-05A4.5',
	'DIY',
	1,
	'Paper Box 05',
	'NOT ORGANIZED',
	'Mini Solenóide 5V.jpg',
	'',
	''
),
(
	'PCF8574 - Placa de Expansão',
	'Placa de Expansão PCF8574 no qual pode ser conectado por I2C provendo até 64 portas I/O. A placa é uma interface 8-bit paralela.',
	'DIY',
	1,
	'Paper Box 05',
	'NOT ORGANIZED',
	'Placa de Expansão PCF8574.jpg',
	'',
	''
),
(
	'DS1307 - Módulo de Real Time Clock',
	'Módulo de Real Time Clock (RTC) com memória 24C32 de 32K com comunicação I2C e chip DS1307.',
	'DIY',
	1,
	'Paper Box 05',
	'NOT ORGANIZED',
	'Módulo de Real Time Clock RTC DS1307 DS-1307 AT24C32.jpg',
	'',
	''
),
(
	'Protoshield',
	'Protoshield desenvolvido para criar shields de acordo com a necessidade do usuário com dois botões, dois leds, entradas para NOKIA 5110, LCM 1602, entre outros.',
	'DIY',
	1,
	'Paper Box 05',
	'NOT ORGANIZED',
	'protoshield-prototype-para-arduino-protoboard-170-pontos1.jpg;protoshield-prototype-para-arduino-protoboard-170-pontos2.jpg',
	'',
	''
),
(
	'Shield de Sensor 5.0',
	'Shield de Sensor no qual podem ser conectados módulo bluetooth, sdcard, display, sensores, entre outros. As dimensões são de 5.7 x 5.7 x 2 cm.',
	'DIY',
	1,
	'Paper Box 05',
	'NOT ORGANIZED',
	'Shield de Sensor 5.0.jpg',
	'',
	''
),
(
	'W908 - Ibeacon',
	'Ibeacon W908 com chip CC2541, a prova de água, uso de bateria CR2477, range efetivo de 30m e máximo de 100m e corrente de 100uA (standby).',
	'DIY',
	1,
	'Paper Box 05',
	'NOT ORGANIZED',
	'ibeacon w908.jpg;Ibeacon w908 -Bluetooth-TICC2541.jpg',
	'',
	''
),
(
	'PCW2138WC - Carregador sem fio',
	'Carregador sem fio (PCW2138WC) com entrada/saída de 5~12VDC/(5VDC/600mA), indutância da bobina de transmissão de 30uH, distância de transmissão de 1~20mm, diâmetro da bobina de 38mm e altura da bobina de 2mm.',
	'DIY',
	1,
	'Paper Box 05',
	'NOT ORGANIZED',
	'Carregador sem fio.jpg',
	'',
	''
),
(
	'HLK-RM04 - Módulo Adaptador Wi-Fi',
	'Módulo Adaptador Wi-Fi HLK-RM04 com antena onboard e externa, modo client/AP/server, com todas as funcionalidades de rede com e sem fio.',
	'DIY',
	1,
	'Paper Box 05',
	'NOT ORGANIZED',
	'Módulo Adaptador Wi-Fi HLK-RM04.jpg',
	'',
	''
),
(
	'PCF8591 - Módulo Conversor de 8-Bit A/D e D/A',
	'Módulo Conversor PCF8591 de 8-Bit A/D e D/A, tensão de 2.5~6V, 3 pinos de entrada (A0, A1 e A2) e 4 pinos de entrada analógicos programados como saída simples ou entrada diferencial.',
	'DIY',
	1,
	'Paper Box 05',
	'NOT ORGANIZED',
	'Módulo Conversor PCF8591 - 1.jpg;Módulo Conversor PCF8591 - 2.jpg;Módulo Conversor PCF8591 - 3.jpg;Módulo Conversor PCF8591 - 4.jpg',
	'',
	''
),
(
	'Módulo Transmissor/Receptor RF de 433MHz',
	'Corrente transm. máx<=40mA (12V), mín<=9mA (3V), modo ressonante/modulação SAW/(ASK/OOK), freq. trab. 315~433.92MHz, pot. trans. 25mW (315MHz,12V), erro freq. 150kHz (máx), vel. <=10kbps,  intervalo de trans. 20~200m.',
	'DIY',
	1,
	'Paper Box 05',
	'NOT ORGANIZED',
	'Modulo Transmissor-Receptor RF de 433MHz.jpg',
	'',
	''
),
(
	'Módulo Player MP3 Music com controle Serial UART',
	'Suporte a formato MP3 e WAV, controle por UART, frequência de amostragem de 8kHz~48kHz, tensão de alimentação de 3.2~5.2VDC, suporte para Micro SD (SDHC) Card <=2G (<16G).',
	'DIY',
	1,
	'Paper Box 05',
	'NOT ORGANIZED',
	'Modulo Player MP3 Music com controle Serial UART1.jpg;Modulo Player MP3 Music com controle Serial UART2.jpg',
	'',
	''
),
(
	'KY-023 - Módulo Joystick',
	'Módulo joystick PS2, no qual tem um cross rocker que é um resistor bidirecional 10K, com balancim em direções diferentes, a resistência muda com direção, fonte de alimentação 5V, estado original x, tensão de leitura Y é de cerca de 2,5V.',
	'DIY',
	1,
	'Paper Box 05',
	'NOT ORGANIZED',
	'Módulo Joystick KY-023.jpg',
	'',
	''
),
(
	'TEA5767 - Módulo Receptor FM',
	'Módulo receptor FM com suporte de frequência entre 76~108MHz usando o chip Philips TEA5767.',
	'DIY',
	1,
	'Paper Box 05',
	'NOT ORGANIZED',
	'Módulo Receptor FM TEA57671.jpg;Módulo Receptor FM TEA5767_pinout.jpg;Módulo Receptor FM TEA5767_schematictea.jpg',
	'',
	''
),
(
	'OV7670 - Módulo Camera VGA 300KP',
	'Array fotosensível 640x480, tensão IO 2.5~3.0V, formato saída YUV/YCbCr4:2:2 RGB565/555/444 GRB4:2:2 Raw RGB Data (8 digit), tamanho lente 1/6\"; ângulo visão 25 graus; taxa frame máx. 30fps VGA, sensibilidade 1.3V/(Lux-sec), sinal taxa ruído 46 dB',
	'DIY',
	1,
	'Paper Box 05',
	'NOT ORGANIZED',
	'Módulo Camera VGA 300KP OV7670.jpg',
	'',
	''
),
(
	'Joystick Escudo v1.2',
	'Um Joystick para adicição do Nokia 5110 LCD e interface de nRF24L01. Pode-se desenvolver facilmente jogos com Joystick, e até a comunicação entre si com nRF24L01 wireless. ',
	'DIY',
	1,
	'Paper Box 05',
	'NOT ORGANIZED',
	'Joystick Escudo v1.2.jpg',
	'',
	''
),
(
	'Cabo conversor IPX para RP-SMA macho',
	'Cabo conversor adaptador IPX para RP-SMA macho com comprimento de 19cm.',
	'DIY',
	1,
	'Paper Box 05',
	'NOT ORGANIZED',
	'Cabo conversor IPX para RP-SMA macho.jpg',
	'',
	''
),
(
	'Conversor Lógico Bidirecional 5V/3V',
	'Conversor nível lógico de 4 canais para Arduino, em uso de I2C.',
	'DIY',
	6,
	'Paper Box 05',
	'NOT ORGANIZED',
	'Conversor Lógico Bidirecional 5V-3V.jpg',
	'',
	''
),
(
	'A7 - Placa de Desenvolvimento GPS GPRS GSM SMS e Módulo de Voz',
	'Placa de Desenvolvimento A7 GPS GPRS GSM SMS e Módulo de Voz com tensão de alimentação de 3.3~4.2V, suporte as frequ&ecirc;ncias 850/900/1800/1900 MHz com duas antenas.',
	'DIY',
	1,
	'Paper Box 05',
	'NOT ORGANIZED',
	'Placa de Desenvolvimento A7 GPS GPRS GSM SMS e Módulo de Voz.jpg',
	'',
	''
),
(
	'ATK-NEO-6M-V12 - Módulo GPS  com antena Ulbox',
	'Taxa 4.8k/9.6k/38.4k(padrão)/57.6k; 3.3/5V sistema SCM; GPS L1 (1575.42MHZ) código C/A; SBAS:WAAS/EGNOS/MSAS; Precisão:2.5 MCEP (SBAS2.0mCEP); Inicio a frio/quente:27s (mais rápido)/1s; Sensibilidade:161dBm; Protocolo:NMEA(padrão)/UBX Binary',
	'DIY',
	1,
	'Paper Box 05',
	'NOT ORGANIZED',
	'Módulo GPS  com antena Ulbox ATK-NEO-6M-V121.jpg;Módulo GPS  com antena Ulbox ATK-NEO-6M-V122.jpg;Módulo GPS  com antena Ulbox ATK-NEO-6M-V123.jpg',
	'',
	''
),
(
	'CD74HC4067 - Placa com Multiplexador/Demultiplexador Analógico de 16 canais',
	'Multiplexador/Demultiplexador analógico com tensão de trabalho de 2~6V. Modelo CD74HC4067 de 16 canais.',
	'DIY',
	1,
	'Paper Box 05',
	'NOT ORGANIZED',
	'Placa com Multiplexador-Demultiplexador Analógico CD74HC4067 de 16 canais.jpg',
	'',
	''
),
(
	'CNC Shield V3 para impressora 3D com 4 Drivers A4988',
	'CNC Shield com tensão de 12~36VDC, botão reset, 4 eixos (X, Y, Z e A), entrada para conectores de fim de curso para cada eixo. Compatível com Arduino UNO e GRBL.',
	'DIY',
	1,
	'Paper Box 05',
	'NOT ORGANIZED',
	'CNC Shield V3 para impressora 3D com 4 Drivers A4988_1.jpg;CNC Shield V3 para impressora 3D com 4 Drivers A4988_2.jpg',
	'',
	''
),
(
	'Controle para uso em MP3',
	'Controle para uso em MP3. Uso de duas pilhas de relógio. Há 21 teclas incluindo turn on/off, mode, play e pause, mute, entre outros.',
	'Equipamento',
	1,
	'Paper Box 05',
	'NOT ORGANIZED',
	'Controle para uso em MP3.jpg',
	'',
	''
),
(
	'Módulo DRF1278F LoRa 433MHz SX1278',
	'Frequency Range: 433MHz Modulation: FSK/GFSK/MSK/LoRa SPI Data Interface Sensitivity: -136dBm Output Power: +20dBm Data Rate: <300 kbps 127dB dynamic Range RSSI Packet engine up to 256 bytes with CRC Standby current: 1uA Supply voltage: 1.8~3.6V',
	'DIY',
	2,
	'Paper Box 05',
	'NOT ORGANIZED',
	'LoRa_SX1278_433MHz_Module_DRF1278F_1.jpg;LoRa_SX1278_433MHz_Module_DRF1278F_2.jpg;LoRa_SX1278_433MHz_Module_DRF1278F_3.jpg;LoRa_SX1278_433MHz_Module_DRF1278F_4.jpg',
	'DRF1278F - 20dBm LoRa Long Range RF Front-end Module.pdf',
	''
),
(
	'Célula de Carga para balança de até 50kg',
	'Capacity:40~50 kg Error:0.05 mv/v Output Sensitivity:1.0±0.1 mv/v Nonlinearity:0.03 %FS Repeatability:0.03 %FS Hysteresis:0.03 %FS Zero Output:±0.1 mV/V Input Resistance:1000±20 Ω Insulation Resistance:≥5000 MΩ Overload Capacity:150 %FS',
	'DIY',
	1,
	'Paper Box 05',
	'NOT ORGANIZED',
	'Load Sensor - 50kg_1.jpg;Load Sensor - 50kg_2.jpg',
	'Load Sensor - 50kg.pdf',
	''
),
(
	'Módulo TTL para RS485 para Arduino',
	'Chipset MAX485; 2 pinos para comunicação e fiação fácil RS-485 Tensão de trabalho de 5V',
	'DIY',
	2,
	'Paper Box 05',
	'NOT ORGANIZED',
	'Módulo TTL para RS485 para Arduino_1.jpg;Módulo TTL para RS485 para Arduino_2.jpg;Módulo TTL para RS485 para Arduino_3.jpg',
	'',
	''
),
(
	'Módulo sem fio NRF24L01 + PA + LNA (com antena)',
	'Controlador: NRF24L01+ Frequência: 2.4GHz Tensão de operação: 1.9 à 3.6V Taxa de transferência: 2 Mbit/s Corrente em power down: 400nA Corrente em standby: 32uA Dimensões: 29 x 15mm Regulador de tensão embutido Conector para antena SMA',
	'DIY',
	2,
	'Paper Box 05',
	'NOT ORGANIZED',
	'NRF24L01 + PA + LNA (com antena)_1.jpg;NRF24L01 + PA + LNA (com antena)_2.jpg',
	'nRF24L01P_Product_Specification_1_0.pdf;nWP_011_v1.1.pdf;RF_Test_Instructions_nRF24L01P_v1_0.pdf;Tuning_the_nFR24xx_matching_network.pdf',
	'nAN24-12.zip;nRF24L01P-EK.zip'
),
(
	'Módulo SD Card',
	'LED indicador Suporte para SD Card Pinos: GND, 3.3V, 5V, CS, MOSI, SCK, MISO e GND',
	'DIY',
	1,
	'Paper Box 05',
	'NOT ORGANIZED',
	'SD_Card_Module_1.jpg;SD_Card_Module_2.jpg;SD_Card_Module_Pin_Outs.png',
	'SDCard Module_schematic.pdf;Micro SD Data Sheet.pdf;SDCard Datasheet  SDCard V 1.2.pdf',
	''
),
(
	'Conversor Digital para Analógico de 12Bits com memória EEPROM',
	'O módulo CJMCU-MCP4725 é um conversor DAC (Digital-to-Analog Converter) controlado por I2C. Caracteristicas: resolução de 12bits Interface I2C (suportados os modos Standard, Fast, e High-Speed) Alimentção de 2.7~5.5V',
	'DIY',
	1,
	'Paper Box 05',
	'NOT ORGANIZED',
	'MCP4725_1.png;MCP4725_2.jpg;MCP4725_3.jpg',
	'MCP4725.pdf',
	''
),
(
	'X9C103S - Potenciômetro 10kΩ controlado digitalmente',
	'Potenciômetro controlado digitalmente com resistência de 10k Ohms, com 99 posições e com tensão de alimentação entre 3V à 5V. Corrente máx. ativa de 3mA. Corrente máx. standby de 750µA. Duração de 100000 trocas de dados por bit.',
	'DIY',
	3,
	'Paper Box 05',
	'NOT ORGANIZED',
	'x9c103s_digital_potentiometer_module_2.jpg;x9c103s_digital_potentiometer_module_1.jpg;Potenciômetro Digital X9C103S_1.jpg;Potenciômetro Digital X9C103S_2.jpg;Potenciômetro Digital X9C103S_3.jpg;Potenciômetro Digital X9C103S_4.jpg',
	'X9C102, X9C103, X9C104, X9C503 - Digitally Controlled Potentiometer.pdf',
	''
),
(
	'Conversor RS232 para TTL',
	'Transceiver : 2 (1 TTL -> RS232 + 1 TTL <- RS232) Operating Voltage:3 V ~ 5.5 V Maximum Datarate: 120 kbps Operation: Full Duplex Protocol: RS232 Receiver Hysteresis: 300mV Temperature range: -40°C ~ 85°C Size: 10mm x 15mm'
	'DIY',
	3,
	'Paper Box 05',
	'NOT ORGANIZED',
	'Mini_RS232_to_TTL_Converter_1.jpg;Mini_RS232_to_TTL_Converter_2.jpg',
	'MAX3222, MAX3232, MAX3237, MAX3241 - 3.0V to 5.5V, Low-Power, up to 1Mbps, True RS-232 Transceivers Using Four 0.1µF External Capacitors.pdf',
	''
),
(
	'SSR-25 DA - Relé de Estado Sólido',
	'Relé de Estado Sólido para 25A de corrente de trabalho, tensão de entrada de 3~32VDC, tensão ON (>2.4V) e OFF (<1.0V), corrente de trigger de 7.5mA/12V, método de controle dado por \"Zero Cross Trigger\", tensão de trabalho 24~380VAC.'
	'DIY',
	1,
	'Paper Box 06',
	'NOT ORGANIZED',
	'Rele de Estado Solido SSR-25 DA.jpg',
	'',
	''
),
(
	'L298N - Módulo para constrole de motores DC'
	'Tensão operação 5~35V (4~35V), controle p/ 2 motores DC ou 1 motor passo, corrente máxima 2A por canal ou 4A máxima, tensão lógica 4.5~5.5V (HIGH)/0V (LOW), corrente lógica 0~36mA, potência máxima de 20W (25W).',
	'DIY',
	2,
	'Paper Box 06',
	'NOT ORGANIZED',
	'Modulo L298N.jpg;Modulo L298N_description.jpg',
	'',
	''
),
(
	'Módulo Relé - 1 relé',
	'Suporte a sinal TTL de 3.3V ou 5V, consumo de 5V e 75mA, LED indicador ON, chaveamento de 10A/250VAC.',
	'DIY',
	1,
	'Paper Box 06',
	'NOT ORGANIZED',
	'Modulo Relay 1 relay.jpg'
	'Songle Relay - SRD.pdf',
	''
),
(
	'MG995 - Servo Motor Pro Tower',
	'Velocidade s/ carga:0.17s/60º (4.8V)0.13s/60º (6.0V); Limite de entrada: 6~20V; VCC: 3.0V~7.2V/100mA; Torque:13kg/cm 6.0V; Vel. Rotação: 53-62RPM; Temperatura trabalho: -30~+6ºC; Zona ruim:4 μs; Angulo max: 180º',
	'DIY',
	1,
	'Paper Box 06',
	'NOT ORGANIZED',
	'Servo Motor Pro Tower MG9951.jpg;Servo Motor Pro Tower MG9952.jpg;Servo Motor Pro Tower MG9953.jpg;Servo Motor Pro Tower MG9954.jpg',
	'',
	''
),
(
	'Controle JVC RM-RK50',
	'Controle JVC RM-RK-50 com 9 botões e uso de bateria CR2025.',
	'DIY',
	1,
	'Paper Box 06',
	'NOT ORGANIZED',
	'Controle JVC RM-RK50 (P14-Infrared module).jpg',
	'',
	''
),
(
	'Lanterna de LED infravermelho para Raspberry Pi',
	'Lanterna de LED infravermelho com LED infravermelho 850 de 1W para raspicam. A placa tem photoresistor, e trabalha com 3.3V.',
	'LED',
	2,
	'Paper Box 06',
	'NOT ORGANIZED',
	'Lanterna de LED Raspberry Pi_1.jpg;Lanterna de LED Raspberry Pi_2.jpg;Lanterna de LED Raspberry Pi_3.jpg;Lanterna de LED Raspberry Pi_4.jpg',
	'',
	''
),
(
	'Módulo receptor infravermelho',
	'Módulo receptor infravermelho P14 tipo NEC (HX1838) com tensão de alimentação de 3.3V-5V e saída digital, distância/ângulo de 18m/-+45 graus, nível 0/1 igual a 0.4V/4.5V e frequência de portadora de 38kHz.',
	'LED',
	1,
	'Paper Box 06',
	'NOT ORGANIZED',
	'Módulo receptor infravermelho.png',
	'',
	''
),
(
	'Teclado Numérico de 16 teclas',
	'Número de teclas: 16; Durabilidade Mecânica: 1000000 ciclos; Max. resistência de contato: 200mΩ; Torque de comutação: 1N; Max. tensão de operação: 24VDC; curso da tecla: 1.2mm; Max. corrente de operação: 20mA; Largura: 65mm; Altura: 64mm',
	'DIY',
	1,
	'Paper Box 06',
	'NOT ORGANIZED',
	'teclado_numerico_16_teclas_pretas_1.jpg;teclado_numerico_16_teclas_pretas_2.jpg;teclado_numerico_16_teclas_pretas_3.jpg',
	'',
	''
),
(
	'Voltímetro Analógico 91L16',
	'Voltímetro Analógico 91L16; Medição de 0 a 300 VAC; Tamanho 40x40mm',
	'DIY',
	1,
	'Paper Box 06',
	'NOT ORGANIZED',
	'Voltímetro Analógico 91L16 0 a 300 VAC_1.jpg;Voltímetro Analógico 91L16 0 a 300 VAC_2.jpg;Voltímetro Analógico 91L16 0 a 300 VAC_3.jpg',
	'',
	''
),
(
	'Interruptor deslizante para Arduino LilyPad',
	'Interruptor para controle de ligado/desligado.',
	'DIY',
	1,
	'Paper Box 06',
	'NOT ORGANIZED',
	'Slide_Switch_AYZ0202__Arduino_LilyPad_1.png;Slide_Switch_AYZ0202__Arduino_LilyPad_2.png;Slide_Switch_AYZ0202__Arduino_LilyPad_3.png;Slide_Switch_AYZ0202__Arduino_LilyPad_4.png',
	'',
	''
),
(
	'Módulo relé com 8 canais',
	'Sinal de controle: Nível TTL; Bobina: 5VDC 75mA; Carga nominal do relê: 12A 125VAC , 7A 250VAC; Carga nominal do módulo: 10A; Tempo de acionamento de contato: 10ms; Placa de oito canais com contato NA/NF nos relés e circuitos de driver optoacoplados',
	'DIY',
	1,
	'Paper Box 06',
	'NOT ORGANIZED',	'relay_module_8ch_01.jpg;relay_module_8ch_02.jpg;relay_module_8ch_03.jpg;relay_module_8ch_04.jpg;relay_module_8ch_05.jpg;relay_module_8ch_06.jpg;relay_module_8ch_07.png',
	'8 Channel 5V Optical Isolated Relay Module.pdf;Songle Relay - SRD.pdf',
	'8_channel_relay.py;8_channel_relay_low.ino;8+Relay+Module.rar'
),
(
	'Osciloscópio Hantek 6022BE',
	'Osciloscópio Hantek 6022BE com dois canais analógicos de 20MHz com taxa de amostragem de 48MS/s, salva tela em TXT, JPG/MP, MS Excell/Word, com transformada rápida de Fourier (FFT), funçõoes matemáticas, entre outras.',
	'Equipment',
	1,
	'Office',
	'NOT ORGANIZED',
	'Hantek 6022BE_1.jpg;Hantek 6022BE_2.jpg;Hantek 6022BE_3.jpg;Hantek 6022BE_4.jpg;Hantek 6022BE_5.jpg;Hantek 6022BE_6.jpg;Hantek 6022BE_7.jpg;Hantek 6022BE_8.jpg;Hantek 6022BE_9.jpg;Hantek 6022BE_10.jpg;Hantek 6022BE_11.jpg',
	'HT6022_Manual.pdf',
	'Hantek6022BE.zip'
),
(
	'Gerador de forma de onda arbitrária DDS- 3X25 25M',
	'Com canal 12 bits saída, saída sinal sincronizada, 1 canal medida entrada de contador/frequência. Formas geradas como seno, quadrada, triangular, dente serra, TTL, ruído branco, ruído gaussiano, trapezoidal, exponencial, AM e FM.',
	'Equipment',
	1,
	'Office',
	'NOT ORGANIZED',
	'Gerador de forma de onda arbitrária DDS-3X25 25M.jpg',
	'DDS3X25_Manual.pdf',
	'DDS3X25.zip'
),
(
	'Estação de retrabalho BST-898D',
	'Estação de retrabalho SMD com temperatura de saída de 100~450ºC (ar) e 200~480ºC (solda) e tensão de entrada de 110/220 V para 50/60Hz. Potência de saída de 720W (soprador) e 40W (soldador)',
	'Equipment',
	1,
	'Office',
	'NOT ORGANIZED',
	'Estação de retrabalho BST-898D.jpg',
	'',
	''
),
(
	'Micro furadeira NEJE AH0002-3',
	'Micro furadeira NEJE AH0002-3 de aço inoxidável com comprimento de 95mm, diâmetro de 4mm, tensão de alimentação de 12~24VDC, corrente maior que 2A, rotação sem carga de 4000~12000rpm, faixa de broca de 0.3~4mm.',
	'Tool',
	1,
	'Office',
	'NOT ORGANIZED',
	'Micro furadeira NEJE AH0002-3.jpg',
	'',
	''
),
(
	'Lupa de Cabeça Profissional',
	'Super Lupa de Cabeça Profissional 2 Super Leds + 5 Lentes - MG81001-H, com possibilidade de ampliar 6 vezes além de LEDs de iluminação.',
	'Tool',
	1,
	'Office',
	'NOT ORGANIZED',
	'Lupa de Cabeça Profissional.jpg',
	'',
	''
),
(
	'Fonte de Alimentação Icel PS-5000',
	'Fonte simétrica, modos tensão/corrente constante, exatidão +-0.5%, saídas 0~30V/0~3A//0~30V/0~3A//5V/3A, ligação série (paralelo) 0~60V/0~6A (0~30V/0~6A), proteção contra curto, regulagem menor 0.01%, riple menor 0.5Vrms, alimentação 126/220V (50/60Hz).',
	'Equipment',
	1,
	'Stand',
	'NOT ORGANIZED',
	'Fonte de Alimentação Icel PS-5000.jpg',
	'PS-5000 Manual de instruções.pdf',
	''
);