/*
 * LED
 */
INSERT INTO item( name, description, category, quantity, locationBox, status, locationImage, locationDatasheet, locationAttachment ) VALUES
(	'Display Matriz de LED Vermelho',
	'Display Matriz HS-757-BS Anodo Comum Vermelho, 13x18mm.',
	'LED',
	1,
	'',
	'NOT ORGANIZED',
	'Display Matriz HS-757-BS Anodo Comum Vermelho.png;LED Dot Matrix Display 5x7 1.9mm Red Common Anode-Common Cathode  757AS-757BS.jpg',
	'',
	''),
	
(	'Módulo Diodo Laser 650nm',
	'Módulo Diodo Laser com tensão de trabalho de 5V e comprimento de onda de 650nm.',
	'LED',
	1,
	'BOX 001 POSITION 01',
	'NOT ORGANIZED',
	'650nm Laser Diode Module-sku_137473_1.jpg;650nm Laser Diode Module-sku_137473_2.jpg;650nm Laser Diode Module-sku_137473_3.jpg',
	'Laser Diode Module - 5mW 650nm 5V Red.pdf',
	''),
	
(	'Display alfanumérico D8614ASR',
	'Display alfanumérico D8614ASR de 28x20mm de cor vermelha',
	'LED',
	1,
	'BOX 001 POSITION 02',
	'NOT ORGANIZED',
	'Display alfanumérico D8614ASR_1.jpg;Display alfanumérico D8614ASR_2.png',
	'',
	''),
	
(	'Barra Gráfica 10 Led Segmentos Vermelho',
	'Barra Gráfica 10 Led Segmentos Vermelho modelo B210SR.',
	'LED',
	1,
	'BOX 001 POSITION 02',
	'NOT ORGANIZED',
	'Barra Gráfica 10 Led Segmentos Vermelho.png',
	'',
	''),
	
(	'Display 7 Segmentos HS-3191-AS',
	'Display 7 Segmentos HS-3191-AS com catodo vermelho, de dimensões 10x13mm.',
	'LED',
	3,
	'BOX 001 POSITION 02',
	'NOT ORGANIZED',
	'Display 7 Segmentos HS-3191-AS.png',
	'',
	''),
	
(	'Display 7 Segmentos CAI5011AH',
	'Display 7 Segmentos de catodo comum',
	'LED',
	1,
	'BOX 001 POSITION 03',
	'NOT ORGANIZED',
	'Display 7 Segmentos.jpg;Display 7 Segmentos.png;Display 7 Segmentos.webp',
	'GNS-5011ABx-11.pdf',
	''),
	
(	'Diodo Led 10W sem Dissipador',
	'Características: Potência: 10W; Cor: Cool White / Branco Frio; Tensão de Alimentação: 9,6~11V; Corrente: 1050mA; Fluxo Luminoso: 675 ~ 765 LM; Temperatura de Cor: 6000~7000K',
	'LED',
	1,
	'BOX 001 POSITION 04',
	'NOT ORGANIZED',
	'Diodo Led 10W sem Dissipador.png',
	'',
	''),
	
(	'Diodo Led 3W com Dissipador',
	'Diodo Led 3W com Dissipador na cor branca',
	'LED',
	1,
	'BOX 001 POSITION 04',
	'NOT ORGANIZED',
	'led-3w-com-dissipador-branco_2_1.jpg',
	'',
	''),
	
(	'Led RGB Tricolor 5mm com 4 Terminais',
	'Led RGB Tricolor 5mm com 4 Terminais com 3.000 MCD',
	'LED',
	1,
	'BOX 001 POSITION 05',
	'NOT ORGANIZED',
	'Led RGB Tricolor 5mm com 4 Terminais.png',
	'',
	''),
	
(	'Módulo KY-016 LED RGB',
	'Módulo LED RGB / marca: KEYES; módulo: KY-016; material: PCB; sinal de saída RGB; 3 cor: vermelho, verde, azul; compatível com para o projeto arduino DIY',
	'LED',
	1,
	'BOX 001 POSITION 05',
	'NOT ORGANIZED',
	'Módulo KY-016 LED RGB.png',
	'',
	''),
	
(	'PHCR359 - Chave Opto Politronic',
	'PHCR359 - Chave Opto Politronic',
	'LED',
	1,
	'BOX 001 POSITION 06',
	'NOT ORGANIZED',
	'PHCR359 - Chave Opto Politronic.png',
	'',
	''),
	
(	'Sensor Óptico Refletivo Duplo TCRT5000',
	'Sensor óptico de reflexão que possui acoplado um infravermelho (emissor) e um fototransistor (receptor). Modelo TCRT5000; Tipo do Detector: Fototransistor; Dimensões: 10.2 x 5.8 x 7mm; Tamanho de Onda Emissor: 950nm; Máxima Detecção: 25mm',
	'LED',
	1,
	'BOX 001 POSITION 06',
	'NOT ORGANIZED',
	'Sensor Óptico Refletivo Duplo TCRT5000.png',
	'',
	''),
	
(	'Led Alto Brilho Azul 5mm',
	'Led Alto Brilho Azul 5mm.',
	'LED',
	20,
	'BOX 001 POSITION 07',
	'NOT ORGANIZED',
	'Led Alto Brilho Azul 5mm.png',
	'',
	''),
	
(	'Led Alto Brilho Laranja 5mm',
	'Led Alto Brilho Laranja 5mm.',
	'LED',
	5,
	'BOX 001 POSITION 07',
	'NOT ORGANIZED',
	'Led Alto Brilho Laranja 5mm.png',
	'',
	''),
	
(	'Led Alto Brilho Roxo 10mm',
	'Led Alto Brilho Roxo 10mm com 3.000 mcd (mili candela).',
	'LED',
	1,
	'BOX 001 POSITION 09',
	'NOT ORGANIZED',
	'Led Alto Brilho Roxo 10mm.png',
	'',
	''),
	
(	'Led Alto Brilho Azul 10mm',
	'Led Alto Brilho Azul 10mm com 6.000 mcd (mili candela).',
	'LED',
	1,
	'BOX 001 POSITION 09',
	'NOT ORGANIZED',
	'Led Alto Brilho Azul 10mm.png',
	'',
	''),
	
(	'Led Alto Brilho Verde 10mm',
	'Led Alto Brilho Verde 10mm com 18.000 mcd (mili candela).',
	'LED',
	1,
	'BOX 001 POSITION 09',
	'NOT ORGANIZED',
	'Led Alto Brilho Verde 10mm.png',
	'',
	''),
	
(	'Led Alto Brilho Branco 10mm',
	'Led Alto Brilho Branco 10mm com 8.000 mcd (mili candela).',
	'LED',
	1,
	'BOX 001 POSITION 09',
	'NOT ORGANIZED',
	'Led Alto Brilho Branco 10mm.png',
	'',
	''),
	
(	'Led Alto Brilho Amarelo 10mm',
	'Led Alto Brilho Amarelo 10mm com 1.000 mcd (mili candela).',
	'LED',
	1,
	'BOX 001 POSITION 09',
	'NOT ORGANIZED',
	'Led Alto Brilho Amarelo 10mm.png',
	'',
	''),
	
(	'Led Alto Brilho Vermelho 10mm',
	'Led Alto Brilho Vermelho 10mm com 6.000 mcd (mili candela).',
	'LED',
	1,
	'BOX 001 POSITION 09',
	'NOT ORGANIZED',
	'Led Alto Brilho Vermelho 10mm.png',
	'',
	''),
	
(	'Display quadruplo D-4036-ksr e 7 segmentos',
	'Display quadruplo D-4036-ksr, catodo, 7 segmentos, vermelho, 30x15mm',
	'LED',
	1,
	'BOX 001 POSITION 09',
	'NOT ORGANIZED',
	'Display quadruplo D-4036-ksr e 7 segmentos.png',
	'D4036KSR.pdf',
	''),
	
(	'LED emissor infravermelho de 3mm',
	'LED emissor infravermelho transparente com diâmetro de 3mm, ângulo de iluminação de 45º, tensão de alimentação de 1.43~1.58V, distância de transmissão de 10m, com comprimento de onda de 940nm.',
	'LED',
	10,
	'BOX 001 POSITION 09',
	'NOT ORGANIZED',
	'LED emissor infravermelho de 3mm.png',
	'TIL32_ETC.pdf',
	''),
	
(	'GTM2088ARGB-28 - Matriz de LEDs RGB 8x8 com super brilho',
	'Matriz de LEDs RGB 8x8 com super brilho, tensão 2.3V (Red)/3.4V (Green)/3.4V (Blue) e corrente de 50mA.',
	'LED',
	1,
	'BOX 000',
	'NOT ORGANIZED',
	'LED Matrix 8x8 - Triple Color RGB common Anode Display - 5mm;Figure 1.jpg;Figure 2.jpg;Figure 3.jpg;Figure 4.jpg;Figure 5.jpg;Figure 6.jpg',
	'LED Matrix 8x8 - Triple Color RGB common Anode Display - 5mm;GTM2088ARGB-28.pdf',
	'LED Matrix 8x8 - Triple Color RGB common Anode Display - 5mm;Product Description.txt;8×32 Scrolling LED Message Display.zip'),
	
(	'Módulo LED RGB para Arduino',
	'Módulo 5050 (JY-MCU) LED RGB SMD de três cores para Arduino, podendo obter cores diferentes usando PWM.',
	'LED',
	1,
	'BOX 000',
	'NOT ORGANIZED',
	'SMD 5050 RGB LED Module;Figure 1.png',
	'SMD 5050 RGB LED Module;5050LED.pdf',
	'SMD 5050 RGB LED Module;3 Color RGB LED Module - Summerfuel Robotics.pdf'),
	
(	'Lanterna de LED infravermelho para Raspberry Pi',
	'Lanterna de LED infravermelho com LED infravermelho 850 de 1W para raspicam. A placa tem photoresistor, e trabalha com 3.3V.',
	'LED',
	2,
	'PAPER BOX 06',
	'NOT ORGANIZED',
	'Lanterna de LED Raspberry Pi_1.jpg;Lanterna de LED Raspberry Pi_2.jpg;Lanterna de LED Raspberry Pi_3.jpg;Lanterna de LED Raspberry Pi_4.jpg',
	'',
	''),
	
(	'Módulo receptor infravermelho',
	'Módulo receptor infravermelho P14 tipo NEC (HX1838) com tensão de alimentação de 3.3V-5V e saída digital, distância/ângulo de 18m/-+45 graus, nível 0/1 igual a 0.4V/4.5V e frequência de portadora de 38kHz.',
	'LED',
	1,
	'PAPER BOX 06',
	'NOT ORGANIZED',
	'Módulo receptor infravermelho.png',
	'',
	'')
;