/*
 * Connector
 */
INSERT INTO item( name, description, category, quantity, locationBox, status, locationImage, locationDatasheet, locationAttachment ) VALUES
(	'Jack Adaptador para Telefone RJ11 2X6P4C Fêmea 6P4C',
	'1 Macho x 2 Femeas RJ11 - Une dois telefones em uma única linha; Acoplador telefônico 1Macho x 2Femea é usado em tomadas telefônicas para uso extensão; Tipo de conexão: RJ11; Pode ser utilizada em qualquer aparelho telefônico; Cor: Bege',
	'Connector',
	1,
	'BOX 003 POSITION 01',
	'NOT ORGANIZED',
	'Jack Adaptador para Telefone RJ11 2X6P4C Femea 6P4C;Figure1.jpg',
	'',
	''),
	
(	'Plug Modular para Conector RJ11 - 6P4C',
	'Plug Modular para Conector RJ11 - 6P4C',
	'Connector',
	4,
	'BOX 003 POSITION 01',
	'NOT ORGANIZED',
	'Plug Modular para Conector RJ11 - 6P4C;Figure1.jpg',
	'',
	''),
	
(	'Plug modular para RJ11 4P4C, YH003 top',
	'Plug modular para RJ11 4P4C, YH003 top',
	'Connector',
	4,
	'BOX 003 POSITION 01',
	'NOT ORGANIZED',
	'Plug modular para RJ11 4P4C, YH003 top;Figure1.jpg',
	'',
	''),
	
(	'Plug Modular para conector RJ11 YH002 - 4P4C',
	'Plug Modular para conector RJ11 YH002 - 4P4C',
	'Connector',
	4,
	'BOX 003 POSITION 01',
	'NOT ORGANIZED',
	'Plug Modular para conector RJ11 YH002 - 4P4C;Figure1.jpg',
	'',
	''),
	
(	'Jack RJ11 YH55-04 6P4C 90°',
	'Jack RJ11 YH55-04 6P4C 90°; Cor Bege',
	'Connector',
	2,
	'BOX 003 POSITION 01',
	'NOT ORGANIZED',
	'Jack RJ11 YH55-04 6P4C 90deg;Figure1.jpg',
	'',
	''),
	
(	'Conector RJ45 Femea Multilan CAT.5E - Furukawa',
	'Suporta IEEE 802.3, 1000 BASE T, 1000 BASE TX, EIA/TIA-854, ANSI-EIA/TIA-862, ATM, Vídeo, Sistemas de Automação Predial e todos os protocolos LAN anteriores. Altura 22,7 mm, Largura 18,3 mm, Peso 0,012kg, Contato Elétrico: (1,27 mm) de ouro e 100 min',
	'Connector',
	1,
	'BOX 003 POSITION 02',
	'NOT ORGANIZED',
	'Conector RJ45 Femea Multilan CAT 5E - Furukawa;Figure1.jpg',
	'',
	''),
	
(	'Plug Modular para Conector RJ45 8P8CS-HALF 8 Vias',
	'Plug Modular para Conector RJ45 8P8CS-HALF 8 Vias',
	'Connector',
	3,
	'BOX 003 POSITION 02',
	'NOT ORGANIZED',
	'Plug Modular para Conector RJ45 8P8CS-HALF 8 Vias;Figure1.jpg',
	'',
	''),
	
(	'Plug Modular para Conector RJ45 8P8C - 8 Vias',
	'Plug Modular para Conector RJ45 8P8C - 8 Vias',
	'Connector',
	2,
	'BOX 003 POSITION 02',
	'NOT ORGANIZED',
	'Plug Modular para Conector RJ45 8P8C - 8 Vias;Figure1.jpg',
	'',
	''),
	
(	'Conector USB03 Fêmea - para Circuito Impresso 90°',
	'Conector USB03 Fêmea - para Circuito Impresso 90°',
	'Connector',
	2,
	'BOX 003 POSITION 03',
	'NOT ORGANIZED',
	'Conector USB03 Femea - para Circuito Impresso 90deg;Figure1.jpg',
	'',
	''),
	
(	'Conector YH-USB-01A fêmea, para pci 180º',
	'Conector YH-USB-01A fêmea, para pci 180º',
	'Connector',
	3,
	'BOX 003 POSITION 03',
	'NOT ORGANIZED',
	'Conector YH-USB-01A femea, para pci 180deg;Figure1.jpg',
	'',
	''),
	
(	'Conector USB05A Macho para Circuito Impresso 180°',
	'Conector USB05A Macho para Circuito Impresso 180°',
	'Connector',
	2,
	'BOX 003 POSITION 03',
	'NOT ORGANIZED',
	'Conector USB05A Macho para Circuito Impresso 180deg;Figure1.jpg',
	'',
	''),
	
(	'Conector USB06 Tipo Solda Macho DS-1107',
	'Conector USB06 Tipo Solda Macho DS-1107',
	'Connector',
	4,
	'BOX 003 POSITION 03',
	'NOT ORGANIZED',
	'Conector USB06 Tipo Solda Macho DS-1107;Figure1.jpg',
	'',
	''),
	
(	'Conector F Macho RCF Compressão RG59/U',
	'Conector F Macho RCF Compressão RG59/U',
	'Connector',
	5,
	'BOX 003 POSITION 04',
	'NOT ORGANIZED',
	'Conector F Macho RCF Compressao RG59-U;Figure1.jpg',
	'',
	''),
	
(	'Conector Antenar para Cabo Coaxial RG59 com Anel',
	'Conector Antenar para Cabo Coaxial com Anel. Conector F Coaxial para cabo RG59 possui anel de crimpagem (requer alicate de crimpar). Para Montagens de Cabo para TV parabólica. sistemas CFTV, etc.',
	'Connector',
	6,
	'BOX 003 POSITION 04',
	'NOT ORGANIZED',
	'Conector Antenar para Cabo Coaxial com Anel;Figure1.jpg',
	'',
	''),
	
(	'Conector F Macho com Rosca para RG59',
	'Conector F Macho com Rosca para RG59',
	'Connector',
	3,
	'BOX 003 POSITION 04',
	'NOT ORGANIZED',
	'Conector F Macho com Rosca para RG59;Figure1.gif',
	'',
	''),
	
(	'Terminal CRIMPLINK Tubular IS0-15008D-3 1,5mm - Preto',
	'Terminal CRIMPLINK Tubular IS0-15008D-3 1,5mm - Preto',
	'Connector',
	14,
	'BOX 003 POSITION 05',
	'NOT ORGANIZED',
	'Terminal CRIMPLINK Tubular IS0-15008D-3 1,5mm - Preto;Figure1.jpg',
	'',
	''),
	
(	'Terminal CRIMPLINK Tubular IS0-10008D-3 1,0mm - Vermelho',
	'Terminal CRIMPLINK Tubular IS0-10008D-3 1,0mm - Vermelho',
	'Connector',
	5,
	'BOX 003 POSITION 05',
	'NOT ORGANIZED',
	'Terminal CRIMPLINK Tubular IS0-10008D-3 1,0mm - Vermelho;Figure1.jpg',
	'',
	''),
	
(	'Conector BNC Macho para Crimpar RGC58',
	'Conector BNC Macho para Crimpar RGC58',
	'Connector',
	2,
	'BOX 003 POSITION 06',
	'NOT ORGANIZED',
	'Conector BNC Macho para Crimpar RGC58;Figure1.jpg',
	'',
	''),
	
(	'Conector Emenda T BNC',
	'Conector Emenda T BNC',
	'Connector',
	2,
	'BOX 003 POSITION 06',
	'NOT ORGANIZED',
	'Conector Emenda T BNC;Figure1.jpg',
	'',
	''),
	
(	'Pino Banana PB121 com derivação lateral - preto',
	'Pino Banana PB121 com derivação lateral - preto',
	'Connector',
	2,
	'BOX 003 POSITION 06',
	'NOT ORGANIZED',
	'Pino Banana PB121 com derivacao lateral - preto;Figure1.jpg',
	'',
	''),
	
(	'Pino Banana PB121 com derivação lateral - vermelho',
	'Pino Banana PB121 com derivação lateral - vermelho',
	'Connector',
	2,
	'BOX 003 POSITION 06',
	'NOT ORGANIZED',
	'Pino Banana PB121 com derivacao lateral - vermelho;Figure1.jpg',
	'',
	''),
	
(	'Pino Banana PB121 com derivação lateral – verde',
	'Pino Banana PB121 com derivação lateral – verde',
	'Connector',
	4,
	'BOX 003 POSITION 06',
	'NOT ORGANIZED',
	'Pino Banana PB121 com derivacao lateral - verde;Figure1.jpg',
	'',
	''),
	
(	'Pino Banana Macho CN 175 – Amarelo',
	'Pino Banana Macho CN 175 – Amarelo',
	'Connector',
	1,
	'BOX 003 POSITION 06',
	'NOT ORGANIZED',
	'Pino Banana Macho CN 175 - Amarelo;Figure1.jpg',
	'',
	''),
	
(	'Pino Banana Macho CN-0919 – Verde',
	'Pino Banana Macho CN-0919 – Verde',
	'Connector',
	1,
	'BOX 003 POSITION 06',
	'NOT ORGANIZED',
	'Pino Banana Macho CN-0919 - Verde;Figure1.jpg',
	'',
	''),
	
(	'Pino Banana Macho CN-0921 – Azul',
	'Pino Banana Macho CN-0921 – Azul',
	'Connector',
	1,
	'BOX 003 POSITION 06',
	'NOT ORGANIZED',
	'Pino Banana Macho CN-0921 - Azul;Figure1.jpg',
	'',
	''),
	
(	'Borne Fêmea 2EDGK-0,5 5 Vias - Espaçamento 5,08mm',
	'Borne Fêmea 2EDGK-0,5 5 Vias - Espaçamento 5,08mm',
	'Connector',
	1,
	'BOX 004 POSITION 04',
	'NOT ORGANIZED',
	'Borne Femea 2EDGK-0,5 5 Vias - Espacamento 5,08mm;Figure1.jpg',
	'',
	''),
	
(	'Borne Macho 90° 2EDGRC-0,5 5 Vias - Espaçamento 5,08mm',
	'Borne Macho 90° 2EDGRC-0,5 5 Vias - Espaçamento 5,08mm',
	'Connector',
	1,
	'BOX 004 POSITION 04',
	'NOT ORGANIZED',
	'Borne Macho 90deg 2EDGRC-0,5 5 Vias - Espacamento 5,08mm;Figure1.jpg',
	'',
	''),
	
(	'Borne PCI KRE 2T, Azul - Espaçamento 5,08mm',
	'Borne PCI KRE 2T, Azul - Espaçamento 5,08mm',
	'Connector',
	5,
	'BOX 004 POSITION 04',
	'NOT ORGANIZED',
	'Borne PCI KRE 2T, Azul - Espacamento 5,08mm;Figure1.jpg',
	'',
	''),
	
(	'Borne PCI KRE 3T Azul - Espaçamento 5,08mm',
	'Borne PCI KRE 3T Azul - Espaçamento 5,08mm',
	'Connector',
	3,
	'BOX 004 POSITION 04',
	'NOT ORGANIZED',
	'Borne PCI KRE 3T Azul - Espacamento 5,08mm;Figure1.jpg',
	'',
	''),
	
(	'Terminal CRIMPLINK Forquilha FV-15 M5-3 1,5mm – Vermelho',
	'Terminal CRIMPLINK Forquilha FV-15 M5-3 1,5mm – Vermelho',
	'Connector',
	5,
	'BOX 004 POSITION 05',
	'NOT ORGANIZED',
	'Terminal CRIMPLINK Forquilha FV-15 M5-3 1,5mm - Vermelho;Figure1.jpg',
	'',
	''),
	
(	'Terminal CRIMPLINK Olhal OB-25 M4-3 2,5mm – Azul',
	'Terminal CRIMPLINK Olhal OB-25 M4-3 2,5mm – Azul',
	'Connector',
	6,
	'BOX 004 POSITION 05',
	'NOT ORGANIZED',
	'Terminal CRIMPLINK Olhal OB-25 M4-3 2,5mm - Azul;Figure1.jpg',
	'',
	''),
	
(	'Terminal Faston FDD pré isolado – Vermelho',
	'Terminal Faston FDD pré isolado – Vermelho',
	'Connector',
	1,
	'BOX 004 POSITION 05',
	'NOT ORGANIZED',
	'Terminal Faston FDD pre isolado - Vermelho;Figure1.jpg',
	'',
	''),
	
(	'Conector Adaptador Mini HDMI Macho x HDMI Fêmea',
	'Conector Adaptador Mini HDMI Macho x HDMI Fêmea',
	'Connector',
	1,
	'BOX 004 POSITION 06',
	'NOT ORGANIZED',
	'Conector Adaptador Mini HDMI Macho x HDMI Femea;Figure1.jpg',
	'',
	''),
	
(	'Plug P4-DC sem Rabicho',
	'Plug P4-DC sem Rabicho',
	'Connector',
	1,
	'BOX 005 POSITION 01',
	'NOT ORGANIZED',
	'Plug P4-DC sem Rabicho;Figure1.gif',
	'',
	''),
	
(	'Plug P4-DC com Rabicho',
	'Plug P4-DC com Rabicho',
	'Connector',
	1,
	'BOX 005 POSITION 01',
	'NOT ORGANIZED',
	'Plug P4-DC com Rabicho;Figure1.gif',
	'',
	''),
	
(	'Jack J2 Estéreo PCI Rosca',
	'Jack J2 Estéreo PCI Rosca',
	'Connector',
	1,
	'BOX 005 POSITION 05',
	'NOT ORGANIZED',
	'Jack J2 Estereo PCI Rosca;Figure1.jpg',
	'',
	''),
	
(	'16pin OBD 2 Connector Female Plug',
	'Power: 24W; Item Height: 1cm; Brand Name: K KWOKKER; Voltage: 12V; Model Name: bmw obd2 connector female angle; Item Width: 1cm; Material Type: Plastic; Item Weight: 50g',
	'Connector',
	1,
	'BOX 005 POSITION 05',
	'NOT ORGANIZED',
	'16pin OBD2 Connector Female Plug;Fig1.webp;Fig2.jpg;Fig3.jpg;Fig4.webp;Fig5.jpg;Fig6.webp;Fig7.jpg;Fig8.jpg;Fig9.jpg;Fig10.jpg;Fig11.jpg;Fig12.jpg;Fig13.jpg;Fig14.jpg;Fig15.jpg;Fig16.jpg;Fig17.jpg;Fig18.jpg;Fig19.jpg;Fig20.jpg;Fig21.jpg',
	'',
	''),

(	'16pin OBD2 J1962 Connector Male Plug',
	'OBD2 Standard Male Connector OBD 2/OBD II/EOBD 2/J1962; pin Signal description: (2) J1850 Bus+, (4) CGND Chassis ground, (5) SGND Signal ground, (6) can high j 2285, (7) K-LINE (ISO 9141-2 and ISO/DIS 14230-4), (10) J1850 Bus-, (14) CAN Low J-2284, (15) ISO 9141-2 L-LINE (ISO 9141-2 and ISO/DIS 14230-4), (16) +12v Battery power',
	'Connector',
	1,
	'BOX 005 POSITION 05',
	'NOT ORGANIZED',
	'16pin OBD2 J1962 Connector Male Plug;Figure1.jpg;Figure2.jpg;Figure3.jpg;Figure4.jpg;Figure5.jpg;Figure6.jpg',
	'',
	''),
	
(	'Micro USB Female to DIP Adapter with 5 pin',
	'Micro USB Female to DIP Adapter with 5pin Connector in PCB',
	'Connector',
	5,
	'BOX 005 POSITION 05',
	'NOT ORGANIZED',
	'Micro USB Female Connector Adapter;Figure1.jpg',
	'',
	''),
	
(	'Mini USB Female to DIP Adapter with 5 pin',
	'Mini USB Female to DIP Adapter with 5pin Connector in PCB',
	'Connector',
	1,
	'BOX 005 POSITION 05',
	'NOT ORGANIZED',
	'Mini USB Female Connector Adapter;Figure1.jpg;Figure2.jpg',
	'',
	'')
;