/*
 * Connector
 */
INSERT INTO item( name, description, category, quantity, locationBox, status, locationImage, locationDatasheet, locationAttachment ) VALUES
(	'Jack Adaptador para Telefone RJ11 2X6P4C Fêmea 6P4C',
	'1 Macho x 2 Femeas RJ11 - Une dois telefones em uma única linha; Acoplador telefônico 1Macho x 2Femea é usado em tomadas telefônicas para uso extensão; Tipo de conexão: RJ11; Pode ser utilizada em qualquer aparelho telefônico; Cor: Bege',
	'Conector',
	1,
	'BOX. 003 POSITION 01',
	'NOT ORGANIZED',
	'Jack Adaptador para Telefone RJ11 2X6P4C Fêmea 6P4C;Figure1.jpg',
	'',
	''),
	
(	'Plug Modular para Conector RJ11 - 6P4C',
	'Plug Modular para Conector RJ11 - 6P4C',
	'Conector',
	4,
	'BOX. 003 POSITION 01',
	'NOT ORGANIZED',
	'Plug Modular para Conector RJ11 - 6P4C;Figure1.jpg',
	'',
	''),
	
(	'Plug modular para RJ11 4P4C, YH003 top',
	'Plug modular para RJ11 4P4C, YH003 top',
	'Conector',
	4,
	'BOX. 003 POSITION 01',
	'NOT ORGANIZED',
	'Plug modular para RJ11 4P4C, YH003 top;Figure1.jpg',
	'',
	''),
	
(	'Plug Modular para conector RJ11 YH002 - 4P4C',
	'Plug Modular para conector RJ11 YH002 - 4P4C',
	'Conector',
	4,
	'BOX. 003 POSITION 01',
	'NOT ORGANIZED',
	'Plug Modular para conector RJ11 YH002 - 4P4C;Figure1.jpg',
	'',
	''),
	
(	'Jack RJ11 YH55-04 6P4C 90°',
	'Jack RJ11 YH55-04 6P4C 90°; Cor Bege',
	'Conector',
	2,
	'BOX. 003 POSITION 01',
	'NOT ORGANIZED',
	'Jack RJ11 YH55-04 6P4C 90°;Figure1.jpg',
	'',
	''),
	
(	'Conector RJ45 Femea Multilan CAT.5E - Furukawa',
	'Suporta IEEE 802.3, 1000 BASE T, 1000 BASE TX, EIA/TIA-854, ANSI-EIA/TIA-862, ATM, Vídeo, Sistemas de Automação Predial e todos os protocolos LAN anteriores. Altura 22,7 mm, Largura 18,3 mm, Peso 0,012kg, Contato Elétrico: (1,27 mm) de ouro e 100 min',
	'Conector',
	1,
	'BOX. 003 POSITION 02',
	'NOT ORGANIZED',
	'Conector RJ45 Femea Multilan CAT.5E - Furukawa;Figure1.jpg',
	'',
	''),
	
(	'Plug Modular para Conector RJ45 8P8CS-HALF 8 Vias',
	'Plug Modular para Conector RJ45 8P8CS-HALF 8 Vias',
	'Conector',
	3,
	'BOX. 003 POSITION 02',
	'NOT ORGANIZED',
	'Plug Modular para Conector RJ45 8P8CS-HALF 8 Vias;Figure1.jpg',
	'',
	''),
	
(	'Plug Modular para Conector RJ45 8P8C - 8 Vias',
	'Plug Modular para Conector RJ45 8P8C - 8 Vias',
	'Conector',
	2,
	'BOX. 003 POSITION 02',
	'NOT ORGANIZED',
	'Plug Modular para Conector RJ45 8P8C - 8 Vias;Figure1.jpg',
	'',
	''),
	
(	'Conector USB03 Fêmea - para Circuito Impresso 90°',
	'Conector USB03 Fêmea - para Circuito Impresso 90°',
	'Conector',
	2,
	'BOX. 003 POSITION 03',
	'NOT ORGANIZED',
	'Conector USB03 Fêmea - para Circuito Impresso 90°;Figure1.jpg',
	'',
	''),
	
(	'Conector YH-USB-01A fêmea, para pci 180º',
	'Conector YH-USB-01A fêmea, para pci 180º',
	'Conector',
	3,
	'BOX. 003 POSITION 03',
	'NOT ORGANIZED',
	'Conector YH-USB-01A fêmea, para pci 180º;Figure1.jpg',
	'',
	''),
	
(	'Conector USB05A Macho para Circuito Impresso 180°',
	'Conector USB05A Macho para Circuito Impresso 180°',
	'Conector',
	2,
	'BOX. 003 POSITION 03',
	'NOT ORGANIZED',
	'Conector USB05A Macho para Circuito Impresso 180°;Figure1.jpg',
	'',
	''),
	
(	'Conector USB06 Tipo Solda Macho DS-1107',
	'Conector USB06 Tipo Solda Macho DS-1107',
	'Conector',
	4,
	'BOX. 003 POSITION 03',
	'NOT ORGANIZED',
	'Conector USB06 Tipo Solda Macho DS-1107;Figure1.jpg',
	'',
	''),
	
(	'Conector F Macho RCF Compressão RG59/U',
	'Conector F Macho RCF Compressão RG59/U',
	'Conector',
	5,
	'BOX. 003 POSITION 04',
	'NOT ORGANIZED',
	'Conector F Macho RCF Compressão RG59-U;Figure1.jpg',
	'',
	''),
	
(	'Conector Antenar para Cabo Coaxial RG59 com Anel',
	'Conector Antenar para Cabo Coaxial com Anel. Conector F Coaxial para cabo RG59 possui anel de crimpagem (requer alicate de crimpar). Para Montagens de Cabo para TV parabólica. sistemas CFTV, etc.',
	'Conector',
	6,
	'BOX. 003 POSITION 04',
	'NOT ORGANIZED',
	'Conector Antenar para Cabo Coaxial com Anel;Figure1.jpg',
	'',
	''),
	
(	'Conector F Macho com Rosca para RG59',
	'Conector F Macho com Rosca para RG59',
	'Conector',
	3,
	'BOX. 003 POSITION 04',
	'NOT ORGANIZED',
	'Conector F Macho com Rosca para RG59;Figure1.gif',
	'',
	''),
	
(	'Terminal CRIMPLINK Tubular IS0-15008D-3 1,5mm - Preto',
	'Terminal CRIMPLINK Tubular IS0-15008D-3 1,5mm - Preto',
	'Conector',
	14,
	'BOX. 003 POSITION 05',
	'NOT ORGANIZED',
	'Terminal CRIMPLINK Tubular IS0-15008D-3 1,5mm - Preto;Figure1.jpg',
	'',
	''),
	
(	'Terminal CRIMPLINK Tubular IS0-10008D-3 1,0mm - Vermelho',
	'Terminal CRIMPLINK Tubular IS0-10008D-3 1,0mm - Vermelho',
	'Conector',
	5,
	'BOX. 003 POSITION 05',
	'NOT ORGANIZED',
	'Terminal CRIMPLINK Tubular IS0-10008D-3 1,0mm - Vermelho;Figure1.jpg',
	'',
	''),
	
(	'Conector BNC Macho para Crimpar RGC58',
	'Conector BNC Macho para Crimpar RGC58',
	'Conector',
	2,
	'BOX. 003 POSITION 06',
	'NOT ORGANIZED',
	'Conector BNC Macho para Crimpar RGC58;Figure1.jpg',
	'',
	''),
	
(	'Conector Emenda T BNC',
	'Conector Emenda T BNC',
	'Conector',
	2,
	'BOX. 003 POSITION 06',
	'NOT ORGANIZED',
	'Conector Emenda T BNC;Figure1.jpg',
	'',
	''),
	
(	'Pino Banana PB121 com derivação lateral – preto',
	'Pino Banana PB121 com derivação lateral – preto',
	'Conector',
	2,
	'BOX. 003 POSITION 06',
	'NOT ORGANIZED',
	'Pino Banana PB121 com derivação lateral – preto;Figure1.jpg',
	'',
	''),
	
(	'Pino Banana PB121 com derivação lateral – vermelho',
	'Pino Banana PB121 com derivação lateral - vermelho',
	'Conector',
	2,
	'BOX. 003 POSITION 06',
	'NOT ORGANIZED',
	'Pino Banana PB121 com derivação lateral – vermelho;Figure1.jpg',
	'',
	''),
	
(	'Pino Banana PB121 com derivação lateral – verde',
	'Pino Banana PB121 com derivação lateral – verde',
	'Conector',
	4,
	'BOX. 003 POSITION 06',
	'NOT ORGANIZED',
	'Pino Banana PB121 com derivação lateral – verde;Figure1.jpg',
	'',
	''),
	
(	'Pino Banana Macho CN 175 – Amarelo',
	'Pino Banana Macho CN 175 – Amarelo',
	'Conector',
	1,
	'BOX. 003 POSITION 06',
	'NOT ORGANIZED',
	'Pino Banana Macho CN 175 – Amarelo;Figure1.jpg',
	'',
	''),
	
(	'Pino Banana Macho CN-0919 – Verde',
	'Pino Banana Macho CN-0919 – Verde',
	'Conector',
	1,
	'BOX. 003 POSITION 06',
	'NOT ORGANIZED',
	'Pino Banana Macho CN-0919 – Verde;Figure1.jpg',
	'',
	''),
	
(	'Pino Banana Macho CN-0921 – Azul',
	'Pino Banana Macho CN-0921 – Azul',
	'Conector',
	1,
	'BOX. 003 POSITION 06',
	'NOT ORGANIZED',
	'Pino Banana Macho CN-0921 – Azul;Figure1.jpg',
	'',
	''),
	
(	'Borne Fêmea 2EDGK-0,5 5 Vias - Espaçamento 5,08mm',
	'Borne Fêmea 2EDGK-0,5 5 Vias - Espaçamento 5,08mm',
	'Conector',
	1,
	'BOX. 004 POSITION 04',
	'NOT ORGANIZED',
	'Borne Fêmea 2EDGK-0,5 5 Vias - Espaçamento 5,08mm;Figure1.jpg',
	'',
	''),
	
(	'Borne Macho 90° 2EDGRC-0,5 5 Vias - Espaçamento 5,08mm',
	'Borne Macho 90° 2EDGRC-0,5 5 Vias - Espaçamento 5,08mm',
	'Conector',
	1,
	'BOX. 004 POSITION 04',
	'NOT ORGANIZED',
	'Borne Macho 90° 2EDGRC-0,5 5 Vias - Espaçamento 5,08mm;Figure1.jpg',
	'',
	''),
	
(	'Borne PCI KRE 2T, Azul - Espaçamento 5,08mm',
	'Borne PCI KRE 2T, Azul - Espaçamento 5,08mm',
	'Conector',
	5,
	'BOX. 004 POSITION 04',
	'NOT ORGANIZED',
	'Borne PCI KRE 2T, Azul - Espaçamento 5,08mm;Figure1.jpg',
	'',
	''),
	
(	'Borne PCI KRE 3T Azul - Espaçamento 5,08mm',
	'Borne PCI KRE 3T Azul - Espaçamento 5,08mm',
	'Conector',
	3,
	'BOX. 004 POSITION 04',
	'NOT ORGANIZED',
	'Borne PCI KRE 3T Azul - Espaçamento 5,08mm;Figure1.jpg',
	'',
	''),
	
(	'Terminal CRIMPLINK Forquilha FV-15 M5-3 1,5mm – Vermelho',
	'Terminal CRIMPLINK Forquilha FV-15 M5-3 1,5mm – Vermelho',
	'Conector',
	5,
	'BOX. 004 POSITION 05',
	'NOT ORGANIZED',
	'Terminal CRIMPLINK Forquilha FV-15 M5-3 1,5mm – Vermelho;Figure1.jpg',
	'',
	''),
	
(	'Terminal CRIMPLINK Olhal OB-25 M4-3 2,5mm – Azul',
	'Terminal CRIMPLINK Olhal OB-25 M4-3 2,5mm – Azul',
	'Conector',
	6,
	'BOX. 004 POSITION 05',
	'NOT ORGANIZED',
	'Terminal CRIMPLINK Olhal OB-25 M4-3 2,5mm – Azul;Figure1.jpg',
	'',
	''),
	
(	'Terminal Faston FDD pré isolado – Vermelho',
	'Terminal Faston FDD pré isolado – Vermelho',
	'Conector',
	1,
	'BOX. 004 POSITION 05',
	'NOT ORGANIZED',
	'Terminal Faston FDD pré isolado – Vermelho;Figure1.jpg',
	'',
	''),
	
(	'Conector Adaptador Mini HDMI Macho x HDMI Fêmea',
	'Conector Adaptador Mini HDMI Macho x HDMI Fêmea',
	'Conector',
	1,
	'BOX. 004 POSITION 06',
	'NOT ORGANIZED',
	'Conector Adaptador Mini HDMI Macho x HDMI Fêmea;Figure1.jpg',
	'',
	''),
	
(	'Plug P4-DC sem Rabicho',
	'Plug P4-DC sem Rabicho',
	'Conector',
	1,
	'BOX. 005 POSITION 01',
	'NOT ORGANIZED',
	'Plug P4-DC sem Rabicho;Figure1.gif',
	'',
	''),
	
(	'Plug P4-DC com Rabicho',
	'Plug P4-DC com Rabicho',
	'Conector',
	1,
	'BOX. 005 POSITION 01',
	'NOT ORGANIZED',
	'Plug P4-DC com Rabicho;Figure1.gif',
	'',
	''),
	
(	'Jack J2 Estéreo PCI Rosca',
	'Jack J2 Estéreo PCI Rosca',
	'Conector',
	1,
	'BOX. 005 POSITION 05',
	'NOT ORGANIZED',
	'Jack J2 Estéreo PCI Rosca;Figure1.jpg',
	'',
	'')
;