/*
 * DIY
 */
INSERT INTO item( name, description, category, quantity, locationBox, status, locationImage, locationDatasheet, locationAttachment ) VALUES
(	'Conversor Analógico para Digital (ADC) de 24-Bit HX711 para balanças',
	'Módule Amplificador HX711 para leitura de massa em células de carga. Conexões: fio vermelho para E+, fio preto para E-, fio verde para A+ e fio branco para A-. Alimentação: 2.6~5.5V; Consumo de corrente: operação normal < 1.5mA, desligado < 1uA.',
	'DIY',
	1,
	'',
	'NOT ORGANIZED',
	'Load_Cell_Amplifier_HX711;Figure1.jpg;Figure2.jpg;Figure3.jpg;Figure4.jpg;Load_Cell_Weight_Sensor_1kg_3.jpg',
	'HX711 - 24-Bit Analog-to-Digital Converter (ADC) for Weigh Scales.pdf',
	''),
	
(	'Driver com LED 10W cor Branca',
	'Tensão entrada (saída) no Driver: AC 86~265V (DC 9~11V); Temperatura de trabalho: -20~60C; Corrente de saída: 700mA; Angulo de feixe: 140°; Temperatura da cor: 6000~6300K; Lumens: 600~900 lumens.',
	'DIY',
	1,
	'BOX 001 POSITION 10',
	'NOT ORGANIZED',
	'Driver com LED 10W cor Branca;Figure1.jpg;Figure2.jpg;Figure3.jpg;Figure4.jpg',
	'',
	''),
	
(	'Módulo Serial I2C para Display LCD',
	'Módulo Serial I2C para Display LCD para conexão de display ao Arduino usando o chip PCF8574',
	'DIY',
	1,
	'BOX 000',
	'NOT ORGANIZED',
	'Serial LCD I2C Module with chip PCF8574;Figure1.jpg;Figure2.jpg;Figure3.jpg;Figure4.jpg',
	'Serial LCD I2C Module with chip PCF8574;Schemas.pdf',
	'Serial LCD I2C Module with chip PCF8574;New LiquidCrystal _ wiki _ Home — Bitbucket.pdf;NewLiquidCrystal_1.5.1.zip'),
	
(	'CC2530 - Módulo ZigBee',
	'Composto por 2 Módulos ZigBee CC2530, 2 Placas Base, 2 Antenas 2.4G 3dB, 1 Módulo Smart RF04EE, 2 Cabos USB. Módulo com 16 canais de transmissão, taxa de transmissão de até 250kbps, transmissão confiável de até 250 metros.',
	'DIY',
	1,
	'PAPER BOX 03',
	'NOT ORGANIZED',
	'Module ZigBee CC2530, 2 base board and module Smart RF04EE;Figure1.jpg;Figure2.jpg',
	'Module ZigBee CC2530, 2 base board and module Smart RF04EE;cc2530.pdf',
	'Module ZigBee CC2530, 2 base board and module Smart RF04EE;ZigBee.7z'),
	
(	'RFID-RC522 - Módulo Sensor de Cartão RFID',
	'Módulo Sensor de Cartão RFID-RC522 com corrente de trabalho de 13~26mA/3.3V. Suporta cartões Mifare1 S50, Mifare1 S70, Mifare Ultralight, Mifare Pro e Mifare Desfare.',
	'DIY',
	1,
	'PAPER BOX 04',
	'NOT ORGANIZED',
	'Módulo Sensor de Cartão RFID;Figure1.jpg',
	'',
	''),
	
(	'Módulo Bluetooth V2.0',
	'Tensão/corrente de trabalho de 3.3V/20~3mA, conectado 8mA, configuração default de 9600, N, 8, 1 e senha 1234.',
	'DIY',
	1,
	'PAPER BOX 04',
	'NOT ORGANIZED',
	'Módulo Bluetooth V2.0 hc-05-HC-05-RF-Wireless;Figure1.jpg;Figure2.jpg',
	'',
	''),
	
(	'AT-09 - Módulo Bluetooth',
	'Módulo Bluetooth 4.0 para Arduino com serial BLE CC2540 CC2541 iBeacon.',
	'DIY',
	1,
	'PAPER BOX 04',
	'NOT ORGANIZED',
	'Módulo Bluetooth AT-09;Figure1.jpg',
	'',
	''),
	
(	'ISD1820 - Módulo para gravação de voz',
	'Modulo ISD1820, para gravação de voz com microfone onboard e gravação de 10s de voz. É composto de três botões (REC,PLAYE e PLAYL), microfone e alto falante.',
	'DIY',
	1,
	'PAPER BOX 04',
	'NOT ORGANIZED',
	'Modulo ISD1820, para gravação de voz;Figure1.jpg',
	'',
	''),
	
(	'Fonte Ajustável para Protoboard',
	'Fonte Ajustável para Protoboard (YwRobot Breadboard Power Supply) com saídas de 3.3V e 5V.',
	'DIY',
	3,
	'PAPER BOX 05',
	'NOT ORGANIZED',
	'Fonte Ajustável para Protoboard;Figure1.jpg',
	'',
	''),
	
(	'Módulo Buck-boost para FPV com LM2587 para entrada de 3 ~ 35V para 1,2 ~ 30V 2A DC',
	'Módulo Buck-boost para FPV com LM2587 para entrada de 3 ~ 35V para 1,2 ~ 30V 2A DC.',
	'DIY',
	1,
	'PAPER BOX 05',
	'NOT ORGANIZED',
	'Módulo Buck-boost para FPV;Figure1.png',
	'',
	''),
	
(	'Placa Amplificadora Stereo com TDA2030A',
	'Placa Amplificadora Stereo com TDA2030A com duplo canal para acesso OCL 18Wx2 ou mono BTL 36Wx1. Resistores de 1% de metal de filmes, Chemi-Con e Panasonic capacitores, 2x3300uF/25V como filtro. Tensão de entrada AC 9V-12V.',
	'DIY',
	1,
	'PAPER BOX 05',
	'NOT ORGANIZED',
	'Placa Amplificadora Stereo TDA2030A;Figure1.jpg',
	'',
	''),
	
(	'RD084DY002 - Módulo de Recarga de Bateria de Lítio 1A',
	'Módulo de Recarga de Bateria de Lítio 1A, com LED indicador de carga. Modelo RD084DY002',
	'DIY',
	1,
	'PAPER BOX 05',
	'NOT ORGANIZED',
	'Módulo de Recarga de Bateria de Lítio 1A;Figure1.jpg',
	'',
	''),
	
(	'Placa de Expansão GSM/GPRS FreeArduino',
	'Placa de Expansão GSM/GPRS FreeArduino usada para fazer/receber ligações, enviar/receber mensagens como também transferências de dados.',
	'DIY',
	1,
	'PAPER BOX 05',
	'NOT ORGANIZED',
	'Placa de Expansão GSM-GPRS FreeArduino;Figure1.jpg',
	'',
	''),
	
(	'Ethernet Shield com Wiznet W5100',
	'Ethernet Shield com Wiznet W5100 para conexão a cabo para Arduino.',
	'DIY',
	1,
	'PAPER BOX 05',
	'NOT ORGANIZED',
	'Ethernet Shield com Wiznet W5100;Figure1.jpg',
	'',
	''),
	
(	'Módulo reconhecimento de impressão digital',
	'Módulo reconhecimento de impressão digital com frequência de trabalho de 433MHz,868MHz ou 915MHz. Sensibilidade de -100dBm, tensão de alimentação de 3.6~6V, tamanho dos caracteres de 256 bytes, tempo de pesquisa < 1 segundo.',
	'DIY',
	1,
	'PAPER BOX 05',
	'NOT ORGANIZED',
	'Modulo reconhecimento de impressão digital;Figure1.jpg',
	'ZFM-20_Series_Fingerprint_Identification_Module-User_Manual.pdf;DY001fingerprint.pdf;adafruit-optical-fingerprint-sensor.pdf',
	'SFGDemoV2.0.rar;Adafruit-Fingerprint-Sensor-Library-master.zip'),
	
(	'PCF8574 - Placa de Expansão',
	'Placa de Expansão PCF8574 no qual pode ser conectado por I2C provendo até 64 portas I/O. A placa é uma interface 8-bit paralela.',
	'DIY',
	1,
	'PAPER BOX 05',
	'NOT ORGANIZED',
	'Placa de Expansão PCF8574;Figure1.jpg',
	'',
	''),
	
(	'DS1307 - Módulo de Real Time Clock',
	'Módulo de Real Time Clock (RTC) com memória 24C32 de 32K com comunicação I2C e chip DS1307.',
	'DIY',
	1,
	'PAPER BOX 05',
	'NOT ORGANIZED',
	'Módulo de Real Time Clock RTC DS1307 DS-1307 AT24C32;Figure1.jpg',
	'',
	''),
	
(	'Protoshield',
	'Protoshield desenvolvido para criar shields de acordo com a necessidade do usuário com dois botões, dois leds, entradas para NOKIA 5110, LCM 1602, entre outros.',
	'DIY',
	1,
	'PAPER BOX 05',
	'NOT ORGANIZED',
	'protoshield-prototype-para-arduino-protoboard-170-pontos;Figure1.jpg;Figure2.jpg',
	'',
	''),
	
(	'Shield de Sensor 5.0',
	'Shield de Sensor no qual podem ser conectados módulo bluetooth, sdcard, display, sensores, entre outros. As dimensões são de 5.7 x 5.7 x 2 cm.',
	'DIY',
	1,
	'PAPER BOX 05',
	'NOT ORGANIZED',
	'Shield de Sensor 5.0;Figure1.jpg',
	'',
	''),
	
(	'W908 - Ibeacon',
	'Ibeacon W908 com chip CC2541, a prova de água, uso de bateria CR2477, range efetivo de 30m e máximo de 100m e corrente de 100uA (standby).',
	'DIY',
	1,
	'PAPER BOX 05',
	'NOT ORGANIZED',
	'ibeacon w908.jpg;Ibeacon w908 -Bluetooth-TICC2541.jpg',
	'',
	''),
	
(	'PCW2138WC - Carregador sem fio',
	'Carregador sem fio (PCW2138WC) com entrada/saída de 5~12VDC/(5VDC/600mA), indutância da bobina de transmissão de 30uH, distância de transmissão de 1~20mm, diâmetro da bobina de 38mm e altura da bobina de 2mm.',
	'DIY',
	1,
	'PAPER BOX 05',
	'NOT ORGANIZED',
	'Carregador sem fio.jpg',
	'',
	''),
	
(	'HLK-RM04 - Módulo Adaptador Wi-Fi',
	'Módulo Adaptador Wi-Fi HLK-RM04 com antena onboard e externa, modo client/AP/server, com todas as funcionalidades de rede com e sem fio.',
	'DIY',
	1,
	'PAPER BOX 05',
	'NOT ORGANIZED',
	'Módulo Adaptador Wi-Fi HLK-RM04.jpg',
	'',
	''),
	
(	'PCF8591 - Módulo Conversor de 8-Bit A/D e D/A',
	'Módulo Conversor PCF8591 de 8-Bit A/D e D/A, tensão de 2.5~6V, 3 pinos de entrada (A0, A1 e A2) e 4 pinos de entrada analógicos programados como saída simples ou entrada diferencial.',
	'DIY',
	1,
	'PAPER BOX 05',
	'NOT ORGANIZED',
	'Módulo Conversor PCF8591 - 1.jpg;Módulo Conversor PCF8591 - 2.jpg;Módulo Conversor PCF8591 - 3.jpg;Módulo Conversor PCF8591 - 4.jpg',
	'',
	''),
	
(	'Módulo Transmissor/Receptor RF de 433MHz',
	'Corrente transm. máx<=40mA (12V), mín<=9mA (3V), modo ressonante/modulação SAW/(ASK/OOK), freq. trab. 315~433.92MHz, pot. trans. 25mW (315MHz,12V), erro freq. 150kHz (máx), vel. <=10kbps,  intervalo de trans. 20~200m.',
	'DIY',
	1,
	'PAPER BOX 05',
	'NOT ORGANIZED',
	'Modulo Transmissor-Receptor RF de 433MHz.jpg',
	'',
	''),
	
(	'Módulo Player MP3 Music com controle Serial UART',
	'Suporte a formato MP3 e WAV, controle por UART, frequência de amostragem de 8kHz~48kHz, tensão de alimentação de 3.2~5.2VDC, suporte para Micro SD (SDHC) Card <=2G (<16G).',
	'DIY',
	1,
	'PAPER BOX 05',
	'NOT ORGANIZED',
	'Modulo Player MP3 Music com controle Serial UART1.jpg;Modulo Player MP3 Music com controle Serial UART2.jpg',
	'',
	''),
	
(	'KY-023 - Módulo Joystick',
	'Módulo joystick PS2, no qual tem um cross rocker que é um resistor bidirecional 10K, com balancim em direções diferentes, a resistência muda com direção, fonte de alimentação 5V, estado original x, tensão de leitura Y é de cerca de 2,5V.',
	'DIY',
	1,
	'PAPER BOX 05',
	'NOT ORGANIZED',
	'Módulo Joystick KY-023.jpg',
	'',
	''),
	
(	'TEA5767 - Módulo Receptor FM',
	'Módulo receptor FM com suporte de frequência entre 76~108MHz usando o chip Philips TEA5767.',
	'DIY',
	1,
	'PAPER BOX 05',
	'NOT ORGANIZED',
	'Módulo Receptor FM TEA57671.jpg;Módulo Receptor FM TEA5767_pinout.jpg;Módulo Receptor FM TEA5767_schematictea.jpg',
	'',
	''),
	
(	'OV7670 - Módulo Camera VGA 300KP',
	'Array fotosensível 640x480, tensão IO 2.5~3.0V, formato saída YUV/YCbCr4:2:2 RGB565/555/444 GRB4:2:2 Raw RGB Data (8 digit), tamanho lente 1/6\"; ângulo visão 25 graus; taxa frame máx. 30fps VGA, sensibilidade 1.3V/(Lux-sec), sinal taxa ruído 46 dB',
	'DIY',
	1,
	'PAPER BOX 05',
	'NOT ORGANIZED',
	'Módulo Camera VGA 300KP OV7670.jpg',
	'',
	''),
	
(	'Joystick Escudo v1.2',
	'Um Joystick para adicição do Nokia 5110 LCD e interface de nRF24L01. Pode-se desenvolver facilmente jogos com Joystick, e até a comunicação entre si com nRF24L01 wireless. ',
	'DIY',
	1,
	'PAPER BOX 05',
	'NOT ORGANIZED',
	'Joystick Escudo v1.2.jpg',
	'',
	''),
	
(	'Cabo conversor IPX para RP-SMA macho',
	'Cabo conversor adaptador IPX para RP-SMA macho com comprimento de 19cm.',
	'DIY',
	1,
	'PAPER BOX 05',
	'NOT ORGANIZED',
	'Cabo conversor IPX para RP-SMA macho.jpg',
	'',
	''),
	
(	'Conversor Lógico Bidirecional 5V/3V',
	'Conversor nível lógico de 4 canais para Arduino, em uso de I2C.',
	'DIY',
	6,
	'PAPER BOX 05',
	'NOT ORGANIZED',
	'Conversor Lógico Bidirecional 5V-3V.jpg',
	'',
	''),
	
(	'A7 - Placa de Desenvolvimento GPS GPRS GSM SMS e Módulo de Voz',
	'Placa de Desenvolvimento A7 GPS GPRS GSM SMS e Módulo de Voz com tensão de alimentação de 3.3~4.2V, suporte as frequ&ecirc;ncias 850/900/1800/1900 MHz com duas antenas.',
	'DIY',
	1,
	'PAPER BOX 05',
	'NOT ORGANIZED',
	'Placa de Desenvolvimento A7 GPS GPRS GSM SMS e Módulo de Voz.jpg',
	'',
	''),
	
(	'ATK-NEO-6M-V12 - Módulo GPS  com antena Ulbox',
	'Taxa 4.8k/9.6k/38.4k(padrão)/57.6k; 3.3/5V sistema SCM; GPS L1 (1575.42MHZ) código C/A; SBAS:WAAS/EGNOS/MSAS; Precisão:2.5 MCEP (SBAS2.0mCEP); Inicio a frio/quente:27s (mais rápido)/1s; Sensibilidade:161dBm; Protocolo:NMEA(padrão)/UBX Binary',
	'DIY',
	1,
	'PAPER BOX 05',
	'NOT ORGANIZED',
	'Módulo GPS  com antena Ulbox ATK-NEO-6M-V121.jpg;Módulo GPS  com antena Ulbox ATK-NEO-6M-V122.jpg;Módulo GPS  com antena Ulbox ATK-NEO-6M-V123.jpg',
	'',
	''),
	
(	'CD74HC4067 - Placa com Multiplexador/Demultiplexador Analógico de 16 canais',
	'Multiplexador/Demultiplexador analógico com tensão de trabalho de 2~6V. Modelo CD74HC4067 de 16 canais.',
	'DIY',
	1,
	'PAPER BOX 05',
	'NOT ORGANIZED',
	'Placa com Multiplexador-Demultiplexador Analógico CD74HC4067 de 16 canais.jpg',
	'',
	''),
	
(	'CNC Shield V3 para impressora 3D com 4 Drivers A4988',
	'CNC Shield com tensão de 12~36VDC, botão reset, 4 eixos (X, Y, Z e A), entrada para conectores de fim de curso para cada eixo. Compatível com Arduino UNO e GRBL.',
	'DIY',
	1,
	'PAPER BOX 05',
	'NOT ORGANIZED',
	'CNC Shield V3 para impressora 3D com 4 Drivers A4988_1.jpg;CNC Shield V3 para impressora 3D com 4 Drivers A4988_2.jpg',
	'',
	''),
	
(	'Módulo DRF1278F LoRa 433MHz SX1278',
	'Frequency Range: 433MHz Modulation: FSK/GFSK/MSK/LoRa SPI Data Interface Sensitivity: -136dBm Output Power: +20dBm Data Rate: <300 kbps 127dB dynamic Range RSSI Packet engine up to 256 bytes with CRC Standby current: 1uA Supply voltage: 1.8~3.6V',
	'DIY',
	2,
	'PAPER BOX 05',
	'NOT ORGANIZED',
	'LoRa_SX1278_433MHz_Module_DRF1278F_1.jpg;LoRa_SX1278_433MHz_Module_DRF1278F_2.jpg;LoRa_SX1278_433MHz_Module_DRF1278F_3.jpg;LoRa_SX1278_433MHz_Module_DRF1278F_4.jpg',
	'DRF1278F - 20dBm LoRa Long Range RF Front-end Module.pdf',
	''),
	
(	'Módulo TTL para RS485 para Arduino',
	'Chipset MAX485; 2 pinos para comunicação e fiação fácil RS-485 Tensão de trabalho de 5V',
	'DIY',
	2,
	'PAPER BOX 05',
	'NOT ORGANIZED',
	'Módulo TTL para RS485 para Arduino_1.jpg;Módulo TTL para RS485 para Arduino_2.jpg;Módulo TTL para RS485 para Arduino_3.jpg',
	'',
	''),
	
(	'Módulo sem fio NRF24L01 + PA + LNA (com antena)',
	'Controlador: NRF24L01+ Frequência: 2.4GHz Tensão de operação: 1.9 à 3.6V Taxa de transferência: 2 Mbit/s Corrente em power down: 400nA Corrente em standby: 32uA Dimensões: 29 x 15mm Regulador de tensão embutido Conector para antena SMA',
	'DIY',
	2,
	'PAPER BOX 05',
	'NOT ORGANIZED',
	'NRF24L01 + PA + LNA (com antena)_1.jpg;NRF24L01 + PA + LNA (com antena)_2.jpg',
	'nRF24L01P_Product_Specification_1_0.pdf;nWP_011_v1.1.pdf;RF_Test_Instructions_nRF24L01P_v1_0.pdf;Tuning_the_nFR24xx_matching_network.pdf',
	'nAN24-12.zip;nRF24L01P-EK.zip'),
	
(	'Módulo SD Card',
	'LED indicador Suporte para SD Card Pinos: GND, 3.3V, 5V, CS, MOSI, SCK, MISO e GND',
	'DIY',
	1,
	'PAPER BOX 05',
	'NOT ORGANIZED',
	'SD_Card_Module_1.jpg;SD_Card_Module_2.jpg;SD_Card_Module_Pin_Outs.png',
	'SDCard Module_schematic.pdf;Micro SD Data Sheet.pdf;SDCard Datasheet  SDCard V 1.2.pdf',
	''),
	
(	'Conversor Digital para Analógico de 12Bits com memória EEPROM',
	'O módulo CJMCU-MCP4725 é um conversor DAC (Digital-to-Analog Converter) controlado por I2C. Caracteristicas: resolução de 12bits Interface I2C (suportados os modos Standard, Fast, e High-Speed) Alimentção de 2.7~5.5V',
	'DIY',
	1,
	'PAPER BOX 05',
	'NOT ORGANIZED',
	'MCP4725_1.png;MCP4725_2.jpg;MCP4725_3.jpg',
	'MCP4725.pdf',
	''),
	
(	'X9C103S - Potenciômetro 10kΩ controlado digitalmente',
	'Potenciômetro controlado digitalmente com resistência de 10k Ohms, com 99 posições e com tensão de alimentação entre 3V à 5V. Corrente máx. ativa de 3mA. Corrente máx. standby de 750µA. Duração de 100000 trocas de dados por bit.',
	'DIY',
	3,
	'PAPER BOX 05',
	'NOT ORGANIZED',
	'x9c103s_digital_potentiometer_module_2.jpg;x9c103s_digital_potentiometer_module_1.jpg;Potenciômetro Digital X9C103S_1.jpg;Potenciômetro Digital X9C103S_2.jpg;Potenciômetro Digital X9C103S_3.jpg;Potenciômetro Digital X9C103S_4.jpg',
	'X9C102, X9C103, X9C104, X9C503 - Digitally Controlled Potentiometer.pdf',
	''),
	
(	'Conversor RS232 para TTL',
	'Transceiver : 2 (1 TTL -> RS232 + 1 TTL <- RS232) Operating Voltage:3 V ~ 5.5 V Maximum Datarate: 120 kbps Operation: Full Duplex Protocol: RS232 Receiver Hysteresis: 300mV Temperature range: -40°C ~ 85°C Size: 10mm x 15mm',
	'DIY',
	3,
	'PAPER BOX 05',
	'NOT ORGANIZED',
	'Mini_RS232_to_TTL_Converter_1.jpg;Mini_RS232_to_TTL_Converter_2.jpg',
	'MAX3222, MAX3232, MAX3237, MAX3241 - 3.0V to 5.5V, Low-Power, up to 1Mbps, True RS-232 Transceivers Using Four 0.1µF External Capacitors.pdf',
	''),
	
(	'Teclado Numérico de 16 teclas',
	'Número de teclas: 16; Durabilidade Mecânica: 1000000 ciclos; Max. resistência de contato: 200mΩ; Torque de comutação: 1N; Max. tensão de operação: 24VDC; curso da tecla: 1.2mm; Max. corrente de operação: 20mA; Largura: 65mm; Altura: 64mm',
	'DIY',
	1,
	'PAPER BOX 06',
	'NOT ORGANIZED',
	'teclado_numerico_16_teclas_pretas_1.jpg;teclado_numerico_16_teclas_pretas_2.jpg;teclado_numerico_16_teclas_pretas_3.jpg',
	'',
	''),
	
(	'L298N - Módulo para constrole de motores DC',
	'Tensão operação 5~35V (4~35V), controle p/ 2 motores DC ou 1 motor passo, corrente máxima 2A por canal ou 4A máxima, tensão lógica 4.5~5.5V (HIGH)/0V (LOW), corrente lógica 0~36mA, potência máxima de 20W (25W).',
	'DIY',
	2,
	'PAPER BOX 06',
	'NOT ORGANIZED',
	'Modulo L298N.jpg;Modulo L298N_description.jpg',
	'',
	''),
	
(	'Módulo Arduino CAN Bus MCP2515',
	'Circuito Integrado MCP2515; Suporta especificação CAN V2.0B (1 Mb/S); Tensão de alimentação: 5V; Corrente de operação: 5mA (standby 1µA); Interface: SPI; Resistores de terminação de 120 ohms; Temperatura de operação: -40 a 85°C; Dimensões: 40 x 28 x 11,5mm',
	'DIY',
	1,
	'PAPER BOX 06',
	'NOT ORGANIZED',
	'Modulo Arduino CAN Bus MCP2515;Figure1.jpg;Figure2.jpg',
	'Modulo Arduino CAN Bus MCP2515;MCP2515.pdf;TJA1050.pdf;Arduino CAN Tutorial - Interfacing MCP2515 CAN BUS Module with Arduino.pdf',
	'Modulo Arduino CAN Bus MCP2515;arduino-mcp2515-master.zip'),

(	'X9C103S 10K Digital Potentiometer Module',
	'Supply voltage: 3~5V; Chip: X9C103S; PCB board size: 2.7 * 1.3CM; 10K span potentiometer. Potentiometer center tap between 0-10k slide in total 100 (potentiometer wiper typical impedance 40 ohms) VL and VH digital potentiometer sliding rheostat port corresponding to the low-end and high-end, allowing the input voltage range -5V to + 5V.',
	'DIY',
	3,
	'PAPER BOX 06',
	'NOT ORGANIZED',
	'X9C103S Digital Potentiometer Module;Figure1.jpg;Figure2.webp;Figure3.jpg;Figure4.webp;Figure5.webp;Figure6.webp',
	'',
	''),
	
(	'Slide Potentiometer 10K Ohm Linear Module',
	'Size: 90 x 20 mm; Color: Red; Voltage: 3.3~5V; Port: analog; Resistance: 10K Ohm; Technology: Carbon Film',
	'DIY',
	1,
	'PAPER BOX 06',
	'NOT ORGANIZED',
	'Slide Potentiometer 10K Ohm Linear Module;Figure1.webp;Figure2.webp;Figure3.webp;Figure4.webp;Figure5.jpg;Figure6.webp',
	'',
	''),
	
(	'Socket Adapter for 8Pin NRF24L01 Wireless Transceive module 51 A18',
	'Socket Adapter for 8Pin NRF24L01 Wireless Transceive module 51 A18 with 26 x 19 mm and Vcc 5V. Module on-board AMS1117-3.3',
	'DIY',
	2,
	'PAPER BOX 06',
	'NOT ORGANIZED',
	'Socket Adapter for 8Pin NRF24L01 Wireless Transceive module 51 A18;Figure1.jpg;Figure2.jpg;Figure3.jpg;Figure4.jpg;Figure5.webp;Figure6.jpg',
	'',
	''),
	
(	'Mini RS232 MAX3232 converter serial module with TTL level',
	'Mini RS232 MAX3232 converter serial module with TTL level',
	'DIY',
	3,
	'PAPER BOX 06',
	'NOT ORGANIZED',
	'Mini RS232 MAX3232 converter serial module with TTL level;Figure1.jpg',
	'',
	''),
	
(	'A4988 Stepper Motor Driver',
	'Low RDS (On) Output; Automatic current decay mode detection/selection; Mix with slow current decay modes; Synchronous rectification for low power dissipation; Internal under voltage lockout (UVLO); Cross-current protection; 3.3 and 5 V compatible logic supply; Thermal shutdown circuitry; Ground fault protection; Load short-circuit protection; Optional step five modes: full, 1/2, 1/4, 1/8 and 1/16',
	'DIY',
	5,
	'PAPER BOX 06;PAPER BOX 05',
	'NOT ORGANIZED',
	'A4988 Stepper Motor Driver;Figure1.jpg;Figure2.jpg;Figure3.jpg;Figure4.jpg;Figure5.jpg;Figure6.jpg;Figure7.jpg',
	'A4988 Stepper Motor Driver;A4988.pdf;Pololu 8-35V 2A Single Bipolar Stepper Motor Driver A4988.pdf',
	'')
;