/*
 * Embedded
 */
INSERT INTO item( name, description, category, quantity, locationBox, status, locationImage, locationDatasheet, locationAttachment ) VALUES
(	'Arduino LilyPad',
	'Projeto Arduino LilyPad com microcontrolador ATmega328 com tensão de operação de 2.7~5.5V, 14 pinos I/O, 6 pinos PWM e 6 pinos de entrada analogica, 40mA de corrente I/O, 16kB de flash, 1kB de SRAM, 512 bytes e velocidade de clock de 8MHz.',
	'Embedded',
	1,
	'PAPER BOX 03',
	'NOT ORGANIZED',
	'Arduino LilyPad.jpg',
	'',
	''),
	
(	'Arduino Nano',
	'Placa de desenvolvimento do projeto Arduino, em um tamanho menor comparado ao Arduino UNO, mas com caracteristicas semelhantes (ATmega328).',
	'Embedded',
	2,
	'PAPER BOX 03',
	'NOT ORGANIZED',
	'Arduino Nano V3-0_1.jpg;Arduino Nano V3-0_2.jpg',
	'',
	'CH341SER.zip;CH341SER (2).zip'),
	
(	'Onion Omega 2+',
	'Microcontrolador com 580MHz de processamento, 128MB de memria, 32MB de armazenamento flash, ÚSB 2.0, slot microSD , 15 pinos de GPIO, 2 PWM, 2 UART, 1 I2C, 1 SPI e 1 I2S.',
	'Embedded',
	1,
	'PAPER BOX 03',
	'NOT ORGANIZED',
	'Onion Omega 2 - front-back.png;Onion Omega 2 - Pinout-Diagram.png',
	'',
	''),
	
(	'Arduino Mega 2560 R3',
	'Placa com microcontrolador ATmega2560 com tensão de operação/entrada 5V/(7-12V), 54 portas digitais (15 PWM), 16 portas analógicas, corrente pinos I/O 40mA, corrente pinos 3.3V de 50mA, memória flash 256kB, SRAM 8kB, EEPROM 4kB, clock 16MHz.',
	'Embedded',
	1,
	'PAPER BOX 03',
	'NOT ORGANIZED',
	'Arduino-Mega-2560-Pinout.jpg',
	'',
	''),
	
(	'Arduino Uno R3',
	'Arduino Uno R3, com microcontrolador ATmega328, tensão operação/entrada 5V/(7-12V), 14 pinos I/O digitais (6 PWM) de 5V/40mA, 6 pinos analógicos, corrente pino 3.3V de 50mA, memória flash 32kB, SRAM 2kB, EEPROM 1kB e clock de 16MHz.',
	'Embedded',
	1,
	'PAPER BOX 03',
	'NOT ORGANIZED',
	'Arduino Uno R3.jpg;Arduino Uno R3 - perspective.png',
	'',
	''),
	
(	'BeagleBone Black',
	'BeagleBone Black AM3358 1GHz ARM Cortex-A8, 512MB DDR3 RAM, 4GB 8bit eMMC, acelerador gráfico 3D e ponto flutuante NEON, 2 microcontroladores PRU 32-bit, porta mini USB comunição/alimentação, USB, ethernet, saída HDMI, 92 pinos I/0 e alimentação.',
	'Embedded',
	1,
	'PAPER BOX 03',
	'NOT ORGANIZED',
	'Beaglebone Black - perspective.jpg;Beaglebone Black.jpg;BeagleBone Black - top.jpg',
	'',
	''),
	
(	'C.H.I.P.',
	'C.H.I.P. com processador de 1GHz, 4GB de armezanemento de alta velocidade, WiFi B/G/N, 512MB de RAM, bluetooth 4.0, conector para saída de VGA/audio, porta mini USB e USB.',
	'Embedded',
	1,
	'PAPER BOX 03',
	'NOT ORGANIZED',
	'CHIP.png',
	'',
	''),
	
(	'Raspberry Pi modelo Board B Rev2.0 512 ARM',
	'Raspberry Pi processador BCM2835 (CPU, GPU, DSP, e SDRAM), cpu 700 MHz ARM1176JZF-S core (ARM11 family), gpu Broadcom VideoCore IV, OpenGL ES 2.0, 1080p30 h.264/MPEG-4 AVC high-profile decoder, 512MB SDRAM, saida RCA/HDMI/P2, slot SD/MMC/SDIO e Ethernet',
	'Embedded',
	1,
	'PAPER BOX 03',
	'NOT ORGANIZED',
	'Raspberry Pi modelo Board B Rev2.0 512 ARM.png',
	'',
	''),
	
(	'Raspberry Pi 3 model B',
	'Processador quad-core 1.2 GHz 64-bit ARMv8, Wirelles 802.11n, Bluetooth 4.1 (BLE), 1GB RAM, 4 USB, 40 GPIO, HDMI, Ethernet, saída áudio/vídeo composto, interface Câmera e Display, slot Micro SD e gráfico VideoCore IV 3D.',
	'Embedded',
	1,
	'PAPER BOX 03',
	'NOT ORGANIZED',
	'Raspberry Pi 3 model B.jpg',
	'',
	''),
	
(	'NodeMcu ESP8266 (ESP-12E)',
	'Modelo Amica, driver CP2012, antena embutida, wireless padrão 802.11 b/g/n, 11 GPIO de funções de PWM, I2C, SPI, etc, tensão operação 4,5~9V, taxa transferência: 110~460800bps, modo operação STA/AP/STA+AP, suporta 5 conexões TCP/IP.',
	'Embedded',
	2,
	'PAPER BOX 03',
	'NOT ORGANIZED',
	'nodemcu_amica_esp12_1.jpg;nodemcu_amica_esp12_2.jpg',
	'',
	''),
	
(	'ESP8266 ESP-12F',
	'Wi-Fi 802.11 B/G/N; Wi-Fi Direct (P2P), soft-AP; Stack TCP/IP integrada; CPU 32 bits de baixo consumo integrada; SDIO 1.1/2.0, SPI, UART; Segurança: WPA, WPA2; ADC 10 bits; Memória Flash: 4Mbyte; Tensão (alimentação / IO): 3.3v.',
	'Embedded',
	4,
	'PAPER BOX 03',
	'NOT ORGANIZED',
	'ESP-12F_1.jpg;ESP-12F_2.jpg;ESP-12F_3.jpg;ESP-12F_4.jpg',
	'ESP-12F.pdf',
	''),
	
(	'ESP32',
	'Microprocessador 32-bit/2 núcleos, Wi-Fi 802.11 b/g/n/e/i, bluetooth v4.2 BR/EDR e BLE, ROM 448KiB, SRAM 520KiB, 10 GPIOs, ADCs 12/8bits, 2 I2C, 2 UART, CAN 2.0, 4 SPI, 2 I2S, 16 PWM. Aceleração Criptografia AES, SHA-2, RSA, ECC e RNG.',
	'Embedded',
	1,
	'PAPER BOX 03',
	'NOT ORGANIZED',
	'ESP-32_1.jpg;ESP-32_2.jpg;ESP-32_3.png;ESP-32_4.png',
	'ESP32 Datasheet.pdf;ESP-WROOM-32 Datasheet.pdf',
	''),
	
(	'EPROM 5V ALTERA FPGA CycloneII EP2C5T144C8N Minimum System Development Board',
	'On board 3.3V and 1.2V Regulators; Single Power 5VDC operation; On board Clock Oscillator; On board Configuration storage EEPROM; 3x LED indicators for user; 1x Power Indicator LED; Reset Switch; FPGA Chip: Altera Cyclone II, EP2C5T144C8N; FPGA chip has 4068 logic elements; Multiple 4k RAM blocks giving a total of 119,898 bits; 13 multipliers; Two PLLs; 89 I/Os; Maximum clock frequency is 300 MHz; FPGA Core Voltage : 1.2V; FPGA IO voltage : 3.3V; Size : 6 (cm) x 8 (cm); Configuration EEPROM chip: 4Mbit EPCS4; Oscillator Frequency: 50MHz; Support for the development of embedded CPU NiosII',
	'Embedded',
	1,
	'PAPER BOX 03',
	'NOT ORGANIZED',
	'ALTERA FPGA Cyclone II EP2C5T144 Board;Figure1.jpg;Figure2.jpg;Figure3.jpg;Figure4.jpg;Figure5.webp;Figure6.webp;Figure7.jpg;Figure8.webp;Figure9.png;Figure10.gif;Figure11.webp',
	'ALTERA FPGA Cyclone II EP2C5T144 Board;EP2C5T144-Altera-Cyclone-II-FPGA-Development-Board-Diagram.pdf;ALTREA-CY2-Evaluation-Board-Schematic-Diagram.pdf;0900766b8130521b.pdf;Cyclone-II-Device-Handbook.pdf;cyc_c51014.pdf',
	'ALTERA FPGA Cyclone II EP2C5T144 Board;EP2C5T144E-Diagrams.zip;EP2C5-core-board-test.zip')
;