/*
 * Tool
 */
INSERT INTO item( name, description, category, quantity, locationBox, status, locationImage, locationDatasheet, locationAttachment ) VALUES
(	'Luva ESD Anti-estática Fingerfit Ponta dos Dedos',
	'Lupa dissipativa emborrachada em PU na ponta dos dedos, composta de poliamida, poliéster e filamentos condutores. Possui resistividade de 1 x 10^8 ohms.',
	'Tool',
	1,
	'PAPER BOX 01',
	'NOT ORGANIZED',
	'Luva ESD Anti-estática Fingerfit Ponta dos Dedos.png',
	'',
	''),
	
(	'Alicate de Corte Diagonal',
	'Alicate de corte diagonal para corte rente para acabamento.',
	'Tool',
	1,
	'PAPER BOX 01',
	'NOT ORGANIZED',
	'Alicate de Corte Diagonal.jpg',
	'',
	''),
	
(	'Alicate Aço Especial Corte Zero ACI-12',
	'Alicate Aço Especial Corte Zero ACI-12 para corte de contatos e fios.',
	'Tool',
	1,
	'PAPER BOX 01',
	'NOT ORGANIZED',
	'Alicate Aço Especial Corte Zero ACI-12.jpg',
	'',
	''),
	
(	'Alicate Pinça Bico Pato Reto (Polofer)',
	'Alicate Pinça Bico Pato Reto (Polofer) para multiuso, de precisão, com trava no cabo (push).',
	'Tool',
	1,
	'PAPER BOX 01',
	'NOT ORGANIZED',
	'Alicate Pinça Bico Pato Reto (Polofer).jpg',
	'',
	''),
	
(	'Alicate Decapador H5 21K547',
	'Alicate Decapador H5, com regulagem ajustável de 5 a 12mm, corte de cabos e fios de até 2mm, decapador de 0.2mm^2 até 6.0mm^2 (24 AWG até 10AWG) fabricado na Alemanha.',
	'Tool',
	1,
	'PAPER BOX 01',
	'NOT ORGANIZED',
	'Alicate Decapador H5 21K547.jpg',
	'',
	''),
	
(	'Lupa de Aumento 75mm',
	'Lupa de Aumento de 75mm de diâmetro.',
	'Tool',
	1,
	'PAPER BOX 01',
	'NOT ORGANIZED',
	'Lupa de Aumento 75mm.jpg',
	'',
	''),
	
(	'Sugador de Solda Suetoku Profissional',
	'Sugador de Solda Suetoku Profissional para uso para retirar solda de Estanho.',
	'Tool',
	1,
	'PAPER BOX 01',
	'NOT ORGANIZED',
	'Sugador de Solda Suetoku Profissional.jpg',
	'',
	''),
	
(	'Pulseira anti-estática LEKO',
	'Pulseira anti-estática de cabo de aterramento de 1.6 metros.',
	'Tool',
	1,
	'PAPER BOX 01',
	'NOT ORGANIZED',
	'Pulseira anti-estática LEKO.jpg',
	'',
	''),
	
(	'Alicate Compressão TALON TL-H518A',
	'Cripador TALON TL-H518A para cabos coaxial RG59 e RG6 com conector F.',
	'Tool',
	1,
	'',
	'NOT ORGANIZED',
	'Alicate Compressão TALON TL-H518A.jpg',
	'',
	''),
	
(	'Alicate Decapador de Cabo Coaxial',
	'Descascador de fios e cabo coaxial de 4, 6, 8 e 12mm, podendo descascar fios RG58 e RG59.',
	'Tool',
	1,
	'',
	'NOT ORGANIZED',
	'Alicate Decapador de Cabo Coaxial.jpg',
	'',
	''),
	
(	'Assistente de Soldagem Hikari HK-151',
	'Assistente de Soldagem Hikari com alavanca, gancho, escova, garfo, agulha, suporte, faca, raspador e broca.',
	'Tool',
	1,
	'PAPER BOX 01',
	'NOT ORGANIZED',
	'Assistente de Soldagem Hikari HK-151.jpg',
	'',
	''),
	
(	'Extrator de CI PLCC Pinça WJ-368',
	'Extrator de CI PLCC Pinça, indicado para extração de CIs PLCC, PGA e DIP (soquete), com corpo em plástico e hastes em aço inoxidável, design ergonômico para retirar o CI verticalmente, adaptável à diversos tamanhos de CI e proteção anti-estática.',
	'Tool',
	1,
	'PAPER BOX 01',
	'NOT ORGANIZED',
	'Extrator de CI PLCC Pinça WJ-368.jpg',
	'',
	''),
	
(	'Pinça angular de precisão anti-magnética TS-15',
	'Pinça angular de precisão anti-magnética de aço inoxidável.',
	'Tool',
	1,
	'PAPER BOX 01',
	'NOT ORGANIZED',
	'Pinça angular de precisão anti-magnética TS-15.jpg',
	'',
	''),
	
(	'Pinça CT01 Aço Inox 125mm - ponta reta lisa',
	'Pinça CT01 Aço Inox 125mm com ponta reta lisa de 25 gramas.',
	'Tool',
	1,
	'PAPER BOX 01',
	'NOT ORGANIZED',
	'Alicate Pinça CT01 Aço Inox 125mm - ponta reta lisa.jpg',
	'',
	''),
	
(	'Broca de aço inoxidável para circuito impresso PCB',
	'Broca de aço inoxidável para circuito impresso PCB de 3.175mm (diâmetro de haste) x 0.4mm (diâmetro de corte) x 7mm (comprimento de corte).',
	'Tool',
	9,
	'PAPER BOX 01',
	'NOT ORGANIZED',
	'Broca de aço inoxidável para circuito impresso PCB.jpg',
	'',
	''),
	
(	'Cabo teste para analisador lógico',
	'Cabo teste para analisador lógico com 10 garras, sendo 5 vermelhas e 5 amarelas.',
	'Tool',
	1,
	'PAPER BOX 01',
	'NOT ORGANIZED',
	'Cabo teste para analisador lógico.jpg',
	'',
	''),
	
(	'Jogo de Chave Torx T5 A T10',
	'Jogo de Chave Torx Com 6 Peças T5 A T10 para notebook e celular.',
	'Tool',
	1,
	'PAPER BOX 01',
	'NOT ORGANIZED',
	'Jogo de Chave Torx T5 A T10.png',
	'',
	''),
	
(	'Kit de Chaves de Precisão com 31 Peças',
	'Kit de Chaves de Precisão com 31 Peças, onde há 1 cabo e 30 Bits Chaves Allen, Torx, Philips, e Fenda Para Manutenção de Celulares e Eletrônicos.',
	'Tool',
	1,
	'PAPER BOX 01',
	'NOT ORGANIZED',
	'Kit de Chaves de Precisão com 31 Peças.jpg',
	'',
	''),
	
(	'Kit acessórios com 137 peças para mini esmeril EDA-9QR',
	'Itens inclusos: 4 Pinças: 0.8, 1.6, 2.4 e 3.2mm; 5 Discos de corte reforçados de fibra de vidro 32mm; 65 Discos de corte 26mm; 1 Tubos com pasta de polir; 1 Escova de cerdas; 6 Pontas montadas; 3 Suportes para discos de corte; 2 Suportes para tubo de lixa; 1 Suporte para discos de feltro; 5 Pontas diamantadas; 2 Fresas; 4 Tubos de lixa 1/2"; 5 Tubos de lixa 1/4"; 1 Pedra para afiar; 4 Rolos de esmeril; 2 Pedras de polimento; 5 Feltros diversos tamanhos; 20 discos de lixa, Maleta.',
	'Tool',
	1,
	'PAPER BOX 01',
	'NOT ORGANIZED',
	'Kit acessorios com 137 pecas para mini esmeril EDA-9QR_1.jpg;Kit Acessorios com 137 Pecas para Mini Esmeril EDA-9QR-2.jpg;Kit Acessorios com 137 Pecas para Mini Esmeril EDA-9QR-3.jpg',
	'',
	''),
	
(	'Kit chaves para celular Lelong 36 peças modelo LE-960',
	'Itens inclusos: Chave Torx: T2, T3, T4, T5, T6, T7, T8, T9, T10, T15; Chave Philips: 1.2, 1.5, 2.0; Chave de Fenda: 1.5, 2.0; Chave Hexagonal: 2.5, 3, 3.5, 4, 4.5, 5, 5.5; Chave Estrela (5 Pontas): 0.8, 1.2; Chave Y: 2.0; Chave PH2; Chave Triangulo: 2.3; Chave U1: 2.6; 02 - chaves plásticas; 01 - Ventosa; 01 - Pinça.',
	'Tool',
	1,
	'PAPER BOX 01',
	'NOT ORGANIZED',
	'Kit chaves para celular lelong 36 pecas_le-960_1.png;Kit chaves para celular lelong 36 pecas_le-960_2.png',
	'',
	''),
	
(	'Pontas para Retífica Black Bull',
	'Pontas para retífica com 20 pontas e 1/8\" (3mm) cada, composto de ferro cobertas com carboneto de silicone.',
	'Tool',
	1,
	'PAPER BOX 01',
	'NOT ORGANIZED',
	'Pontas para Retífica Black Bull_1.jpg;Pontas para Retífica Black Bull_2.jpg',
	'',
	''),
	
(	'Conjunto de Agulha Aço Inoxidável de Circuito Eletrônico de 80mm x 0.7-1.3mm',
	'Conjunto de 10 Agulhas de Circuito Eletrônico PCB para reparo de soldagem com comprimento de 80mm e diâmetro de 0.7 até 1.3mm',
	'Tool',
	1,
	'PAPER BOX 01',
	'NOT ORGANIZED',
	'Agulha Circuito Eletrônico_1.jpg;Agulha Circuito Eletrônico_2.jpg;Agulha Circuito Eletrônico_3.jpg;Agulha Circuito Eletrônico_4.jpg;Agulha Circuito Eletrônico_5.jpg;Agulha Circuito Eletrônico_6.jpg',
	'',
	''),
	
(	'Ponta de Prova com Gancho',
	'Ganhos na cores preto, vermelho, verde, amarelo e azul, em material latão e plástico, gancho bronze de 4mm x 2mm, com conexão dos clipes com o multimetro ou fonte.',
	'Tool',
	1,
	'PAPER BOX 01',
	'NOT ORGANIZED',
	'Ponta de Prova Gancho_1.jpg;Ponta de Prova Gancho_2.jpg;Ponta de Prova Gancho_3.jpg;Ponta de Prova Gancho_4.jpg;Ponta de Prova Gancho_5.jpg;Ponta de Prova Gancho_6.jpg',
	'',
	''),
	
(	'Chave Ajuste Vishay Spectrol TO-008',
	'Chave Ajuste Vishay Spectrol TO-008 para trimmer e trimpot multivoltas.',
	'Tool',
	1,
	'PAPER BOX 01',
	'NOT ORGANIZED',
	'Chave Ajuste Spectrol TO-008 para trimmer-trimpot.jpg',
	'',
	''),
	
(	'Escova ESD Hikari HK-219',
	'Escova anti-estática para limpar placas de eletrônica sem descarregar cargas eletrosestáticas. Cabo ergonômico de 125mm com cerdas de 52mm x 3mm x 25mm.',
	'Tool',
	1,
	'PAPER BOX 01',
	'NOT ORGANIZED',
	'escova_esd_hk-219_frente.jpg;escova_esd_hk-219_lateral.jpg',
	'',
	''),
	
(	'Detector e Medidor de Tensão Hyx Vd4',
	'Medição de tensão diretamente de 12~220V. Detecção de tensão sobre linhas inderetamente de 12~220V. Não necessita de pilhas.',
	'Tool',
	1,
	'PAPER BOX 01',
	'NOT ORGANIZED',
	'Detector e Medidor de Tensão Hyx Vd4.jpg',
	'',
	''),
	
(	'Micro furadeira NEJE AH0002-3',
	'Micro furadeira NEJE AH0002-3 de aço inoxidável com comprimento de 95mm, diâmetro de 4mm, tensão de alimentação de 12~24VDC, corrente maior que 2A, rotação sem carga de 4000~12000rpm, faixa de broca de 0.3~4mm.',
	'Tool',
	1,
	'Office',
	'NOT ORGANIZED',
	'Micro furadeira NEJE AH0002-3.jpg',
	'',
	''),
	
(	'Lupa de Cabeça Profissional',
	'Super Lupa de Cabeça Profissional 2 Super Leds + 5 Lentes - MG81001-H, com possibilidade de ampliar 6 vezes além de LEDs de iluminação.',
	'Tool',
	1,
	'Office',
	'NOT ORGANIZED',
	'Lupa de Cabeça Profissional.jpg',
	'',
	'')
;