/*
 * Sensor
 */
INSERT INTO item( name, description, category, quantity, locationBox, status, locationImage, locationDatasheet, locationAttachment ) VALUES
(	'DS18B20 - Sensor de temperatura TO92',
	'Sensor temperatura com resolução programável por 1 fio de 9~12 bits, tensão alimentação 3.0~5.5V, temperatura medida entre -55&deg;C até +125&deg;C, conversão 12 bits em 750ms (max), acuracia +-0.5&deg;C de temperaturas entre -10&deg; até +85&deg;C',
	'Sensor',
	10,
	'PAPER BOX 04',
	'NOT ORGANIZED',
	'DS18B20.png;DS18B20_pins.png',
	'',
	''),
	
(	'LM35DZ - Sensor de temperatura',
	'Sensor de temperatura para medidas entre -55&deg;C até 150&deg;C, com tensão de operação entre 4~30V, consumo de corrente menor que 60uA, fator linear 10mV/&deg;C.',
	'Sensor',
	1,
	'PAPER BOX 04',
	'NOT ORGANIZED',
	'LM35DZ.jpg',
	'',
	''),
	
(	'Módulo de Sensor de Som',
	'Módulo de Sensor de Som com sensibilidade ajustada, com tensão de operação de 3.3V~5V, com saída digital on-off e saída analógica regulada por potenciômetro.',
	'Sensor',
	1,
	'PAPER BOX 04',
	'NOT ORGANIZED',
	'Modulo de Sensor de Som.jpg',
	'',
	''),
	
(	'Sensor de chuva',
	'Sensor de chuva com saída analógica e digital.',
	'Sensor',
	1,
	'PAPER BOX 04',
	'NOT ORGANIZED',
	'Sensor de chuva.jpg',
	'',
	''),
	
(	'GY-521 (MPU6050) Módulo de 3 eixos de aceleração e giroscópio',
	'Módulo GY-521 de 3 eixos de aceleração/giroscópio 6DOF com chip MPU6050, alimentação 3~5V, comunicação I2C, conversor A/D de 16 bits, range do giroscópio de +- 250, 500, 1000 e 2000 degree/sec, range do acelerômetro de +- 2g, +-4g, +-8g e +-16g.',
	'Sensor',
	1,
	'PAPER BOX 04',
	'NOT ORGANIZED',
	'Módulo de 3 eixos de aceleração e giroscópio DOF MPU-6050.jpg',
	'',
	''),
	
(	'HC-SR04 - Módulo de sensor de ultrassônico',
	'Módulo de sensor de ultrassônico para medição de distância HC-SR04 com tensão de alimentação de 5V DC, corrente de operação de 2mA, alcance de 2cm~4m e precisão de 3mm.',
	'Sensor',
	1,
	'PAPER BOX 04',
	'NOT ORGANIZED',
	'Módulo de sensor de ultrassônico HC-SR04.jpg',
	'',
	''),
	
(	'XD-58C - Módulo de frequência cardíaca',
	'Módulo de frequência cardíaca XD-58C com tensão de trabalho de 3~5V de material FR4 da marca KEYES.',
	'Sensor',
	1,
	'PAPER BOX 04',
	'NOT ORGANIZED',
	'Módulo de frequência cardíaca XD-58C.jpg',
	'',
	''),
	
(	'ACS712-20A - Módulo de Sensor de Corrente até 20A',
	'Módulo ACS712 20A de Sensor Corrente de 20A com tempo resposta de 5us, largura banda de 80kHz, margem erro de 1.5% a 25°C, resistência interna de 0.0012Ohms, tensão isolação de 2.1kVrms, tensão alimentação de 4.5~5.5V e sensibilidade de 100mV/A.',
	'Sensor',
	1,
	'PAPER BOX 04',
	'NOT ORGANIZED',
	'Módulo de Sensor de Corrente até 20A ACS712 20A.jpg',
	'',
	''),
	
(	'MQ-3 - Sensor Álcool Etanol',
	'Sensor Álcool Etanol MQ-3 com tensão de alimentação de 5V e saídas analógica e digital.',
	'Sensor',
	1,
	'PAPER BOX 04',
	'NOT ORGANIZED',
	'Sensor Álcool Etanol MQ-3.jpg',
	'',
	''),
	
(	'HC-SR501 - Sensor Infravermelho de movimento',
	'Sensor HC-SR501 de Infravermelho de movimento ROBOX RTHW com consumo em standby de 50uA, distancia máxima de detecção de 7m, ângulo  de máximo de detecção de 110° e tensão de alimentação de 4.5~20V.',
	'Sensor',
	1,
	'PAPER BOX 04',
	'NOT ORGANIZED',
	'Sensor Infravermelho de movimento ROBOX IR HC-SR501.jpg',
	'',
	''),
	
(	'MQ-2 - Sensor de gás liquefeito de petróleo e natural',
	'Sensor MQ-2 com saída digital e analógica, sensível a gás liquefeito de petróleo, natural, de cidade e de poluição.',
	'Sensor',
	1,
	'PAPER BOX 04',
	'NOT ORGANIZED',
	'Sensor MQ-2 de gás liquefeito de petróleo e natural.png',
	'',
	''),
	
(	'BH1750FVI - Sensor Digital de Intensidade de Luz',
	'Chip BH1750FVI original da ROHM, tensão de alimentação de 3~5V, intevalo de iluminância de 0~65535 lux e conversor AD de 16 bits.',
	'Sensor',
	1,
	'PAPER BOX 04',
	'NOT ORGANIZED',
	'Sensor Digital de Intensidade de Luz BH1750FVI.jpg',
	'BH1750FVI - Digital 16 bit Serial Output Type Ambient Light Sensor IC.pdf',
	'TEST_BH1750.zip;BH1750-master.zip'),
	
(	'MQ-7 - Sensor de Monóxido de Carbono',
	'Sensor MQ-7 com material SnO2 com a capacidade de detectar CO, trabalhando com tensão de 5V e saída digital e analógica.',
	'Sensor',
	1,
	'PAPER BOX 04',
	'NOT ORGANIZED',
	'Sensor MQ-7 de Monóxido de Carbono1.jpg;Sensor MQ-7 de Monóxido de Carbono2.jpg',
	'',
	''),
	
(	'Módulo Sensor Magnético de Efeito Hall',
	'Módulo Sensor Magnético de Efeito Hall para aplicações em trabalhos com campos magnéticos, velocidade e \"gap\" de indução. Tensão de alimentação de 5V.',
	'Sensor',
	1,
	'PAPER BOX 04',
	'NOT ORGANIZED',
	'Módulo Sensor Magnético de Efeito Hall (a3144eul).jpg',
	'',
	''),
	
(	'SW-520D - Módulo de Sensor de Ângulo',
	'Módulo de Sensor de Ângulo com SW-520D, tensão de alimentação de 3.3~12VDC, saída 0 (LED verde ligado) e 1 (LED verde desligado).',
	'Sensor',
	1,
	'PAPER BOX 04',
	'NOT ORGANIZED',
	'Modulo de Sensor de Angulo (SW520).jpg',
	'',
	''),
	
(	'GY-273 (HMC5883L) - Módulo Bússola',
	'Módulo Bússola GY-273 com chip HMC5883L, tensão de alimentação de 3~5V, comunicação I2C, faixa de medição +-1.3~8 Gaus.',
	'Sensor',
	1,
	'PAPER BOX 04',
	'NOT ORGANIZED',
	'Módulo Bússola GY-273 (HMC5883L).jpg',
	'',
	''),
	
(	'Módulo Sensor Gestos e RGB',
	'Sensor de Gestos e Luz Ambiente de alimentação de 3.3V.',
	'Sensor',
	1,
	'PAPER BOX 04',
	'NOT ORGANIZED',
	'Modulo Sensor Gestos e RGB.jpg',
	'',
	''),
	
(	'ADXL345 - Módulo Digital Sensor Aceleração',
	'Módulo Digital Sensor Aceleração ADXL345 de 3-eixos de +-2g, +-4g, +-8g, +-16g, com resolução fixada de 10 bits. Tensão de alimentação de 5V/3.3V',
	'Sensor',
	1,
	'PAPER BOX 04',
	'NOT ORGANIZED',
	'Modulo Digital Sensor Aceleracao ADXL345.jpg',
	'',
	''),
	
(	'TTP223B - Módulo Sensor Touch',
	'Módulo Sensor Touch TTP223B com tensão de operação de 2~5.5V, saída de estado alto/baixo de 0.8V/0.3V, tempo de resposta de 220ms (estado baixo) e 60ms (estado alto)',
	'Sensor',
	1,
	'PAPER BOX 04',
	'NOT ORGANIZED',
	'Modulo Sensor Touch TTP223B (Touch Sensor Capacitive).jpg',
	'',
	''),
	
(	'BMP085 - Módulo Digital Sensor de Pressão Barométrica e Temperatura do Ar BOSCH',
	'Intervalo pressão barométrica 300~1100hPa (elevação 9000~500m), tensão alimentação 1.8~3.6V (VDDA), 1.62~3.6V (VDDD), consumo modo padrão 5uA, acurácia alta c/ resolução 0.06hPa (0.5m), no modo linear, resolução é 0.03hPa (0.25m).',
	'Sensor',
	1,
	'PAPER BOX 04',
	'NOT ORGANIZED',
	'Módulo Digital Sensor de Pressão Barométrica e Temperatura do Ar BOSCH BMP085.jpg',
	'BMP085 - Digital pressure sensor.pdf',
	'Adafruit_Python_BMP-master.zip;Adafruit-BMP085-Library-master.zip;Adafruit_Python_GPIO-master.zip;BMP280_driver-master.zip'),
	
(	'Módulo de Sensor de toque de corpo humano',
	'Tensão de alimentação de 5VDC e uso do circuito LM393, saída analógica e digital.',
	'Sensor',
	1,
	'PAPER BOX 04',
	'NOT ORGANIZED',
	'Módulo de Sensor de toque de corpo humano.jpg',
	'',
	''),
	
(	'UVM-30A - Sensor de Detecção de Raios Ultravioleta',
	'Sensor com 28mm/12mm/10mm, detecção raios ultravioletas, alimentação 3~5V, tensão saída 0~1VDC, precisão teste de +-1 UV INDEX, corrente funcionamento 0.06mA (typ) e 0.1mA (max), comprimento onda de resposta 200nm~370nm, estabilidade de -20º~85º',
	'Sensor',
	1,
	'PAPER BOX 04',
	'NOT ORGANIZED',
	'Sensor UVM-30A de Detecção de Raios Ultravioleta.jpg',
	'',
	''),
	
(	'HB100 - Sensor de detecção de radar',
	'Sensor microondas de efeito doppler com frequência de 10.525 GHz, alimentação de 5V +-0.25V, corrente de 40mA, dimensões 37mm (c), 45mm (l) e 8mm (a).',
	'Sensor',
	1,
	'PAPER BOX 04',
	'NOT ORGANIZED',
	'Sensor de detecção de radar HB100.jpg',
	'',
	''),
	
(	'RCWL-0516 - Radar doppler',
	'Radar doppler RCWL-0516 para sensor de movimento para detecção de longa distância e com capacidade de penetração. Tensão de alimentação 4~28VDC e saída de 3.3V',
	'Sensor',
	1,
	'PAPER BOX 04',
	'NOT ORGANIZED',
	'Radar doppler RCWL-0516.jpg',
	'',
	''),
	
(	'GY-9250 (MPU-9250) Módulo de 9 eixos de aceleração, giroscópio e magnetômetro',
	'O módulo MPU-9250 tem 9-eixos: 3 do giroscópio (escalas de ±250, ±500, ±1000, e ±2000°/sec), 3 do acelerômetro (escalas de ±2g, ±4g, ±8g e ±16g) e 3 do magnetômetro (resolução de saída de 14 bit (0.6µT/LSB) e escala completa de±4800µT)',
	'Sensor',
	1,
	'PAPER BOX 04',
	'NOT ORGANIZED',
	'GY-9250(MPU-9250)-9-axis_1.jpg;GY-9250(MPU-9250)-9-axis_2.jpg;GY-9250(MPU-9250)-9-axis_3.jpg;GY-9250(MPU-9250)-9-axis_4.jpg;GY-9250(MPU-9250)-9-axis_5.jpg',
	'PS-MPU-9250A-01.pdf;RM-MPU-9250A-00.pdf',
	'MPU9250-master.zip'),
	
(	'CM30-3015-NC - Sensor Capacitivo',
	'Sensor Capacitivo com distância de detecção de 0-15mm com saídas NPN/NO+NC e tensão de alimentação 6~36VDC.',
	'Sensor',
	1,
	'PAPER BOX 04',
	'NOT ORGANIZED',
	'Sensor Capacitivo.jpg',
	'',
	''),
	
(	'PR12-2DP - Sensor Indutivo de Proximidade',
	'Sensor Indutivo de Proximidade PR12-2DP com distância de detecção de 0-2mm, frequência de resposta de 1.5kHz e tensão de alimentação de 12-24VDC.',
	'Sensor',
	1,
	'PAPER BOX 04',
	'NOT ORGANIZED',
	'Sensor Indutivo de Proximidade PR12-2DP1.jpg;Sensor Indutivo de Proximidade PR12-2DP2.png',
	'',
	''),
	
(	'YF-S201 - Contador de Fluxo de água',
	'YF-S201 - Contador de Fluxo de Água usando sensor de efeito Hall. Pressão < 1.75MPa, tensão de 5~24V, acurácia = 1~60L/Min +-3%, caracteristica do pulso do fluxo = 4.8xQ, onde Q é L/Min.',
	'Sensor',
	1,
	'PAPER BOX 04',
	'NOT ORGANIZED',
	'Contador de Fluxo de água - YF-S201.jpg',
	'',
	''),
	
(	'DHT21/AM2301 - Sensor de Temperatura e Umidade',
	'Sensor de Temperatura e Umidade DHT21/AM2301 com tensão de alimentação de 3~5V, umidade de 0~100%, temperatura de -40~80°C, precisão de +-3%RH/+-0.5°C com saída digital \"monobus\".',
	'Sensor',
	1,
	'PAPER BOX 04',
	'NOT ORGANIZED',
	'Sensor de Temperatura e Umidade DHT21-AM2301_1.jpg;Sensor de Temperatura e Umidade DHT21-AM2301_2.jpg;Sensor de Temperatura e Umidade DHT21-AM2301_3.jpg',
	'',
	''),
	
(	'SCT013-000 - Sensor de Corrente não Invasivo 100A',
	'Medição corrente 0~100A, corrente saída 0~50mA, acurácia ±1%, linearidade ±3%, razão espiras 1:1800, deslocamento fase ≤180º, material núcleo ferrite e frequência trabalho 50~1000Hz.',
	'Sensor',
	1,
	'PAPER BOX 04',
	'NOT ORGANIZED',
	'Sensor de Corrente não Invasivo 100A SCT013-000.jpg',
	'',
	''),
	
(	'E18-D80NK - Sensor de Proximidade Fotoelétrico Infravermelho com faixa de detecção de 3~80 cm',
	'Sensor normalmente aberto com faixa de detecção de 3~80 cm, alimentação de 5VDC, corrente de consumo < 25mA, diâmetro de 17 mm, comprimento do sensor de 45 mm, comprimento do cabo de 45 cm, tempo de resposta < 2 ms, ângulo maior que 15°.',
	'Sensor',
	1,
	'PAPER BOX 04',
	'NOT ORGANIZED',
	'E18-D80NK - Sensor de Proximidade_1.jpg;E18-D80NK - Sensor de Proximidade_2.jpg;E18-D80NK - Sensor de Proximidade_3.jpg;E18-D80NK - Sensor de Proximidade_4.jpg;E18-D80NK - Sensor de Proximidade_5.jpg;E18-D80NK - Sensor de Proximidade_6.jpg',
	'E18-D80NK Long range adjustable IR sensor.pdf;Wiring the E18-D80NK Infrared Distance Ranging Sensor.pdf',
	''),
	
(	'Célula de Carga de 5kg',
	'Potência nominal: 1,0±0.15mV/V; Impedância entrada/saída: 1115±10%/1000±10%Ω; Resistência isolamento: 1000MΩ; Sobrecarga seguro/extrema: 150%FS/200%FS; Alimentação:3~12VDC; IP65',
	'Sensor',
	2,
	'PAPER BOX 04',
	'NOT ORGANIZED',
	'Load_Cell_Weight_Sensor_5kg_1.jpg;Load_Cell_Weight_Sensor_5kg_2.jpg',
	'5KG resistance strain type pressure sensor.doc',
	''),
	
(	'Sensor LSON Ultrassônico 40KHz',
	'16mm ultrasonic; Water resistant; 40KHz sensor; Diameter: 16mm; Working mode: transceiver split; Transmitting sound pressure at 10V: >=110dB; Sensitivity: >=-75dB; Capacitance at 1KHz: 1800+/-30%',
	'Sensor',
	4,
	'PAPER BOX 04',
	'NOT ORGANIZED',
	'Sensor LSON Ultrason.jpeg',
	'',
	''),
	
(	'Sensor de nível de água',
	'Sensor de nível de água para ser usado no Arduino.',
	'Sensor',
	1,
	'PAPER BOX 05',
	'NOT ORGANIZED',
	'Sensor de nível de água.jpg',
	'',
	''),
	
(	'Módulo Encoder Rotação de 360°',
	'Módulo Encoder Rotação de 360° com resolução de 20 pulsos por revolução e corrente máxima de 10mA.',
	'Sensor',
	1,
	'PAPER BOX 05',
	'NOT ORGANIZED',
	'Módulo Encoder Rotação de 360.jpg',
	'',
	''),

(	'Célula de Carga para balança de até 50kg',
	'Capacity:40~50 kg Error:0.05 mv/v Output Sensitivity:1.0±0.1 mv/v Nonlinearity:0.03 %FS Repeatability:0.03 %FS Hysteresis:0.03 %FS Zero Output:±0.1 mV/V Input Resistance:1000±20 Ω Insulation Resistance:≥5000 MΩ Overload Capacity:150 %FS',
	'Sensor',
	1,
	'PAPER BOX 05',
	'NOT ORGANIZED',
	'Load Sensor - 50kg_1.jpg;Load Sensor - 50kg_2.jpg',
	'Load Sensor - 50kg.pdf',
	''),
	
(	'Voltímetro Analógico 91L16',
	'Voltímetro Analógico 91L16; Medição de 0 a 300 VAC; Tamanho 40x40mm',
	'Sensor',
	1,
	'PAPER BOX 06',
	'NOT ORGANIZED',
	'Voltímetro Analógico 91L16 0 a 300 VAC_1.jpg;Voltímetro Analógico 91L16 0 a 300 VAC_2.jpg;Voltímetro Analógico 91L16 0 a 300 VAC_3.jpg',
	'',
	'')
;