/*
 * Equipment
 */
INSERT INTO item( name, description, category, quantity, locationBox, status, locationImage, locationDatasheet, locationAttachment ) VALUES
(	'Alicate Amperimetro Digital AD-7910 True RMS',
	'Medidas de tensão contínua e alternada True RMS, corrente contínua e alternada, resistência, capacitância, frequência, ciclo de atividade, temperatura, teste de diodo, continuidade e detecção de tensão elétrica. Abertura garra 52mm (2”)',
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',
	'Alicate Amperimetro Digital AD-7910;Figure1.jpg',
	'Alicate Amperimetro Digital AD-7910;AD-7910 Manual Fev 2015 A.pdf',
	'AD-7910;'
),
(	'Multímetro Digital MD-6130 True RMS',
	'Multímetro Digital MD-6130 para leituras de tensão/corrente elétrica contínua/alternada (True RMS), de temperatura, de teste de transistores, diodos e continuidade, de resistência, de capacitância, indutância e frequência.',
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',
	'Multímetro Digital MD-6130 True RMS.jpg',
	'',
	''),
	
(	'Multímetro Digital Minipa ET-2041',
	'Leitura tensão contínua (alternada) 200mV~1000V (2V~750V), corrente contínua (alternada) 2mA~20A (20mA~20A), capacitância 2nF~20uF, temperatura, frequência, teste transistores bipolares, teste diodos/continuidade e resistência 200Ohms~200MOhms.',
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',
	'Multímetro Digital Minipa ET-2041.jpg',
	'',
	''),
	
(	'Multímetro Analógico HM202A+',
	'Multímetro Analógico HM202A+ com medição de tensão elétrica contínua/alternada, corrente elétrica contínua, resistência, decibel, teste de transistores/ICEO e continuidade.',
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',
	'Multímetro Analógico HM202A+.jpg',
	'',
	''),
	
(	'Osciloscópio Hantek 6022BE',
	'Osciloscópio Hantek 6022BE com dois canais analógicos de 20MHz com taxa de amostragem de 48MS/s, salva tela em TXT, JPG/MP, MS Excell/Word, com transformada rápida de Fourier (FFT), funçõoes matemáticas, entre outras.',
	'Equipment',
	1,
	'Office',
	'NOT ORGANIZED',
	'Hantek 6022BE_1.jpg;Hantek 6022BE_2.jpg;Hantek 6022BE_3.jpg;Hantek 6022BE_4.jpg;Hantek 6022BE_5.jpg;Hantek 6022BE_6.jpg;Hantek 6022BE_7.jpg;Hantek 6022BE_8.jpg;Hantek 6022BE_9.jpg;Hantek 6022BE_10.jpg;Hantek 6022BE_11.jpg',
	'HT6022_Manual.pdf',
	'Hantek6022BE.zip'),
	
(	'Fonte de Alimentação Icel PS-5000',
	'Fonte simétrica, modos tensão/corrente constante, exatidão +-0.5%, saídas 0~30V/0~3A//0~30V/0~3A//5V/3A, ligação série (paralelo) 0~60V/0~6A (0~30V/0~6A), proteção contra curto, regulagem menor 0.01%, riple menor 0.5Vrms, alimentação 126/220V (50/60Hz).',
	'Equipment',
	1,
	'Stand',
	'NOT ORGANIZED',
	'Fonte de Alimentação Icel PS-5000.jpg',
	'PS-5000 Manual de instruções.pdf',
	''),
	
(	'Gerador de forma de onda arbitrária DDS- 3X25 25M',
	'Com canal 12 bits saída, saída sinal sincronizada, 1 canal medida entrada de contador/frequência. Formas geradas como seno, quadrada, triangular, dente serra, TTL, ruído branco, ruído gaussiano, trapezoidal, exponencial, AM e FM.',
	'Equipment',
	1,
	'Office',
	'NOT ORGANIZED',
	'Gerador de forma de onda arbitrária DDS-3X25 25M.jpg',
	'DDS3X25_Manual.pdf',
	'DDS3X25.zip'),
	
(	'Estação de retrabalho BST-898D',
	'Estação de retrabalho SMD com temperatura de saída de 100~450ºC (ar) e 200~480ºC (solda) e tensão de entrada de 110/220 V para 50/60Hz. Potência de saída de 720W (soprador) e 40W (soldador)',
	'Equipment',
	1,
	'Office',
	'NOT ORGANIZED',
	'Estação de retrabalho BST-898D.jpg',
	'',
	''),
	
(	'Conversor USB para RS232 TTL PL2303HX',
	'Simples comunicação UART e saída de 3.3V ou 5V.',
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',
	'Conversor USB para RS232 TTL PL2303HX.jpg',
	'',
	''),
	
(	'PICkit 3 PIC Programmer',
	'Com conexão USB, execução real-time, compatível MPLAB IDE, monitor curto-circuito/sobre-tensão, suporte baixa tensão até 2V (2~6V), LEDs diagnóstico (alimentação, ocupado e erro), leitura/escrita memória de programa e dados microcontrolador.',
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',
	'PICkit 3 PIC Programmer.jpg',
	'',
	''),
	
(	'Analisador Lógico Open Bench',
	'Analisador lógico open source (Open Bench Logic Sniffer) com interface USB, captura formas de onda de até 50MHz sobre 32 canais, 16 canais de 5V com buffer.',
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',
	'Analisador Lógico Open Bench_1.jpg;Analisador Lógico Open Bench_2.jpg;Analisador Lógico Open Bench_3.jpg',
	'',
	''),
	
(	'Gravador de PIC K150 (USB 40ZIF)',
	'Gravador de microcontroladores PIC de alguns das séries 12C, 12F, 16C, 16F e 18. Gravador com soquete ZIF de 40 pinos. Compatível somente com Windows 98/2000/NT/XP e 7.',
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',
	'Gravador de PIC K150 (USB 40ZIF)_1.jpg;Gravador de PIC K150 (USB 40ZIF)_2.jpg',
	'',
	''),
	
(	'Gravador AVR USBasp',
	'Gravador para controladores Atmel AVR com uma conexão USB. Permite a leitura ou escrita na EEPROM, firmware, fuse bits e lock bits. Velocidade de programação maior que 5kBytes/seg. Opção de modo lento SCK para alvos com baixo clock (<1.5MHz).',
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',
	'Gravador AVR USBasp_1.jpg;Gravador AVR USBasp_2.jpg;Gravador AVR USBasp_3.jpg;Gravador AVR USBasp_4.jpg',
	'',
	''),	
	
(	'Balança Digital Portátil',
	'Balança digital com capacidade de 1000g, e mínimo de 0.1g, com unidades em g, ct, oz e gn. Divisões de 0.1g, temperatura de operação de 10~30ºC e uso de 2 pilhas AAA.',
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',
	'Balança Digital Portátil.jpg',
	'',
	''),
	
(	'RF Explorer 3G Combo - Analisador de Espectro',
	'Analisador de Espectro portátil com tela LCD 128x64 pixels, leitura em 240~960MHz/15~2700MHz, com alcance de 112kHz~100MHz, uma antena Sub-GHz Nagoya NA-773 e outra 2.4GHz helicoidal, amplitude de resolução de 0.5dBm.',
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',
	'RF Explorer 3G Combo - Analisador de Espectro.png',
	'',
	''),
	
(	'Microscopio 1000X USB',
	'Microscópio USB com ampliação de 1000X, com captura de imagem e vídeo.',
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',
	'Microscopio 1000X USB.jpg',
	'',
	''),	
	
(	'Wi-Pi módulo Wi-Fi para Raspberry Pi',
	'Wi-Pi módulo Wi-Fi para Raspberry Pi compativel com IEEE 802.11,802.11g e 802.11b. Intervalo de frequência de 2.4GHz até .4835GHz. Suporte nativo para o Linux Raspbian Weezy. Interface USB 2.0 e potência máxima de transmissão de 20dBm.',
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',
	'Wi-Pi módulo Wi-Fi para Raspberry Pi.jpg',
	'',
	''),
	
(	'Adaptador USB para Ethernet Apple',
	'Adaptador USB 2.0 para Ethernet Apple que oferece um conector RJ-45 compatível com Ethernet 10/100BASE-T.',
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',
	'Adaptador USB para Ethernet Apple.jpg',
	'',
	''),
	
(	'Adaptador 10 pinos para 6 pinos AVRISP USBasp',
	'Adaptador 10 pinos para 6 pinos AVRISP USBasp para uso no gravador AVR USBasp, AVRISP, USBASP e STK500.',
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',
	'Adaptador 10 pinos para 6 pinos AVRISP USBasp_1.jpg;Adaptador 10 pinos para 6 pinos AVRISP USBasp_2.jpg;Adaptador 10 pinos para 6 pinos AVRISP USBasp_3.jpg;Adaptador 10 pinos para 6 pinos AVRISP USBasp_4.jpg',
	'',
	''),
	
(	'Placa Adaptadora de Som USB Virtual com canal 5.1',
	'Placa de som surround virtual 5.1 com USB 2.0, perfeito para fone de ouvido ou alto falantes e um microfone.',
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',
	'Placa Adaptadora de Som USB Virtual com canal 5.1_1.jpg;Placa Adaptadora de Som USB Virtual com canal 5.1_2.jpg',
	'',
	''),
	
(	'Satelite Finder SF-95',
	'Satelite Finder SF-95 é um localizado de Satélite FINDER 950~2150MHz, com entrada máxima de -10dBm e tensão de alimentação 13~18V DC.',
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',
	'Satelite Finder SF-95.jpg;Satelite Finder SF-95_1.jpg;Satelite Finder SF-95_2.jpg;Satelite Finder SF-95_3.jpg',
	'',
	''),
	
(	'Mini Teclado Wireless 2.4Hz USB',
	'Mini Teclado Wireless 2.4Hz USB com suporte para HTPC, computadores com sistemas operacional Windows/Linux/Mac, PlayStation3, XBOX 360 e Android. Tensão de alimentação de 3V (2x AAA) com corrente menor que 50mA em operação e 1mA em descanso.',
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',
	'Mini Teclado Wireless 2.4Hz USB.jpg',
	'',
	''),
	
(	'Nano Adaptador USB Wireless N150Mbps TL-WN725N',
	'Adaptador USB Wireless com velocidade de transmissão Wireless de até 150Mbps e segurança avançada com suporte a WEP de 64/128, WPA, PA2/WPA-PSK/WPA2-PSK (TKIP / AES).',
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',
	'Nano Adaptador USB Wireless N150Mbps TL-WN725N_1.jpg;Nano Adaptador USB Wireless N150Mbps TL-WN725N_2.jpg',
	'',
	''),
	
(	'Cabo conversor USB para RS232',
	'Especificação USB 1.1 e 2.0; Suporte RS232 com interface DB9 e DB25; Taxa de transferência acima de 1Mbps',
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',
	'Adaptador USB-RS232 - 1.jpg;Adaptador USB-RS232 - 2.jpg;Adaptador USB-RS232 - 3.jpg;Adaptador USB-RS232 - 4.jpg',
	'',
	''),
	
(	'Peso de Calibração de 5 gramas',
	'Peso de Calibração de 5 gramas.',
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',
	'peso de Calibracao 5 gramas_1.jpg;peso de Calibracao 5 gramas_2.jpg;peso de Calibracao 5 gramas_3.jpg',
	'',
	''),
	
(	'Tomada USB 2.0 com 7 portas',
	'Tomada USB 2.0 com 7 portas compatível com USB 1.1, taxa de transferência de dados de 1.5 Mbps até 480 Mbps e proteção de 500mA.',
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',
	'Tomada USB 2.0 com 7 portas_1.jpg;Tomada USB 2.0 com 7 portas_2.jpg;Tomada USB 2.0 com 7 portas_3.jpg;Tomada USB 2.0 com 7 portas_4.jpg;Tomada USB 2.0 com 7 portas_5.jpg;Tomada USB 2.0 com 7 portas_6.jpg;',
	'',
	''),
	
(	'Cabo extensor com conector OBD2 macho para fêmea de 16 pinos para ELM327 da Elbow',
	'Cabo extensor com conector OBD2 macho para fêmea de 16 pinos para ELM327 da Elbow com comprimento de 60cm',
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',
	'Extension_Cable_Flat_OBD2_16Pin_Male_to_Female_ELM327_1.jpg;Extension_Cable_Flat_OBD2_16Pin_Male_to_Female_ELM327_2.jpg;Extension_Cable_Flat_OBD2_16Pin_Male_to_Female_ELM327_3.jpg;Extension_Cable_Flat_OBD2_16Pin_Male_to_Female_ELM327_4.jpg',
	'',
	''),
	
(	'Conversor USB para RS485',
	'Módulo conversor USB para RS485; Cor: Preta; Driver USB: CH340; Velocidade: 75~115200bps; Máxima distância de comunicação RS485: 1200m; Dimensões: 60mmx18mmx14mm.',
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',
	'USB to RS485_1.jpg;USB to RS485_2.jpg;USB to RS485_3.jpg;USB to RS485_4.jpg',
	'',
	'CH341SER.zip;CH341SER (2).zip'),
	
(	'Conversor USB para RS232 TTL FT232RL',
	'Módulo Conversor FTDI FT232RL USB para RS232 Serial TTL com operação em 3.3 ou 5V. Chip: FT232RL; LEDs indicadores RX e TX; Tensão TTL selecionável para 5V ou 3.3V; Pinos: DTR, RXD, TX, VCC, CTS, GND; Interface: Mini USB; Dimensões: 36 x 18mm',
	'Equipment',
	1,
	'Paper Box 02',
	'NOT ORGANIZED',
	'USB to RS232 TTL FT232RL_1.png;USB to RS232 TTL FT232RL_2.jpg',
	'FT232R USB UART I.C._v104.pdf',
	''),
	
(	'Adaptador TF para SD Card',
	'Adaptador TF para SD Card para uso no Raspberry Pi modelo B.',
	'Equipment',
	1,
	'Paper Box 03',
	'NOT ORGANIZED',
	'Adaptador TF para SD Card.jpg',
	'',
	''),
	
(	'Adaptador GPIO para Raspberry PI',
	'Adaptador GPIO com revisão 2.0 com 26 pinos compatível com Raspberry Pi 2 e modelo B e B+.',
	'Equipment',
	1,
	'Paper Box 03',
	'NOT ORGANIZED',
	'Adaptador GPIO para Raspberry PI_1.jpg;Adaptador GPIO para Raspberry PI_2.jpg;Adaptador GPIO para Raspberry PI_3.jpg;Adaptador GPIO para Raspberry PI_4.jpg',
	'',
	''),
	
(	'ELM327 OBD2 - Interface de diagnóstico',
	'Interface de diagnóstico ELM327 OBD2 versão 2.1 de conexão bluetooth.',
	'Equipment',
	1,
	'Paper Box 04',
	'NOT ORGANIZED',
	'ELM327 OBD2 - Interface de diagnóstico.jpg',
	'',
	''),
	
(	'Controle para uso em MP3',
	'Controle para uso em MP3. Uso de duas pilhas de relógio. Há 21 teclas incluindo turn on/off, mode, play e pause, mute, entre outros.',
	'Equipment',
	1,
	'Paper Box 05',
	'NOT ORGANIZED',
	'Controle para uso em MP3.jpg',
	'',
	''),
	
(	'Controle JVC RM-RK50',
	'Controle JVC RM-RK-50 com 9 botões e uso de bateria CR2025.',
	'Equipment',
	1,
	'Paper Box 06',
	'NOT ORGANIZED',
	'Controle JVC RM-RK50 (P14-Infrared module).jpg',
	'',
	''),
	
(	'Webcam 3MP HD 720P C270 Logitech',
	'Resolução máxima: 720p/30qps; Tipo de foco: foco fixo; Tecnologia de lente: padrão; Microfone embutido: mono; FoV: 60°; Clipe universal que se ajusta a laptops e LCDs ou monitores; Comprimento do cabo: 1,5 m',
	'Equipment',
	1,
	'Paper Box 05',
	'NOT ORGANIZED',
	'Webcam 3MP HD 720P C270 Logitech;Figure1.png;Figure2.png;Figure3.png;Figure4.png',
	'Webcam 3MP HD 720P C270 Logitech;hd-webcam-c270.pdf',
	'Webcam 3MP HD 720P C270 Logitech;LogiCameraSettings_2.10.4.7z.001;LogiCameraSettings_2.10.4.7z.002;LogiCameraSettings_2.10.4.7z.003'),

(	'Conversor HDMI para VGA com cabo P2 + P2 estéreo',
	'Conversor HDMI para VGA, acompanha cabo P2 + P2 estéreo',
	'Equipment',
	1,
	'Paper Box 06',
	'NOT ORGANIZED',
	'Conversor HDMI para VGA;Figure1.jpg',
	'',
	''),

(	'Leitor de Cartão de Memória SD',
	'Leitor de Cartao de Memoria 480Mbps para cartões Ultra II SD, MMC 4.0, MMC-II, HS RS MMC, Extreme III-SD e RS-MMC',
	'Equipment',
	1,
	'Paper Box 06',
	'NOT ORGANIZED',
	'Leitor de Cartao de Memoria SD;Figure1.jpg',
	'',
	''),
	
(	'Fonte Chaveada CFTV 5V 3A com Plug P4 2,1mm',
	'Fonte Chaveada CFTV 5V 3A com Plug P4 2,1mm com Novo Padrao INMETRO',
	'Equipment',
	1,
	'Paper Box 06',
	'NOT ORGANIZED',
	'Fonte Chaveada CFTV 5V 3A;Figure1.jpg',
	'',
	'')
;