/*
 * Button
 */
INSERT INTO item( name, description, category, quantity, locationBox, status, locationImage, locationDatasheet, locationAttachment ) VALUES
(	'Chave Push Button NA',
	'Chave Push Button NA',
	'Button',
	2,
	'BOX. 004 POSITION 02',
	'NOT ORGANIZED',
	'Chave Push Button NA;Figure1.jpg',
	'',
	''),
	
(	'Chave Push Button NA DS-314 – 2T sem trava – vermelho',
	'Chave Push Button NA DS-314 – 2T sem trava – vermelho',
	'Button',
	1,
	'BOX. 004 POSITION 02',
	'NOT ORGANIZED',
	'Chave Push Button NA DS-314 – 2T sem trava – vermelho;Figure1.jpg',
	'',
	''),
	
(	'Chave de Gancho Micro-switch KW9-XW',
	'Chave de Gancho Micro-switch KW9-XW',
	'Button',
	1,
	'BOX. 004 POSITION 02',
	'NOT ORGANIZED',
	'Chave de Gancho Micro-switch KW9-XW;Figure1.jpg',
	'',
	''),
	
(	'Chave Alavanca',
	'Chave Alavanca',
	'Button',
	2,
	'BOX. 004 POSITION 02',
	'NOT ORGANIZED',
	'Chave Alavanca.png',
	'',
	''),
	
(	'Chave táctil KFC-A06 – 12X12X4,3mm – 4T – 180º',
	'Chave táctil KFC-A06 – 12X12X4,3mm – 4T – 180º',
	'Button',
	9,
	'BOX. 004 POSITION 03',
	'NOT ORGANIZED',
	'Chave Táctil KFC-A06 12X12X4,3mm - 4T - 180°;Figure1.jpg',
	'',
	''),
	
(	'Chave HH SS12D00G3 com 3 Terminais',
	'Chave HH SS12D00G3 com 3 Terminais',
	'Button',
	2,
	'BOX. 004 POSITION 05',
	'NOT ORGANIZED',
	'Chave HH SS12D00G3 com 3 Terminais;Figure1.jpg',
	'',
	''),
	
(	'Chave táctil KFC-A06 - 6X6X5mm - 4T – 180°',
	'Chave táctil KFC-A06 - 6X6X5mm - 4T – 180°',
	'Button',
	4,
	'BOX. 004 POSITION 05',
	'NOT ORGANIZED',
	'Chave Táctil KFC-A06 - 6X6X5mm - 4T - 180°;Figure1.jpg',
	'',
	''),
	
(	'Chave Tactil Redonda TSY6650 6X6X5mm 2T 180º',
	'Chave Tactil Redonda TSY6650 6X6X5mm 2T 180º',
	'Button',
	2,
	'BOX. 004 POSITION 05',
	'NOT ORGANIZED',
	'Chave Tactil Redonda TSY6650 6X6X5mm 2T 180G;Figure1.jpg',
	'',
	''),
	
(	'Interruptor deslizante para Arduino LilyPad',
	'Interruptor para controle de ligado/desligado.',
	'Button',
	1,
	'Paper Box 06',
	'NOT ORGANIZED',
	'Slide_Switch_AYZ0202__Arduino_LilyPad;Figure11.png;Figure2.png;Figure3.png;Figure4.png',
	'',
	'')
;