/*
 * Button
 */
INSERT INTO item( name, description, category, quantity, locationBox, status, locationImage, locationDatasheet, locationAttachment ) VALUES
(
	'Boia de Nível Magnético para Água',
	'Boia Sensor de Nível Lateral Magnético para Água; Material: ABS; Tensão Máxima: 110 VDC; Corrente Máxima: 0,5A; Potencia Máxima suportada: 10W; Exemplo: Alimentação 110V, a corrente máxima é de 0,09mA',
	'Button',
	1,
	'BOX 004 POSITION 02',
	'NOT ORGANIZED',
	'Boia Sensor de Nivel Lateral Magnetico para Agua;Figure1.jpg;Figure2.jpg',
	'',
	''),

(	'Chave Push Button NA',
	'Chave Push Button NA',
	'Button',
	2,
	'BOX 004 POSITION 02',
	'NOT ORGANIZED',
	'Chave Push Button NA;Figure1.jpg',
	'',
	''),
	
(	'Chave Push Button NA DS-314 – 2T sem trava – vermelho',
	'Chave Push Button NA; Modelo: DS-314; Quantidade terminais: 2T sem trava; Cor: vermelho',
	'Button',
	1,
	'BOX 004 POSITION 02',
	'NOT ORGANIZED',
	'Chave Push Button NA DS-314 – 2T sem trava – vermelho;Figure1.jpg',
	'',
	''),
	
(	'Chave de Gancho Micro-switch KW9-XW',
	'Chave de Gancho Micro-switch KW9-XW',
	'Button',
	1,
	'BOX 004 POSITION 02',
	'NOT ORGANIZED',
	'Chave de Gancho Micro-switch KW9-XW;Figure1.jpg',
	'',
	''),
	
(	'Chave Alavanca',
	'Chave Alavanca',
	'Button',
	2,
	'BOX 004 POSITION 02',
	'NOT ORGANIZED',
	'Chave Alavanca;Figure1.png',
	'',
	''),
	
(	'Chave táctil KFC-A06 – 4T 180º',
	'Chave táctil; Modelo: KFC-A06; Dimensão: 12x12x4,3mm; 4 Terminais; Disposição de 180º',
	'Button',
	9,
	'BOX 004 POSITION 03',
	'NOT ORGANIZED',
	'Chave Tactil KFC-A06 12x12x4,3mm - 4T - 180deg;Figure1.jpg',
	'',
	''),
	
(	'Chave HH SS12D00G3 3T',
	'Chave HH SS12D00G3 com 3 Terminais',
	'Button',
	2,
	'BOX 004 POSITION 05',
	'NOT ORGANIZED',
	'Chave HH SS12D00G3 com 3 Terminais;Figure1.jpg',
	'',
	''),
	
(	'Chave táctil KFC-A06 - 4T 180°',
	'Chave táctil; Modelo KFC-A06; Dimensão: 6x6x5mm: 4 Terminais; Disposição 180°',
	'Button',
	4,
	'BOX 004 POSITION 05',
	'NOT ORGANIZED',
	'Chave Tactil KFC-A06 - 6x6x5mm - 4T - 180deg;Figure1.jpg',
	'',
	''),
	
(	'Chave Tactil Redonda TSY6650 - 2T 180º',
	'Chave Tactil Redonda; Modelo: TSY6650; Dimensão: 6x6x5mm; 2 Terminais; Disposição 180º',
	'Button',
	2,
	'BOX 004 POSITION 05',
	'NOT ORGANIZED',
	'Chave Tactil Redonda TSY6650 6x6x5mm 2T 180deg;Figure1.jpg',
	'',
	''),
	
(	'Interruptor deslizante para Arduino LilyPad',
	'Interruptor para controle de ligado/desligado.',
	'Button',
	1,
	'PAPER BOX 06',
	'NOT ORGANIZED',
	'Slide Switch AYZ0202 to Arduino LilyPad;Figure1.png;Figure2.png;Figure3.png;Figure4.png',
	'',
	'')
;