/*
 * Display
 */
INSERT INTO item( name, description, category, quantity, locationBox, status, locationImage, locationDatasheet, locationAttachment ) VALUES
(	'Nextion HMI NX3224T024',
	'NX3224T024 tem 65K (65536) cores (16 bit - 5R6G5B), resolução de 320×240 pixels (também pode configurar 240×320 pixels), sensor resistivo, luz de fundo, suporte a cartão SD, e comunicação serial.',
	'Display',
	1,
	'',
	'NOT ORGANIZED',
	'NX3224T024;Figure1.jpg;Figure2.jpg;Figure3.jpg;Figure4.jpg;Figure5.jpg;Figure6.jpg;Figure7.jpg;Figure8.jpg;Figure9.jpg;Figure10.jpg;Figure11.jpg;Figure12.jpg',
	'NX3224T024 - ITEAD Wiki.pdf',
	''),
	
(	'Módulo LCD Nokia 5110',
	'Módulo LCD Nokia 5110 de 1.6\" com chip PCD8544 de 48x48 pixels com tensão de 2.7V ~ 3.3V, interface SPI, corrente de operação <5mA, com iluminação <20mA.',
	'Display',
	1,
	'BOX 000',
	'NOT ORGANIZED',
	'Module LCD Nokia 5110;Figure1.jpg',
	'Module LCD Nokia 5110;Nokia5110.pdf',
	'Module LCD Nokia 5110;Adafruit-PCD8544-Nokia-5110-LCD-library-1.1.1.zip;Adafruit-GFX-Library-1.7.4.zip;BitmapEncoder-master.zip;LCDAssistant.zip;LCDAssistantCMD.zip;TheDotFactory-0.1.4.7z'),
	
(	'AGM-1604A-801 - Display de Cristal Liquido 16x4',
	'Display de Cristal Liquido modelo AGM-1604A-801, no formato 16*4 caracteres, com luz branca de fundo e cor de fundo azul.',
	'Display',
	1,
	'BOX 000',
	'NOT ORGANIZED',
	'16x4 LCD Display White-Blue LED Backlight;Figure1.jpg',
	'16x4 LCD Display White-Blue LED Backlight;AGM-1604A-801.pdf',
	'16x2 LCD Display White-Blue LED Backlight;Arduino - HelloWorld.pdf;In-Depth Tutorial to Interface 16x2 Character LCD Module with Arduino.pdf;HelloWord.ino'),
	
(	'Módulo Touch Screen TFT 3.2in',
	'Módulo Touch Screen TFT 3.2in, modelo TFT01-3.2, com 65k core, resolução 320x240 pixels e tensão de trabalho de 3.3V.',
	'Display',
	1,
	'BOX 000',
	'NOT ORGANIZED',
	'3.2 inch TFT LCD Screen Module;Figure1.jpg;Figure2.jpg',
	'3.2 inch TFT LCD Screen Module;SSD1289-spec.pdf',
	'3.2 in TFT LCD Screen Module;UTFT.zip;3.2 inch TFT Touch LCD.zip;LCD 3.2 TFT LCD Screen Module.zip;The instruction for mega2560 board and 3.2 inch touch screen and shield.zip'),
	
(	'1602A - Display de Cristal Liquido 16x2',
	'Display de Cristal Liquido; Modelo 6514 com 16 caracteres x 2 linhas, luz de fundo azul, caracteres branco e tensão de alimentação de 5VDC',
	'Display',
	1,
	'BOX 000',
	'NOT ORGANIZED',
	'16x2 LCD Display White-Blue LED Backlight;Figure1.jpg;Figure2.jpg;Figure3.jpg',
	'16x2 LCD Display White-Blue LED Backlight;eone-1602a1.pdf',
	'16x2 LCD Display White-Blue LED Backlight;Arduino - HelloWorld.pdf;In-Depth Tutorial to Interface 16x2 Character LCD Module with Arduino.pdf;HelloWord.ino'),
	
(	'Módulo matriz de LEDs vermelho com MAX7219',
	'Módulo matriz de LEDs (8x8) vermelho com catodo comum usando o chip MAX7219, alimentado em 5VDC, comunicação SPI e dimensões de 5cm de comprimento, 3.2cm de largura e 1.5cm de altura.',
	'Display',
	1,
	'BOX 000',
	'NOT ORGANIZED',
	'MAX7219 Dot Matrix Display Module;Figure1.jpg',
	'MAX7219 Serially Interfaced, 8-Digit LED Display Drivers;MAX7219-MAX7221 Serially Interfaced, 8-Digit LED Display Drivers.pdf',
	'MAX7219 Dot Matrix Display Module;LedControl-master.zip;8x8 LED Matrix MAX7219 Tutorial with Scrolling Text and Android Control via Bluetooth.zip;Aprenda a usar o Módulo Matriz de LEDs com MAX7219 - Embarcados.pdf'),
	
(	'Módulo OLED Display 0.96 polegadas Azul/Amarelo 128X64 SPI',
	'Módulo OLED Display de 0.96 polegadas nas cores Azul e Amarelo com resolução de 128X64 pixels e comunicação SPI.',
	'Display',
	1,
	'BOX 000',
	'NOT ORGANIZED',
	'0.96 inch SPI Serial 128X64 Yellow Blue OLED Display Module;Figure1.jpg;Figure2.jpg;Figure3.jpg;Figure4.jpg',
	'0.96 inch SPI Serial 128X64 Yellow Blue OLED Display Module;SSD1306.pdf',
	'0.96 inch SPI Serial 128X64 Yellow Blue OLED Display Module;Adafruit_SSD1306-2.0.4.zip;Adafruit-GFX-Library-1.7.4.zip'),
	
(	'Módulo OLED Display 1.3 polegadas Branco 128X64 SPI',
	'Módulo OLED Display de 1.3 polegadas na cor Branca com resolução de 128X64 pixels e comunicação SPI.',
	'Display',
	1,
	'BOX 000',
	'NOT ORGANIZED',
	'1.3 inch SPI Serial 128X64 Yellow Blue OLED Display Module;Figure1.jpg;Figure2.jpg;Figure3.jpg;Figure4.jpg',
	'1.3 inch SPI Serial 128X64 Yellow Blue OLED Display Module;sh1106_datasheet.pdf',
	'1.3 inch SPI Serial 128X64 Yellow Blue OLED Display Module;Getting started with µOLED displays.zip')
;