/*
 * Integrated Circuit
 */
INSERT INTO item( name, description, category, quantity, locationBox, status, locationImage, locationDatasheet, locationAttachment ) VALUES
(	'NE555 - Timer',
	'Timer com baixo tempo de turn-off, máxima frequência de operação maior que 500kHz, tempo de microsegundos à horas, saída de até 200mA, entre outros.',
	'Integrated Circuit',
	4,
	'',
	'NOT ORGANIZED',
	'NE555.jpg',
	'',
	''),
	
(	'MT8870DE - Receptor integrado de DTMF',
	'Receptor integrado de DTMF com modo de baixa potência, inibidor, aplicações em sistemas de cartão de crédito, controle remoto, entre outros.',
	'Integrated Circuit',
	1,
	'',
	'NOT ORGANIZED',
	'MT8870.jpg',
	'',
	''),
	
(	'MAX232N/ST232BN - Driver e Receiver EIA-232',
	'Driver e Receiver EIA-232, com operação acima até 120kbits/s, com dois drivers e dois receptores e tensão de alimentação +-30V.',
	'Integrated Circuit',
	3,
	'',
	'NOT ORGANIZED',
	'MAX232N.jpg;ST232.jpg',
	'',
	''),

(	'ADC0804LCN - Conversor A/D de 8Bit',
	'Conversor A/D de resolução de 8 bits com tempo de conversão de 100us. Tensão de alimentação de 5V com intervalo de tensão de entrada de 0~5V.',
	'Integrated Circuit',
	1,
	'',
	'NOT ORGANIZED',
	'ADC0804LCN.jpg',
	'',
	''),
	
(	'L293B - Drivers de quatro canais',
	'Drivers com quatro canais com corrente de saída de 1A por canal e 2A de pico, alta imunidade a ruídos e proteção contra sobre temperatura.',
	'Integrated Circuit',
	1,
	'',
	'NOT ORGANIZED',
	'L293D.jpg',
	'',
	''),
	
(	'ULN2003APG - Arranjo de 7 Darlington',
	'Arranjo de 7 Darlington de alta corrente, sinais 5V TTL e CMOS e 500mA por saída.',
	'Integrated Circuit',
	1,
	'',
	'NOT ORGANIZED',
	'ULN2803.jpg;ULN2003APG.jpg',
	'',
	''),
	
(	'74HC595 - conversor de serial para paralelo',
	'Conversor com registrador de deslocamento de 8 bits com registradores de saída com 3 estados, alimentação de 2~6V, e aplicações em switches de rede, dislpay de LEDs e servidores.',
	'Integrated Circuit',
	8,
	'',
	'NOT ORGANIZED',
	'SN74HC595.jpg',
	'',
	''),
	
(	'4019 - Seletor de Porta AND/OR CMOS',
	'Seletor de Porta AND/OR CMOS com 4 destas, com aplicações em seleção de porta AND*OR, deslocamento para direita/esquerda de registradores, entre outros.',
	'Integrated Circuit',
	2,
	'',
	'NOT ORGANIZED',
	'CD4019.jpg',
	'',
	''),
	
(	'74HC238 - Decoder/Demultiplexador inverso e não-inverso',
	'Decoder/Demultiplexador inverso e não-inverso de alta velocidade com 8 bits, tensão de 2~6V e tensão nominal de 3.3V e 5V.',
	'Integrated Circuit',
	3,
	'',
	'NOT ORGANIZED',
	'74HC238.jpg;CD74HC238.jpg',
	'',
	''),
	
(	'4511 - Driver decodificador BCD para display de 7 segmentos',
	'Driver decodificador BCD para display de 7 segmentos com aplicações em display de LED de catodo comum, catodo comum multiplexado, incandescente ou de fluorescente de baixa tensão.',
	'Integrated Circuit',
	4,
	'',
	'NOT ORGANIZED',
	'CD4511.jpg',
	'',
	''),
	
(	'74LS245 - Transceptor de Barramento Octal com 3 estados de saída',
	'Transceptor de Barramento Octal com 3 estados de saída, com aplicações em construção de automação, controle e automação de fabricas e testes e medidas.',
	'Integrated Circuit',
	4,
	'',
	'NOT ORGANIZED',
	'SN74LS245.jpg',
	'',
	''),
	
(	'4011 - Quatro portas NAND',
	'Quatro portas NAND com duas entradas por porta.',
	'Integrated Circuit',
	2,
	'',
	'NOT ORGANIZED',
	'CD4011.jpg',
	'',
	''),
	
(	'4001 - Quatro portas NOR',
	'Quatro portas NOR com duas entradas por porta.',
	'Integrated Circuit',
	2,
	'',
	'NOT ORGANIZED',
	'CD4001.jpg',
	'',
	''),
	
(	'74HC32 - Quatro portas OR',
	'Quatro portas OR com duas entradas por porta.',
	'Integrated Circuit',
	2,
	'',
	'NOT ORGANIZED',
	'SN74HC32.jpg',
	'',
	''),
	
(	'74HC00 - Quatro portas NAND',
	'Quatro portas NAND com duas entradas por porta.',
	'Integrated Circuit',
	2,
	'',
	'NOT ORGANIZED',
	'SN74HC00N.jpg',
	'',
	''),
	
(	'74HC08 - Quatro portas AND',
	'Quatro portas AND com duas entradas por porta.',
	'Integrated Circuit',
	2,
	'',
	'NOT ORGANIZED',
	'SN74HC08N.jpg',
	'',
	''),
	
(	'74HC04 - Seis portas inversoras',
	'Seis portas inversoras, isto é, seis portas NOT.',
	'Integrated Circuit',
	2,
	'',
	'NOT ORGANIZED',
	'SN74HC04N.jpg',
	'',
	''),
	
(	'4071 - Quatro portas OR',
	'Quatro portas OR com duas entradas por porta.',
	'Integrated Circuit',
	2,
	'',
	'NOT ORGANIZED',
	'HEF4071.jpg',
	'',
	''),
	
(	'LM567CN - Decodificador de Tom',
	'Decodificador de tom de frequência central ajustável de 0.01Hz até 500kHz, com saída lógica de até 100mA, com aplicações em decodificação de toque de tom, oscilador de precisão, controle ultrassônico, entre outros.',
	'Integrated Circuit',
	2,
	'',
	'NOT ORGANIZED',
	'LM567-NE567-tone-decoder.jpg',
	'',
	''),
	
(	'MCP2551 - CAN Transceiver',
	'Transceiver para comunicação entre TTL e CAN e permitindo comunicações até 112 nós.',
	'Integrated Circuit',
	2,
	'',
	'NOT ORGANIZED',
	'MCP2551.jpg',
	'AN228 - A CAN Physical Layer Discussion.pdf;AN713 - An introduction to the CAN protocol that discusses the basics and key features.pdf;MCP2551- High-Speed CAN Transceiver.pdf;TB3101 - MCP2551 to MCP2561 Migration.pdf',
	''),
	
(	'IR2104 - Driver Meia-Ponte',
	'VOFFSET: 600V max.; IO+/-: 130 mA / 270 mA; ton/off (typ.): 680 & 150 ns; Deadtime (typ.): 520 ns; Gate drive supply (VOUT) range from 10 to 20V; 3.3V, 5V and 15V input logic compatible',
	'Integrated Circuit',
	1,
	'',
	'NOT ORGANIZED',
	'IR2104_1.jpg;IR2104_2.jpg',
	'IR2104 - Half-Bridge Driver.pdf',
	''),
	
(	'ADC0832 - Conversor Serial A/D de 8Bit Multiplexado',
	'No Zero or Full-Scale Adjust Required; 2-Channel Multiplexer Options with Address Logic; 0V to 5V Input Range with Single 5V Power Supply; Resolution: 8 Bits; Total Unadjusted Error: ±1/2 LSB and ±1 LSB; Low Power: 15 mW; Conversion Time: 32 μs',
	'Integrated Circuit',
	1,
	'',
	'NOT ORGANIZED',
	'ADC0832_1.jpg;ADC0832_2.jpg',
	'ADC0831-N, ADC0832-N, ADC0834-N, ADC0838-N - 8-Bit Serial I-O A-D Converters with Multiplexer Options.pdf',
	''),
	
(	'ULN2803A - Array de Transistores Darlington',
	'500 mA - Rated Collector Current (Single Output); High-Voltage Outputs: 50 V; Output Clamp Diodes; Inputs Compatible With Various Types of Logic',
	'Integrated Circuit',
	1,
	'',
	'NOT ORGANIZED',
	'ULN2803_1.jpg;ULN2803_2.jpg',
	'ULN2803A - Darlington Transistor Arrays.pdf',
	''),
	
(	'4070 - Quatro portas OR Exclusivo (XOR)',
	'Quatro portas OR Exclusivo com duas entradas por porta.',
	'Integrated Circuit',
	3,
	'',
	'NOT ORGANIZED',
	'HCF4070BE.png',
	'HCF4070.pdf;HCF4070B.pdf',
	''),
	
(	'TDA7439 - Processador de áudio controlado digitalmente',
	'Processador de áudio controlado digitalmente de três bandas, entrada multiplexada, entre outras.',
	'Integrated Circuit',
	1,
	'',
	'NOT ORGANIZED',
	'TDA7439_1.jpg;TDA7439_2.jpg',
	'TDA7439 - Three-band digitally-controlled audio processor.pdf',
	'')
;