/*
 * Microcontroller
 */
INSERT INTO item( name, description, category, quantity, locationBox, status, locationImage, locationDatasheet, locationAttachment ) VALUES
(	'PIC16F84A - Microcontrolador',
	'Microcontrolador de 8 bit, com apenas 35 instruções, 1024 palavras de memória de programa, 68 bytes RAM, 64 bytes EEPROM.',
	'Microcontroller',
	5,
	'',
	'NOT ORGANIZED',
	'PIC16F84A.jpg',
	'',
	''),
	
(	'PIC16F628A - Microcontrolador',
	'Microcontrolador de 8 bit, com apenas 35 instruções, 2048 palavras de memória de programa, 224 bytes RAM, 128 bytes EEPROM, 2 comparadores, timer de 8/16 bits, PWM de 10 bits e USART.',
	'Microcontroller',
	3,
	'',
	'NOT ORGANIZED',
	'PIC16F628A.jpg',
	'',
	''),
	
(	'ATMEGA328P-PU - Microcontrolador',
	'Microcontrolador CMOS 8-bit de 131 instruções, RISC, 32 registradores trabalho uso geral 8-bit, 32KBytes memória flash, 1KBytes EEPROM, 2KBytes SRAM, 2 timer/contador 8-bit, 1 timer/contador 16-bit, 6 canais PWM, 8 canais A/D 10-bit, entre outros.',
	'Microcontroller',
	10,
	'',
	'NOT ORGANIZED',
	'ATMEGA328P-PU.jpg',
	'',
	''),
	
(	'PIC12F675 - Microcontrolador',
	'Microcontrolador 8 pinos em 8 bits com 6 pinos I/O, 1 comparador analógico, 1024 palavras de memória de programa, 64 bytes SRAM, 128 bytes EEPROM, 6 I/O, 4 canais I/O de 10 bits e um timer de 8 bits e outro de 16 bits.',
	'Microcontroller',
	1,
	'',
	'NOT ORGANIZED',
	'PIC12F675.jpg',
	'',
	''),
	
(	'PIC16F688 - Microcontrolador',
	'Microcontrolador de 8 bit, com 35 instruções, 4096 palavras de mem. de programa, 256 bytes SRAM, 256 bytes EEPROM, 12 pinos I/O, módulo comparador analógico, conversor A/D resolução 10 bits e 8 canais, módulo USART (RS-485/RS-232/LIN) 1.2 e ICSP.',
	'Microcontroller',
	1,
	'',
	'NOT ORGANIZED',
	'microcontrolador_PIC16F688.jpg',
	'PIC16F688.pdf',
	''),
	
(	'PIC18F4550 - Microcontrolador',
	'Microcontrolador com USB 2.0, 13 canais A/D de 10 bits, 24k bytes de Flash, SRAM de 2048 bytes, 256 bytes de EEPROM, 35 I/O, SPP, SPI, I2C, EUSART, timers de 8 (1) e 16 (3) bits.',
	'Microcontroller',
	1,
	'',
	'NOT ORGANIZED',
	'PIC18F4550.jpg',
	'',
	''),
	
(	'PIC18F4520 - Microcontrolador',
	'Program Memory Type: Flash; Program Memory Size (KB): 32; CPU Speed (MIPS/DMIPS): 10; SRAM (B): 1,536; Data EEPROM/HEF (bytes): 256; Digital Communication Peripherals: 1-UART, 1-SPI, 1-I2C1-MSSP(SPI/I2C); Capture/Compare/PWM Peripherals: 1 CCP, 1 ECCP; Timers: 1 x 8-bit, 3 x 16-bit; ADC Input: 13 ch, 10-bit; Number of Comparators: 2; Operating Voltage Range (V): 2 to 5.5',
	'Microcontroller',
	1,
	'',
	'NOT ORGANIZED',
	'PIC18F4520;Figure1.png',
	'PIC18F4520;PIC18F2420,2520,4420,4520 - Data Sheet 28,40,44-Pin Enhanced Flash Microcontrollers with 10-Bit A,D and nanoWatt Technology.pdf',
	''),
	
(	'dsPIC4013 - Microcontrolador',
	'Microcontrolador alta performance de 16 bits para controle de sinal digital, 48k+16k bytes de memória de programa, 2048 bytes SRAM, 1024 bytes EEPROM, 5 timers 16 bits, 4 PWM, interface codec AC 97 e I2S, 13 canais A/D 12 bits, 2 UART, 1 SPI/I2C/CAN',
	'Microcontroller',
	1,
	'',
	'NOT ORGANIZED',
	'dsPIC30F4013.png',
	'',
	''),
	
(	'80C51 - Microcontrolador',
	'Microcontrolador 80C51 de chip CHMOS de 8 bit, com 128 x 8 bit de RAM, 32 linhas de programação I/O, 2 timers/contadores, processador boleano, ...',
	'Microcontroller',
	1,
	'',
	'NOT ORGANIZED',
	'80C51.jpg',
	'',
	'')
;